### ISSUE TITLE
Storage accounts created by azurefile-csi-driver is not getting deleted

### ISSUE THREAD

**Issue by rajdhandus** [kubernetes-sigs/azurefile-csi-driver#1010]
**What happened**:

- we observed that we are hitting the storage account limits for our subscription.
- when analyzed - it looks like there are lots of empty storage accounts

"total_storages": 401,
"empty_storages": 339,
"non_empty_storages": 62,

**What you expected to happen**:
- The entity creating storage accounts should also ensure proper cleanup happens or if possible that the storage accounts are re-used.

**How to reproduce it**:
- Create a PVCs that use azurefile-csi and delete them on a periodic interval
- Scale the cluster up and restart the VMs frequently

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: v2.4.0-0-g56242df5
- Kubernetes version (use `kubectl version`): 1.22.4
- OS (e.g. from /etc/os-release): linux
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
hi, that's a regression in azure file csi driver v1.13 and v1.14, could you upgrade csi driver version  to a higher version, e.g. v1.15.0 ~ v1.17.0, thanks.

**Comment by rajdhandus** [comment]
@andyzhangx - we have installed the drivers via EnableAzureDiskFileCSIDriver flag... How do we upgrade the version?

`--aks-custom-headers EnableAzureDiskFileCSIDriver=true`

**Comment by andyzhangx** [comment]
if it's on AKS, the fixed version has already been rolled out to all regions, just delete the empty storage accounts

**Comment by rajdhandus** [comment]
thanks for the confirmation. is there a way to check if it's rolled out to our clusters? Is there a version in the log? "v2.4.0-0-g56242df5" is the one i saw in the logs...

**Comment by andyzhangx** [comment]
just run `kubectl get po -n kube-system -o yaml | grep azurefile-csi`, you will get the azure file driver version.

**Comment by rajdhandus** [comment]
we have a few clusters in Prod. We have seen the issue in 2/6 so far. Given below is the breakdown. Not sure if the rollout is deployed to all the clusters. Can you please check and confirm?

**Comment by andyzhangx** [comment]
@rajdhandus I could confirm the issue was resolved by rolling out v1.15.0 version (or reverting to v1.12.0 version), could you clean up empty storage accounts in `EastUS` and `WestEU` regions, the account leak issue won't happen any more.

**Comment by rajdhandus** [comment]
this issue has resurfaced again in 1b and 3b. The csi-azurefile-node-* pods seem to have an age of 11 days..

| IssueSeen | Cluster # | ClusterLocation | Image | ImageID |
| -- | -- | -- | -- | -- |
| Yes   | 3b  | WestEU | image: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi:v1.17.0 | imageID: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi@sha256:ba76af87826f04d3258108e4f204ba62bdae61f5a5ac66273f646dddb7477139  |
| Yes   | 1b  | EastUS | image: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi:v1.17.0 | imageID: mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi@sha256:ba76af87826f04d3258108e4f204ba62bdae61f5a5ac66273f646dddb7477139  |
