### ISSUE TITLE
VHD disks don't respect fsgroup

### ISSUE THREAD

**Issue by gnufied** [kubernetes-sigs/azurefile-csi-driver#1012]
I was testing the VHD feature of azurefile and it integrates kinda poorly with fsgroup specified in pod. Currently it looks like, if volume is in diskMode, it ignores supplied `fsGroup` completely - https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/pkg/azurefile/nodeserver.go#L248

But even if it did, since now we are mounting the cifs file and then creating a loopback device on it, ideally it is kubelet which must recursively chown and chmod files. 

This is basically a side effect of exposing multiple volume types under same CSI driver name and will be tricky to fix.

**Comment by andyzhangx** [comment]
agree, for this case, if `NodeServiceCapability_RPC_VOLUME_MOUNT_GROUP` is set, the driver should set ownership itself since all volume types supported by this driver shares the same driver name.

**Comment by andyzhangx** [comment]
here is the workaround fix for vhd disk: https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1013

**Comment by gnufied** [comment]
But the workaround is precisely what drivers are *not* supposed to do. That is why parameter is called "volume_mount_group" not generic "fsgroup" or something similar. Drivers are *only* supposed to use the `volume_mount_group` for mounting the volumes - period. By relying on internal k8s `SetVolumeOwnership` function - driver is basically hardcoding for k8s compatibility and driver does not benefit from things like `fsGroupChangePolicy` etc because we will be *always* recursively chowning files.

**Comment by andyzhangx** [comment]
while for this driver, `driverSupportsCSIVolumeMountGroup` is already `true`, which means it won't check `fsGroupPolicy`:

https://github.com/kubernetes/kubernetes/blob/c8b3b293c047ff9971cb5542a446c9c525877f50/pkg/volume/csi/csi_mounter.go#L279-L292

```
	if !driverSupportsCSIVolumeMountGroup && c.supportsFSGroup(fsType, mounterArgs.FsGroup, c.fsGroupPolicy) {
		// Driver doesn't support applying FSGroup. Kubelet must apply it instead.

		// fullPluginName helps to distinguish different driver from csi plugin
		err := volume.SetVolumeOwnership(c, mounterArgs.FsGroup, mounterArgs.FSGroupChangePolicy, util.FSGroupCompleteHook(c.plugin, c.spec))
		if err != nil {
			// At this point mount operation is successful:
			//   1. Since volume can not be used by the pod because of invalid permissions, we must return error
			//   2. Since mount is successful, we must record volume as mounted in uncertain state, so it can be
			//      cleaned up.
			return volumetypes.NewUncertainProgressError(fmt.Sprintf("applyFSGroup failed for vol %s: %v", c.volumeID, err))
		}
		klog.V(4).Info(log("mounter.SetupAt fsGroup [%d] applied successfully to %s", *mounterArgs.FsGroup, c.volumeID))
	}
```

**Comment by gnufied** [comment]
Yes, that is what I was talking about. The `volume_mount_group` parameter should *never* be used for recursively chown/chmoding files inside a driver. That is kubelet's job (if needed).
