### ISSUE TITLE
Error upgrade to 1.18 - CSIDriver fsGroupPolicy immutable

### ISSUE THREAD

**Issue by Sartigan** [kubernetes-sigs/azurefile-csi-driver#1034]
**What happened**: We've upgraded from 1.17 to 1.18

**What you expected to happen**: Successfull helm upgrade !

**How to reproduce it**: install 1.17 and upgrade to 1.18

**Anything else we need to know?**: Full error:
```
cannot patch "file.csi.azure.com" with kind CSIDriver: CSIDriver.storage.k8s.io "file.csi.azure.com" is invalid: spec.fsGroupPolicy: Invalid value: "ReadWriteOnceWithFSType": field is immutable
```

Caused by this: https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1017/files

Used with Kubernetes 1.21.7

**Comment by andyzhangx** [comment]
pls run `kubectl delete -f CSIDriver file.csi.azure.com` and then upgrade

**Comment by Sartigan** [comment]
Wouldn't you say this is some kind of breaking change? Manual operations are required to upgrade...

**Comment by andyzhangx** [comment]
sorry when I changed the config, actually we don't know it's a breaking change in upgrade, will update in the release notes, thanks for pointing out.
