### ISSUE TITLE
Release policy for breaking changes

### ISSUE THREAD

**Issue by mauriciopoppe** [kubernetes-sigs/azurefile-csi-driver#1043]
**Is your feature request related to a problem?/Why is this needed**

I saw that [v1.18.0 release](https://github.com/kubernetes-sigs/azurefile-csi-driver/releases/tag/v1.18.0) introduces a breaking change, such breaking changes usually require additional action by the users however it was introduced in a minor release.

In comparison other CSI projects like the external-snapshot artifacts go through a major release when there's a breaking change.

What's the policy around releasing breaking changes?

/cc @msau42 @jingxu97

**Comment by andyzhangx** [comment]
@mauriciopoppe the word `Breaking changes` may be incorrect, it actually does not block upgrade or usage since there is no API breaking change. Maybe it's better renaming as `Notion before upgrading to this release`, wdyt?
