### ISSUE TITLE
custom domain support

### ISSUE THREAD

**Issue by rgr-ralf-it** [kubernetes-sigs/azurefile-csi-driver#1047]
As you know, ASA allows to use custom domain in networking:

![image](https://user-images.githubusercontent.com/106732891/175789745-a976bf96-a09e-4ddd-afd2-fdedb109cc5b.png)

Then looking at list of parameters of this driver https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/driver-parameters.md I could not find one / or guess which to use.

Please give short guidance how to use custom domain with this driver.

**Comment by andyzhangx** [comment]
@rgr-ralf-it Are you using AKS? aks agent node does not support AAD domain join now, from CSI driver perspective, if node is domain joined, you could just append `-o domain=xxx` in mount options in storage class or PV, it should be supported if node is domain joined.
