### ISSUE TITLE
Move Azure File Share to Another Subscription

### ISSUE THREAD

**Issue by mauriciocirelli** [kubernetes-sigs/azurefile-csi-driver#1126]
Dear,

We have a Premium File Share (nfs) that is used by a StorageClass (provisioner: file.csi.azure.com).
We would like to move that File Share to another subscription.
Is it possible to update the parameters (subscriptionID and resourceGroup) from a StorageClass?

How could we perform this operation while keeping the data and the persistent volumes?

Thank you!

**Comment by andyzhangx** [comment]
I think you need to create a new storage class with `subscriptionID`, `resourceGroup`, `shareName` parameters

**Comment by mauriciocirelli** [comment]
@andyzhangx Thank you for your reply. Unfortunately, that is what we would like to avoid... Creating a new StorageClass would force us to recreate the Persistent Volume Claims and Persistent Volumes... We would lose the contents of those volumes, right? Is there any way to avoid losing this data?

**Comment by andyzhangx** [comment]
> @andyzhangx Thank you for your reply. Unfortunately, that is what we would like to avoid... Creating a new StorageClass would force us to recreate the Persistent Volume Claims and Persistent Volumes... We would lose the contents of those volumes, right? Is there any way to avoid losing this data?

@mauriciocirelli if you are using smb protocol, you could bring you own account key with k8s secret, you don't need to set `subscriptionID`, `resourceGroup`, but now you are using nfs protocol, it's not supported.

And you won't lose data, after the migration, you need to create new PV, PVC to mount original nfs file share.

**Comment by mauriciocirelli** [comment]
> And you won't lose data, after the migration, you need to create new PV, PVC to mount original nfs file share.

Ahh I see.. Thank you!
