### ISSUE TITLE
Add support for Workload Identity

### ISSUE THREAD

**Issue by RomanBednar** [kubernetes-sigs/azurefile-csi-driver#1138]
**Is your feature request related to a problem?/Why is this needed**

 - A customer using ARO wants to spin up an OpenShift cluster with "az aro create" without needing additional input, i.e. without the need for an AD account or service principal credentials, and the identity used is never visible to the customer and cannot appear in the cluster.
 
 - As an administrator, I want to deploy OpenShift 4 and run Operators on Azure using access controls (IAM roles) with temporary, limited privilege credentials.

**Describe the solution you'd like in detail**

CSI Driver should support identity federation to enable workload identities, similar work is currently WIP in [cluster-api-provider-azure](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2814/files#diff-8f168651958e0a88d9402ac98e3b8764c9a4b54d29de8284def5e2c9070dd11bR280).

In order to use identity federation the driver has to be updated to use azidentity instead of autorest/adal.

**Describe alternatives you've considered**

Alternatively, if we can't migrate the driver to azidentity, OpenShift Operators might use OIDC sidecar as a short term solution: https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview#how-to-migrate-to-workload-identity

**Additional context**

OpenShift Enhancement: https://github.com/openshift/enhancements/blob/40aac25619eb2e1bd2fb55a90bdcdddf7d7346e2/enhancements/cloud-integration/azure/azure-workload-identity.md

**Comment by andyzhangx** [comment]
if we want to support CSI driver with workload identity, migration to MSAL should be the dependency, related to https://github.com/kubernetes-sigs/cloud-provider-azure/issues/430

**Comment by cvvz** [comment]
Hi, @RomanBednar ,  could you please kindly take a look at this pr: https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1193? Especially the [document](https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1193/files#diff-4f8da2bb5977ab994b556b1f0d255bc53ca626b62bc3307561d6210929ed05d9), and make sure whether it satisfies your need?

**Comment by andyzhangx** [comment]
the adal lib token refresh issue depends on https://github.com/Azure/go-autorest/pull/719
