### ISSUE TITLE
CSI migration from in-tree driver to CSI driver go beta

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azurefile-csi-driver#115]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like in detail**

design doc: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/csi-migration.md

depends on cs-attacher v3.0.0: https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/430

depends on csi-provisioner fix: https://github.com/kubernetes/kubernetes/pull/94853

**Describe alternatives you've considered**

**Additional context**

**Comment by andyzhangx** [comment]
now depends on this PR: https://github.com/kubernetes/kubernetes/pull/90162, this PR would cherry-pick to 1.17, 1.18, will azure file and disk migration would go beta in 1.19

**Comment by rfranzke** [comment]
Sounds great. Happy to help with opening the cherry-pick PRs after kubernetes/kubernetes#90162 is merged.

**Comment by andyzhangx** [comment]
Azure disk & azure file migration would go beta in 1.19, here is the PR: https://github.com/kubernetes/kubernetes/pull/90896
related KEP:
https://github.com/kubernetes/enhancements/issues/1490

**Comment by andyzhangx** [comment]
waiting for https://github.com/kubernetes-csi/external-provisioner `v2.0.0` release

**Comment by andyzhangx** [comment]
related work: https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/419

**Comment by andyzhangx** [comment]
waiting for 
 - `v0.20.0` release on https://github.com/kubernetes/csi-translation-lib
 - upgrade to csi-translation-lib `v0.20.0` on https://github.com/kubernetes-csi/external-provisioner `v2.0.3`
 - upgrade to csi-provisioner `v2.0.3` in this driver
 - enable migration CI test

**Comment by andyzhangx** [comment]
csi-provisioner has been upgrade to `v2.0.4`, now try to enable csi migration test: https://github.com/kubernetes/test-infra/pull/19790

**Comment by andyzhangx** [comment]
update:
```
Summarizing 5 Failures:

[Fail] Dynamic Provisioning [It] should create a volume on demand with mount options [kubernetes.io/azure-file] [file.csi.azure.com] [Windows] 
/home/prow/go/src/sigs.k8s.io/azurefile-csi-driver/test/e2e/testsuites/testsuites.go:514

[Fail] Dynamic Provisioning [It] should create multiple PV objects, bind to PVCs and attach all to different pods on the same node [kubernetes.io/azure-file] [file.csi.azure.com] [Windows] 
/home/prow/go/src/sigs.k8s.io/azurefile-csi-driver/test/e2e/testsuites/testsuites.go:519

[Fail] Dynamic Provisioning [It] should create a volume on demand and mount it as readOnly in a pod [kubernetes.io/azure-file] [file.csi.azure.com] [Windows] 
/home/prow/go/src/sigs.k8s.io/azurefile-csi-driver/test/e2e/testsuites/testsuites.go:548

[Fail] Dynamic Provisioning [It] should create a deployment object, write and read to it, delete the pod and write and read to it again [kubernetes.io/azure-file] [file.csi.azure.com] [Windows] 
/home/prow/go/src/sigs.k8s.io/azurefile-csi-driver/test/e2e/testsuites/testsuites.go:408

[Fail] Dynamic Provisioning [It] should create a volume on demand and resize it [kubernetes.io/azure-file] [file.csi.azure.com] [Windows] 
/home/prow/go/src/sigs.k8s.io/azurefile-csi-driver/test/e2e/testsuites/testsuites.go:514

Ran 6 of 25 Specs in 4414.212 seconds
FAIL! -- 1 Passed | 5 Failed | 0 Pending | 19 Skipped
--- FAIL: TestE2E (4414.22s)
```

**Comment by andyzhangx** [comment]
waiting for https://github.com/kubernetes/kubernetes/pull/96099 merged into k8s v1.17.14

**Comment by andyzhangx** [comment]
would be addressed by PR: https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/430
`mcr.microsoft.com/oss/kubernetes-csi/csi-attacher:v3.0.2` has the fix already: https://github.com/kubernetes/kubernetes/pull/94904

**Comment by andyzhangx** [comment]
found blocking issue: https://github.com/kubernetes/kubernetes/issues/96508

**Comment by andyzhangx** [comment]
kubernetes/kubernetes#96508 would be fixed by https://github.com/kubernetes/kubernetes/pull/97877, I think that's the last fix, migration test pass with PR: https://github.com/kubernetes/kubernetes/pull/97877
