### ISSUE TITLE
no longer needed replace line in go.mod

### ISSUE THREAD

**Issue by Morty-luo** [kubernetes-sigs/azurefile-csi-driver#1177]
It seems that `kubernetes-sigs/azurefile-csi-driver` at now indirectly depends on newer version `v0.6.0` of `golang.org/x/text`.
Keep according replace line in go.mod makes no sense but limits the update of `golang.org/x/text`. Should it be dropped? <br>
<https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/go.mod#L119>
```txt
golang.org/x/text v0.6.0 // indirect
```
<https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/go.mod#L141>
```txt
replace (
	...
	golang.org/x/text => golang.org/x/text v0.3.8
)
```

**Comment by andyzhangx** [comment]
nice catch, I have removed the version dependency in PR: https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1178
