### ISSUE TITLE
How to migrate storeAccountKey from true to false

### ISSUE THREAD

**Issue by susanwangmcpod** [kubernetes-sigs/azurefile-csi-driver#1218]
My customer uses AKS with Azure Files PVs, which were dynamically provisioned previously, and the storage account keys are stored in the secrets.

Now due to security policies, they need to rotate storage account keys periodically. If the PVs are dynamically provisioned from SC with parameter storeAccountKey: false, then it just needs to recreate pods after storage account keys are changed.

However, customer now has many existing PVs which were dynamically provisioned from SC without specifying the parameter storeAccountKey, so the storage account keys are stored in the secrets now.

So are there any ways to migrate storeAccountKey from true to false? If this is not possible, then whether we have any other methods to update secrets with new storage account keys automatically? Thanks in advance.

**Comment by andyzhangx** [comment]
@susanwangmcpod if you don't want to store AccountKey as secret, you need to:
1. grant kubelet identity reader permission to the storage accounts
2. when you rotate account key, existing azure file volume mount would become invalid, recreate those pods with azure file mounts, and azure file driver would use kubelet identity to get the updated account key directly.

**Comment by susanwangmcpod** [comment]
Thanks, Andy. I will have a test.

**Comment by susanwangmcpod** [comment]
@andyzhangx my customer spent some time in testing above shared steps. It works. But they feedbacked that this is still unable to meet their requirements, because pods are unable to access files after storage account keys rotate. This means their app still have some downtime until these pods are recreated. So customer is asking whether there exists any other methods to avoid such downtime when storage account keys rotate? Thanks in advance.

**Comment by andyzhangx** [comment]
> @andyzhangx my customer spent some time in testing above shared steps. It works. But they feedbacked that this is still unable to meet their requirements, because pods are unable to access files after storage account keys rotate. This means their app still have some downtime until these pods are recreated. So customer is asking whether there exists any other methods to avoid such downtime when storage account keys rotate? Thanks in advance.

@susanwangmcpod 
there is a better way to reduce downtime, e.g.

1. update secret with secondary account key
2. recreate pods one by one 
3. rotate primary account key
4. update secret with primary account key
5. recreate pods one by one

**Comment by susanwangmcpod** [comment]
Thanks, Andy.

**Comment by susanwangmcpod** [comment]
Hello @andyzhangx ,

I did some tests, and it looks like that kubelet identity always fetches the first storage account key (key1). Is this by design?

My guess is if kubelet identity can fetch the latest rotated key, then we may follow the similar steps as above to reduce downtime with kubelet identity as well.


Thanks.

**Comment by andyzhangx** [comment]
> Hello @andyzhangx ,
> 
> I did some tests, and it looks like that kubelet identity always fetches the first storage account key (key1). Is this by design?
> 
> My guess is if kubelet identity can fetch the latest rotated key, then we may follow the similar steps as above to reduce downtime with kubelet identity as well.
> 
> Thanks.

@susanwangmcpod that's a good suggestion, currently it's always getting the first key, but I think we make a change in the next version to always get the key with latest CreationTime, by that way, if you are using kubelet identity to get account key directly, it could be:
```
1. rotate secondary key
2. recreate pods one by one so that the smb mount would use the secondary key automatically
3. rotate primary account key
4. recreate pods one by one so that the smb mount would use the primary key automatically
```

```
// AccountKey an access key for the storage account.
type AccountKey struct {
	// KeyName - READ-ONLY; Name of the key.
	KeyName *string `json:"keyName,omitempty"`
	// Value - READ-ONLY; Base 64-encoded value of the key.
	Value *string `json:"value,omitempty"`
	// Permissions - READ-ONLY; Permissions for the key -- read-only or full permissions. Possible values include: 'KeyPermissionRead', 'KeyPermissionFull'
	Permissions KeyPermission `json:"permissions,omitempty"`
	// CreationTime - READ-ONLY; Creation time of the key, in round trip date format.
	CreationTime *date.Time `json:"creationTime,omitempty"`
}
```

**Comment by susanwangmcpod** [comment]
Many thanks, Andy.

**Comment by yzhang0727** [comment]
@andyzhangx  hello andy, for the time of next version release, do you have an estimation time?

**Comment by andyzhangx** [comment]
> @andyzhangx hello andy, for the time of next version release, do you have an estimation time?

@yzhang0727 working on this now

**Comment by rkarra08101992** [comment]
Hello Andy, I see that there so many manual steps involved to rotate keys. Is there a way to automatically do this without having to perform those steps?

**Comment by andyzhangx** [comment]
@rkarra08101992 after setting following two parameters in storage class, you could try following step 1 ~ 5 to validate it works, and the you could automate those cli commands

```
parameters:
  getLatestAccountKey: "true"
  storageAccountKey: "false"
```

1. update secret with secondary account key
2. recreate pods by moving pods to the node which does not have this file share mount (this could make sure remount happen)
3. rotate primary account key
4. update secret with primary account key
5. recreate pods by moving pods to the node which does not have this file share mount (this could make sure remount happen)
