### ISSUE TITLE
static provisioned pv can not get mounted to pod after auto-migration

### ISSUE THREAD

**Issue by xiaoping8385** [kubernetes-sigs/azurefile-csi-driver#1221]
Hi experts,
we have created intree static pv in k8s 1.23, and it works fine, however, after we upgrade to k8s 1.24, we found that all the workload pod can not running as pvs can not be attached, and we find that the migration flag is set as on by default, and we haven't set up our azurefile csi driver yet,so we install the azurefile csi driver, and after that all the csi pods get running, we found all the workload pod get running, however the application keep crash, and we found there are no data inside the mount path. 
Additionally, we found that there are no mounted azure file share  

```
[aa480175@azldfsjmp105 azure-pv-migrate]$ kubectl exec -it cacs-prod-automate-68dbb47fd4-pzw4d -n cacs-prod -- df -h
Filesystem                         Size Used Avail Use% Mounted on
overlay                          148G  38G 103G 27% /
tmpfs                            64M   0  64M  0% /dev
tmpfs                            14G   0  14G  0% /sys/fs/cgroup
/dev/sdc1                         148G  38G 103G 27% /etc/hostname
shm                             64M   0  64M  0% /dev/shm
/dev/sda2                         394G 4.3G 370G  2% /etc/hosts
```

we check the csi-node log and csi controller log, we can't found any obvious error. it said that the mount successfully.
Our the static pv description is defined like this:

 ```
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/bound-by-controller: "yes"
    creationTimestamp: "2022-10-01T20:21:56Z"
    finalizers:
    - kubernetes.io/pv-protection
    labels:
      usage: cacs-uatd-data-pv
    name: cacs-uatd-data-pv
    resourceVersion: "41713"
    uid: bbe3af7a-f700-45d9-be5e-ec5f56d268e0
  spec:
    accessModes:
    - ReadWriteMany
    azureFile:
      secretName: cacs-uatd-pv-secret
      secretNamespace: cacs-uatd
      shareName: cacs-uatd-data
    capacity:
      storage: 1Mi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: cacs-data-pv-claim
      namespace: cacs-uatd
      resourceVersion: "41697"
      uid: d76196f1-24e2-4520-bfac-a1e2a6e438f3
    persistentVolumeReclaimPolicy: Retain
    volumeMode: Filesystem
  status:
    phase: Bound
```
So is there any know issue or special design related to that static pv auto-migration?
Thanks!

**Comment by andyzhangx** [comment]
@xiaoping8385 could you share the csi-node logs?

**Comment by xiaoping8385** [comment]
@andyzhangx Thanks for reply, we need some time to reproduce the issue and collect the log, but I want to confirm first is that, will the static intree pv description will also get a annotation like "pv.kubernetes.io/migrated-to: file.csi.azure.com"? as I can confirm that the migrated dynamic pv will have such annotation, but I can't see this in static intree pv(check the above description after we upgrade to 1.24). Is that expected or works as designed?

**Comment by xiaoping8385** [comment]
So is that means the intree-static pv should continue to work without any manual change after uprade to k8s 1.24?

**Comment by andyzhangx** [comment]
> So is that means the intree-static pv should continue to work without any manual change after uprade to k8s 1.24?

@xiaoping8385 yes, while in long term, I think you should switch to use CSI driver volume directly, follow guide here: https://learn.microsoft.com/en-us/azure/aks/csi-migrate-in-tree-volumes

**Comment by xiaoping8385** [comment]
@andyzhangx  Thanks, one more question, I have defined azurefile csi driver as my default driver, I have recreated the pv with above pv definition yaml(in the comment 1),  and the mount issue has gone, and I check the new description and I found it looks like below 
```
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{"pv.kubernetes.io/provisioned-by":"file.csi.azure.com"},"name":"cacs-devd-data-pv-csi"},"spec":{"accessModes":["ReadWriteMany"],"capacity":{"storage":"1Mi"},"csi":{"driver":"file.csi.azure.com","nodeStageSecretRef":{"name":"azure-storage-account-c360nprdcusappdata01-secret","namespace":"cacs-devd"},"readOnly":false,"volumeAttributes":{"shareName":"cacs-devd-data"},"volumeHandle":"c360nprdcusappdata01#cacs-devd#cacs-devd"},"mountOptions":["dir_mode=0777","file_mode=0777","uid=0","gid=0","mfsymlinks","cache=strict","nosharesock","nobrl"],"persistentVolumeReclaimPolicy":"Retain","storageClassName":"azurefile-csi"}}
      pv.kubernetes.io/bound-by-controller: "yes"
      pv.kubernetes.io/provisioned-by: file.csi.azure.com
    creationTimestamp: "2023-04-13T16:15:06Z"
    finalizers:
    - kubernetes.io/pv-protection
    name: cacs-devd-data-pv-csi
    resourceVersion: "31905139"
    uid: 1efef44c-9bd6-44c9-9702-8e303f5e9cc9
  spec:
…
```
and there are "pv.kubernetes.io/provisioned-by: file.csi.azure.com ", so in this situation, do I need to migration again following [this guide](https://learn.microsoft.com/en-us/azure/aks/csi-migrate-in-tree-volumes#migrate-file-share-volumes)? Does that mean I have already migrated my intree pv successfully? I realize that the only difference is in my current pv yaml it was putting secretName and secretNamespace under spec.azureFile, while in [this guide](https://learn.microsoft.com/en-us/azure/aks/csi-migrate-in-tree-volumes#migrate-file-share-volumes), it recommend to put to     :

nodeStageSecretRef:
      name: azure-secret
      namespace: default
So could you let me know if  this matters? Thanks!

**Comment by andyzhangx** [comment]
the azure file csi volume is like this, if you are already using `driver: file.csi.azure.com`, it means you are already using csi volume, that's the recommended way:
```
 csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: unique-volumeid  # make sure volumeid is unique for every identical share in the cluster
    volumeAttributes:
      resourceGroup: EXISTING_RESOURCE_GROUP_NAME  # optional, only set this when storage account is not in the same resource group as the cluster nodes
      shareName: aksshare
    nodeStageSecretRef:
      name: azure-secret
      namespace: default
```

**Comment by xiaoping8385** [comment]
I doubt I could save that step, since I found the description of my intree pv (after migration and after recreation) has turned into 
```
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{"pv.kubernetes.io/provisioned-by":"file.csi.azure.com"},"name":"cacs-devd-data-pv-csi"},"spec":{"accessModes":["ReadWriteMany"],"capacity":{"storage":"1Mi"},"csi":{"driver":"file.csi.azure.com","nodeStageSecretRef":{"name":"azure-storage-account-c360nprdcusappdata01-secret","namespace":"cacs-devd"},"readOnly":false,"volumeAttributes":{"shareName":"cacs-devd-data"},"volumeHandle":"c360nprdcusappdata01#cacs-devd#cacs-devd"},"mountOptions":["dir_mode=0777","file_mode=0777","uid=0","gid=0","mfsymlinks","cache=strict","nosharesock","nobrl"],"persistentVolumeReclaimPolicy":"Retain","storageClassName":"azurefile-csi"}}
      pv.kubernetes.io/bound-by-controller: "yes"
      pv.kubernetes.io/provisioned-by: file.csi.azure.com
    creationTimestamp: "2023-04-13T16:15:06Z"
    finalizers:
    - kubernetes.io/pv-protection
    name: cacs-devd-data-pv-csi
    resourceVersion: "31905139"
    uid: 1efef44c-9bd6-44c9-9702-8e303f5e9cc9
  spec:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 1Mi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: cacs-data-pv-csi-claim
      namespace: cacs-devd
      resourceVersion: "31905137"
      uid: 411e6e70-d0b3-4962-8d0b-40bd0ba6d284
    csi:
      driver: file.csi.azure.com
      nodeStageSecretRef:
        name: azure-storage-account-c360nprdcusappdata01-secret
        namespace: cacs-devd
      volumeAttributes:
        shareName: cacs-devd-data
      volumeHandle: c360nprdcusappdata01#cacs-devd#cacs-devd
    mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - nosharesock
    - nobrl
    persistentVolumeReclaimPolicy: Retain
    storageClassName: azurefile-csi
    volumeMode: Filesystem
  status:
    phase: Bound

```
which almost the same as you suggested, looks like azurefile csi driver has aleady translate the intree volume parameters into the right format of out tree volumes. 
Can you confirm that, Thanks!

**Comment by xiaoping8385** [comment]
@andyzhangx  Thanks for the information, that really helps. Btw, we have exported the logs for the not mount error which mentioned by the first comment, you may take a look and let us know if anything is wrong, thanks! 
[csi-azurefile-node-5sr5v-log.txt](https://github.com/kubernetes-sigs/azurefile-csi-driver/files/11258569/csi-azurefile-node-5sr5v-log.txt)
[csi-azurefile-node-ddbfn-log.txt](https://github.com/kubernetes-sigs/azurefile-csi-driver/files/11258570/csi-azurefile-node-ddbfn-log.txt)
[csi-azurefile-node-p5rxr-log.txt](https://github.com/kubernetes-sigs/azurefile-csi-driver/files/11258571/csi-azurefile-node-p5rxr-log.txt)
