### ISSUE TITLE
Still using one certain storageaccount when selectRandomMatchingAccount set to true.

### ISSUE THREAD

**Issue by duanwei33** [kubernetes-sigs/azurefile-csi-driver#1308]
**What happened**:
1. I had several storage accounts in my resource group which satisfy the sku: Standard_LRS and same location westus
2. I created sc with the following parameters:
```
parameters:
  skuName: Standard_LRS
  selectRandomMatchingAccount: "true"
```
3. I created 5 pvc with this storageclass but all of them using the same storageaccount:imageregistrywduan0pzvfq, see drivers log below:
```
I0630 06:57:50.402635       1 azure_storageaccount.go:227] randomly pick one matching account, index: 0
I0630 06:57:50.402642       1 azure_storageaccount.go:231] found a matching account imageregistrywduan0pzvfq type Standard_LRS location westus
I0630 06:57:50.551064       1 azure_storageaccount.go:227] randomly pick one matching account, index: 0
I0630 06:57:50.551072       1 azure_storageaccount.go:231] found a matching account imageregistrywduan0pzvfq type Standard_LRS location westus
I0630 06:57:50.686691       1 azure_storageaccount.go:227] randomly pick one matching account, index: 0
I0630 06:57:50.686703       1 azure_storageaccount.go:231] found a matching account imageregistrywduan0pzvfq type Standard_LRS location westus
I0630 06:57:50.822402       1 azure_storageaccount.go:227] randomly pick one matching account, index: 0
I0630 06:57:50.822410       1 azure_storageaccount.go:231] found a matching account imageregistrywduan0pzvfq type Standard_LRS location westus
I0630 06:57:50.980125       1 azure_storageaccount.go:227] randomly pick one matching account, index: 0
I0630 06:57:50.980151       1 azure_storageaccount.go:231] found a matching account imageregistrywduan0pzvfq type Standard_LRS location westus
```
Here I'm not sure if this message `randomly pick one matching account, index: 0` telling that there is only one matching account or it just picked one with index:0: 
- if it is the former, not sure what is the exact condition to match.
- if it is the latter, could you help take a look why it always choose the same storage account?

Thanks in advance!

**What you expected to happen**:
The parameter selectRandomMatchingAccount works as expected.
  
**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:

- CSI Driver version: 1.28.0
- Kubernetes version (use `kubectl version`): 1.27
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
thanks for the check, this issue would be fixed by following two PRs:

https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1309
https://github.com/kubernetes-sigs/cloud-provider-azure/pull/4203

**Comment by andyzhangx** [comment]
@duanwei33 FYI, we are considering revert this PR(https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1309) since without account search cache, there could be storage account api throttling issue when there are large number of azure file creation in parallel. So we still want to use account search which makes this RandomMatchingAccount feature not evenly distributed, and as long as user create many file shares, the file share num would be relatively distributed accross multiple storage accounts in the end, that's a limitation of this RandomMatchingAccount feature.

**Comment by duanwei33** [comment]
@andyzhangx Thanks for the info, acked. BTW, could we add some notes in doc in such case?

**Comment by andyzhangx** [comment]
> @andyzhangx Thanks for the info, acked. BTW, could we add some notes in doc in such case?

@duanwei33 notes added in the PR: https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1426
