### ISSUE TITLE
Question: Use of `subscriptionID` and `resourceGroup` Attributes

### ISSUE THREAD

**Issue by shurick81** [kubernetes-sigs/azurefile-csi-driver#1315]
Hi, for our AKS we use storage accounts in the same subscription and also other storage accounts that belong to other subscriptions within the same Azure tenant. Previously we used in-tree volumes and we never specified the `subscriptionID` nor `resourceGroup` attributes. We also tried to not specify these attributes using the new azurefile-csi-driver and the volumes were mounted smoothly. Do we really need to specify these attributes or is it only necessary for some particular use cases that our system does not need? Thank you in advance!

**Comment by andyzhangx** [comment]
@shurick81 if you already provide the storage account name and key directly, then those two fields are not necessary; those two fields are necessary when account key is not provided by end user, and the driver would use azure api to get storage account key by resourceGroup and storageAccount name.

**Comment by shurick81** [comment]
Thanks @andyzhangx, would it be right to guess that automatic access requires granting permissions to AKS managed identity?

**Comment by andyzhangx** [comment]
> Thanks @andyzhangx! Would it be right to guess that automatic access requires granting permissions to AKS managed identity?

@shurick81 yes, that's correct, the aks managed identity only has access to node resource group by default.
