### ISSUE TITLE
Restore from SMB file share snapshot feature

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azurefile-csi-driver#136]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

Currently azure file don't have a restore from snapshot SDK, need to implement that when it's available.
als see ref: https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/issues/13#issuecomment-528861659

https://docs.microsoft.com/en-us/azure/backup/restore-afs
https://docs.microsoft.com/en-us/azure/backup/restore-azure-file-share-rest-api

**Describe alternatives you've considered**

**Additional context**

**Comment by ialidzhikov** [comment]
@andyzhangx, does it make sense to put `lifecycle/frozen` on this issue?

**Comment by andyzhangx** [comment]
looks like there is still no snapshot restore API: https://docs.microsoft.com/en-us/rest/api/storageservices/snapshot-share

cc @RenaShahMSFT any progress on azure file snapshot API v2?

**Comment by akankshakumari393** [comment]
Do we know when can we have the support for restore feature?

**Comment by aslafy-z** [comment]
@andyzhangx any news please?

**Comment by olsenme** [comment]
@aslafy-z , @akankshakumari393 could I please know a little more about your use case and why you need this capability?

**Comment by Satsank** [comment]
I apologize if this isn't allowed here. For those looking at alternatives to take Azure Files Snapshot and Restore, the team at CloudCasa.io added native support for it recently. Snapshots are taken using CSI driver, but the Restores are done using native AzureFiles Integration(must provide adequate permissions through an ARM template). It's a work around available through CloudCasa until the CSI driver natively supports this functionality. Hope this helps! https://cloudcasa.io/blog/automating-azure-files-restore-in-aks/

**Comment by andyzhangx** [comment]
> I apologize if this isn't allowed here. For those looking at alternatives to take Azure Files Snapshot and Restore, the team at CloudCasa.io added native support for it recently. Snapshots are taken using CSI driver, but the Restores are done using native AzureFiles Integration(must provide adequate permissions through an ARM template). It's a work around available through CloudCasa until the CSI driver natively supports this functionality. Hope this helps! https://cloudcasa.io/blog/automating-azure-files-restore-in-aks/

@Satsank thanks for the sharing. Do you have more details about `Restores are done using native AzureFiles Integration(must provide adequate permissions through an ARM template)`? is it copy file one by one under one file share? Thanks.

**Comment by 0x113** [comment]
Hi @andyzhangx, I'm the developer behind automated Azure Files restore and I'll be more than happy to answer the questions.

Firstly, there's no need to provide any permissions with an ARM template for Azure Files restore. It's recommended for backing up and restoring AKS clusters infrastructure, but for just Azure Files, it's not mandatory.
As you may know, Azure files create a Kubernetes secret in the namespace of PVC in the following format: `azure-storage-account-<storage-account-name>-secret`. Our Azure Files mover looks for the right Secret, and it retrieves the credentials from there.

When it comes to the restore, CloudCasa uses the native Azure SDK to copy the files. Once CloudCasa finds the right snapshot for the PVC, it iterates through the files and copies them one by one to the destination file share. In the case of directories, it recreates the directory and then copies all the files.
I hope this helps!
