### ISSUE TITLE
volume cloning feature

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azurefile-csi-driver#137]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

Reference: https://kubernetes-csi.github.io/docs/volume-cloning.html

Need to check whether azure file supports create an azure file from existing azure file(cloning)
azure disk PR for reference:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/196

**Describe alternatives you've considered**

**Additional context**

**Comment by ZeroMagic** [comment]
Related doc: https://docs.microsoft.com/en-us/azure/storage/files/storage-files-planning#migration
