### ISSUE TITLE
add mountOptions e2e test

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azurefile-csi-driver#138]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

including 
 - positive tests
 - negative tests (with wrong mountOptions provided, it should fail) (done)
https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/deploy/example/storageclass-azurefile-csi-mountoptions.yaml

negative tests are done:
https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/f0a7d581749fd29fcb4340adceb2a63bebc929b3/test/e2e/dynamic_provisioning_test.go#L268-L296

**Describe alternatives you've considered**

**Additional context**

**Comment by bcho** [comment]
I am working on this issue cc @andyzhangx 

/assign @bcho
