### ISSUE TITLE
Azure file driver test cases summary

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azurefile-csi-driver#139]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

## unit tests 
tests to add: 

note:
since azure disk csi driver and in-tree driver use the same azure cloud provider lib, unit tests could be applied to both csi and in-tree drivers.

## e2e tests
Currently there are no e2e tests on in-tree azure disk & file drivers, we could leverage existing csi e2e tests and enable those e2e tests, run against on both csi driver and in-tree driver.

current test cases:
 - should create a volume on demand
 - should create a volume on demand and mount it as readOnly in a pod
 - should create multiple PV objects, bind to PVCs and attach all to different pods on the same node
 - should create a deployment object, write and read to it, delete the pod and write and read to it again
 - should delete PV with reclaimPolicy
 - should retain PV with reclaimPolicy

more cases to add:
  - [add more e2e test cases](https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/140)
  - [add mountOptions e2e test ](https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/138)

## Performance tests

**Describe alternatives you've considered**

**Additional context**

**Comment by kushthedude** [comment]
@andyzhangx I think this issue has not been addressed.
