### ISSUE TITLE
Volume provisioning fails with "InvalidHeaderValue" when using "smb" protocol and no skuName

### ISSUE THREAD

**Issue by RomanBednar** [kubernetes-sigs/azurefile-csi-driver#1390]
**What happened**:

Using StorageClass with `protocol: smb` parameter and no `skuName` parameter fails to provision volumes with misleading message: `The value for one of the HTTP headers is not in the correct format`

Also tested with `Standard_LRS` storage account type and StorageClass with `skuName: Standard_LRS` - this works fine so I assume samba is supported with standard account and does not require premium.

**What you expected to happen**:

The driver should either detect storage account type via cloud provider or provide a more helpful message.

**How to reproduce it**:

1. Create premium storage account:
```
az storage account show --name premiumacct | jq '.sku'
{
  "name": "Premium_LRS",
  "tier": "Premium"
}
```

2. Create Samba premium StorageClass (without skuName parameter):
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: "2023-08-17T11:26:30Z"
  name: azurefile-premium
  resourceVersion: "51708"
  uid: 873edb60-b9cb-44c8-b32a-dff871f8079e
parameters:
  protocol: smb
  storageAccount: premiumacct
provisioner: file.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

3. Attempt to create PVC:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: file.csi.azure.com
    volume.kubernetes.io/storage-provisioner: file.csi.azure.com
  creationTimestamp: "2023-08-17T11:45:45Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: mypvc
  namespace: default
  resourceVersion: "57633"
  uid: d4ff26d0-0dac-4782-8abe-bb294090208c
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: azurefile-premium
  volumeMode: Filesystem
status:
  phase: Pending
```

4. Check PVC events for errors, type is not set (`type()`):
```
  Normal   Provisioning          15s (x5 over 31s)  file.csi.azure.com_rbednar-mycluster-01-qlr8j-master-2_8962c26e-4d7e-4425-b954-28f2bdcaee00  External provisioner is provisioning volume for claim "default/mypvc"
  Warning  ProvisioningFailed    15s                file.csi.azure.com_rbednar-mycluster-01-qlr8j-master-2_8962c26e-4d7e-4425-b954-28f2bdcaee00  failed to provision volume with StorageClass "azurefile-premium": rpc error: code = Internal desc = failed to create file share(pvc-d4ff26d0-0dac-4782-8abe-bb294090208c) on account(premiumacct) type() subsID() rg(rbednar-mycluster-01-qlr8j-rg) location() size(2), error: storage.FileSharesClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidHeaderValue" Message="The value for one of the HTTP headers is not in the correct format.\nRequestId:616414e9-801a-007d-3400-d1aad2000000\nTime:2023-08-17T11:46:01.6830388Z"
  Normal   ExternalProvisioning  6s (x3 over 31s)   persistentvolume-controller                                                                  waiting for a volume to be created, either by external provisioner "file.csi.azure.com" or manually created by system administrator
```

5. Create StorageClass with `Premium_LRS`
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: "2023-08-17T11:55:01Z"
  name: azurefile-premium-sku
  resourceVersion: "60469"
  uid: 88d67eb5-54d9-4cbd-84ba-aa334892f23b
parameters:
  protocol: smb
  skuname: Premium_LRS
  storageAccount: premiumacct
provisioner: file.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

6. Create PVC with this new StorageClass:
```
$ oc get pvc/mypvc -o json | jq '.spec.storageClassName , .metadata.name'
"azurefile-premium-sku"
"mypvc"
```

7. Verify PV created successfully
```
$ oc get pv/pvc-5f6331c1-2694-4ff4-baa9-a0755ad450c7 -o json | jq '.spec.claimRef.name'
"mypvc"
```

**Anything else we need to know?**:

1. Testing with `Premium_LRS` storage account while having StorageClass with `skuName: Standard_LRS` to create mismatch results in the same error:

` Warning  ProvisioningFailed    4s                file.csi.azure.com_rbednar-mycluster-01-qlr8j-master-2_8962c26e-4d7e-4425-b954-28f2bdcaee00  failed to provision volume with StorageClass "azurefile-mismatch": rpc error: code = Internal desc = failed to create file share(pvc-1669cbb0-7aae-4eee-9dee-55cf6cccbcae) on account(premiumacct) type(Standard_LRS) subsID() rg(rbednar-mycluster-01-qlr8j-rg) location() size(2), error: storage.FileSharesClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidHeaderValue" Message="The value for one of the HTTP headers is not in the correct format.\nRequestId:9e602865-301a-00b3-2e0c-d17b5c000000\nTime:2023-08-17T13:13:38.1743028Z"`

2. Documentation says the parameter [defaults](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/6ad4199f5754761f663e9ce3ca5d786ee610e1d0/docs/driver-parameters.md?plain=1#L25) to `Standard_LRS` but the driver does not seem apply this for samba, looking at the request while having no `skuName`/`storageAccountType` parameter in StorageClass the message is missing the type: `failed to create file share(xxx) on account(xxx) type()...`

**Environment**:

- CSI Driver version: v1.28.0
- Kubernetes version (use `kubectl version`):  v1.27.3+4aaeaec (OpenShift 4.14.0-ec.4)
- OS (e.g. from /etc/os-release): RHEL 8.6 (Ootpa)
- Kernel (e.g. `uname -a`): 5.14.0-284.23.1.el9_2.x86_64
- Install tools: openshift-install
- Others: N/A

**Comment by andyzhangx** [comment]
that's because you are creating a 2GB premium file share, while the minimum premium file share is 100GB.

**Comment by RomanBednar** [comment]
Does not seem to be the case, I can create 2GB volume with premium just fine:

```$ oc get sc/azurefile-premium-sku -o yaml
oallowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: "2023-08-22T11:57:17Z"
  name: azurefile-premium-sku
  resourceVersion: "82846"
  uid: 78044e36-6fe6-4bcd-b7bd-ef28354b53ec
parameters:
  protocol: smb
  skuname: Premium_LRS
  storageAccount: rbednartestprem
provisioner: file.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

```
$ oc get pvc
NAME    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS            AGE
mypvc   Bound    pvc-6259070e-f032-47ba-b995-b4c7f68a8aed   2Gi        RWX            azurefile-premium-sku   27s
```

```
$ az storage account show --name rbednartestprem | jq '.sku'
{
  "name": "Premium_LRS",
  "tier": "Premium"
}
```

**Comment by andyzhangx** [comment]
that's because you have `skuname: Premium_LRS` in storage class, and the driver would set minimum size of premium file share:

https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/ed21b21aaa2406a3ad978ac6f66bb887e8707019/pkg/azurefile/controllerserver.go#L358-L362

**Comment by RomanBednar** [comment]
I see, so making skuname required for smb does not make sense. The only good solution would be to get storage account type from cloud provider so it's more robust and users don't have to set this parameter in `StorageClass` manually, I guess. Although I'm not sure about the possible pitfalls with this approach.

Would you consider such change or is the current behavior intended and we should close this?

This was reported by our QE team initially and I think their main concern is the inconsistency between smb and nfs. Since nfs [defaults](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/ed21b21aaa2406a3ad978ac6f66bb887e8707019/pkg/azurefile/controllerserver.go#L325-L327) to premium it works fine without skuname being set explicitly, but fails when just the protocol is changed to `smb`.

Different point of view, not considering nfs: standard storage account does not require skuname for `smb` and can provision any size (smaller and larger than 100G), but when users switch to premium, they start getting errors with sizes <100G if they don't set skuname.

**Comment by andyzhangx** [comment]
this issue only happens when storageAccount is provided by user, and if we get storage account type every time when every file share is created, that would make one extra storage account get api call

**Comment by RomanBednar** [comment]
Would something like [this](https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1391/files#diff-216451d6e14fadab29db3b17c4ee452298c7aab9e65e0ba18df801075f956397R315-R324) make sense?
