### ISSUE TITLE
What is the cadence of removing deprecated versions

### ISSUE THREAD

**Issue by adriananeci** [kubernetes-sigs/azurefile-csi-driver#1402]
We are currently using the `azurefile-csi-driver` helm chart as a dependency of another chart and I've noticed the versions removal is pretty aggressive. Every 2-3 weeks our helm chart is failing syncing because the `azurefile-csi-driver` version is no longer available upstream. This is a bit annoying since other things are depending on this component and a manual intervention is almost always required.

What is the cadence of removing deprecated versions? Can the versions removal be extended to a longer period? Is versions removal just a way to keep the version folders small/ repo cleaner or is there another reason?

**Comment by andyzhangx** [comment]
@adriananeci what version you are using now? mainly we want to keep the latest patch version with CVE and other bug fixed. That would also keep the version folders small and cleaner.

**Comment by adriananeci** [comment]
Now we're using `v1.26.5`, but recently we had to move very frequently from one version to another because the old versions were just disappearing.
We had to go from `1.26.1` ->  `1.26.3` in mid July, then from `1.26.3` ->  `1.26.4` in the beginning of August, and now from `1.26.4` ->  `1.26.5`

I'm looking for a long term support for all patch versions that are part of the actively maintained minor/major versions

**Comment by andyzhangx** [comment]
ok, I will try keeping the patch version as long as possible, and from security perspective, it's better using latest patch version since it fixes a few CVEs
