### ISSUE TITLE
POSIX compliant and secure mounting option

### ISSUE THREAD

**Issue by KenADev** [kubernetes-sigs/azurefile-csi-driver#1417]
**Is your feature request related to a problem?/Why is this needed**
Currently, the only option to mount an Azure Fileshare in a POSIX compliant way is to use the NFS protocol. However, the security implications when NFS is used are devastating:
Insecure connections have to be enabled on the Storage Account, there is no encryption in transit, and no authentication (access is only limited by network restrictions).
The only other POSIX compliant storage option is to use Azure Disks, which however have the disadvantage that every AKS node can only mount a kind of small number of disks (e.g., 16 disks.) and only ReadWriteOnce is supported.

**Describe the solution you'd like in detail**
A POSIX compliant mounting option with proper authentication, encryption in transit, and support for ReadWriteMany. 

**Describe alternatives you've considered**
Azure Disks, but have ReadWriteOnly and disks/node limitations.

**Additional context**
We require this feature for complying with PCI DSS.

**Comment by andyzhangx** [comment]
azure file team is already working on encryption in transit support on azure file nfs service, stay tuned.
