### ISSUE TITLE
Add windows build test

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azurefile-csi-driver#142]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like in detail**

Add windows build test
```
make azurefile-windows
```

could refer to https://github.com/kubernetes/test-infra/blob/bc272268da64b4aa08a26fa998963645f7746c7b/config/jobs/kubernetes-sigs/azurefile-csi-driver/azurefile-csi-driver-config.yaml#L28-L46

**Describe alternatives you've considered**

**Additional context**

**Comment by levimm** [comment]
/assign
https://github.com/kubernetes/test-infra/pull/15687

**Comment by andyzhangx** [comment]
it's done
