### ISSUE TITLE
permission denied while moving files

### ISSUE THREAD

**Issue by fragolinux** [kubernetes-sigs/azurefile-csi-driver#1428]
**What happened**:
we have an azure k8s cluster v1.25.5, using azurefile csi driver to access an azure file share, in latest days we are seeing errors in some pods mounting that share, about permission denied while moving files in a directory. Nothing changed in deployed resources in last month, except we see that now azure csi file driver updated itself to version 1.24.4 (it's managed by aks, not by us).

The pod uses a modified openvidu image, the line causing issue is the [126 ](https://github.com/EcoMind/openvidu/blob/feature/2.24.0-EM/openvidu-server/docker/openvidu-recording/scripts/composed.sh#L126)of this file:

`  jq -c -r ".hasAudio=$HAS_AUDIO | .hasVideo=$HAS_VIDEO | .duration=$DURATION | .size=$SIZE | .status=\"$STATUS\"" "/recordings/$VIDEO_ID/.recording.$VIDEO_ID" > $TMP && mv $TMP /recordings/$VIDEO_ID/.recording.$VIDEO_ID`

/recordings is the folder mounting the file share, and commands run under user "kurento" (id 102) which has sudo permissions, and same command run as root works... the directory containing the files, and the files themselves, are all chmoded 777 by the same script, so they should just work, and they worked fine till july ending...

why we think it's a csi driver related issue? As said, nothing changed in deployed resources in last month except driver version self update, and in describe of the pod we found this error this morning, while it was starting up:

`Warning   FailedMount              pod/XXX   MountVolume.SetUp failed for volume "YYY" : kubernetes.io/csi: mounter.SetUpAt failed to get CSI client: driver name file.csi.azure.com not found in the list of registered CSI drivers
`

tried to modify that file, adding sudo before mv, but same issues, permission denied while mv, and the worst part is that before the mv, both source ($TMP) and destination files existed, but after the mv command fails, the destination file disappears from the share...

**What you expected to happen**:
successfully move/rename files

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:

- CSI Driver version: 1.24.4
- Kubernetes version (use `kubectl version`): 1.25.5
- OS (e.g. from /etc/os-release): stock aks provided images
- Kernel (e.g. `uname -a`): same as above

`image: [mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi:v1.24.4](http://mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi:v1.24.4)      image: [mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi:v1.24.4](http://mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi:v1.24.4)      imageID: [mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi@sha256:7c943abf4675728b0b528f675ad9a5d850a1ebc45ac87f3039df031c56b8a34e](http://mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi@sha256:7c943abf4675728b0b528f675ad9a5d850a1ebc45ac87f3039df031c56b8a34e)`

**Comment by andyzhangx** [comment]
@fragolinux the csi driver version upgrade won't affect existing smb mount, could you try the same move operation on the pod on the other node?

**Comment by fragolinux** [comment]
tried and results are the same... as the cluster uses aks spot nodes, which are shut down after work time, and recreated next morning, today we have the same issues and all the nodes where the workloads are running are just 6 hours old

**Comment by andyzhangx** [comment]
> tried and results are the same... as the cluster uses aks spot nodes, which are shut down in the evening after work time, and recreated next morning, today we have the same issues and all the nodes where the workloads are running are just 6 hours old

@fragolinux if so, are you able to ssh to the node, and try get the smb mount on the node by "mount | grep cifs", and try moving files on the node directly to check whether it works. This could be a cifs driver or azure file service issue.

**Comment by fragolinux** [comment]
but if i'm inside the pod and run the command as root it works... and collegue a few moments later tried to run pod in debug mode, introducing a bit of delay by doing so, and this was enough for the script to move the file successfully... none of these was needed till late july... i'll try to go on the node...

**Comment by fragolinux** [comment]
is there a way to pin a specific driver version, while deploying on AKS? I can't find one...

**Comment by andyzhangx** [comment]
> is there a way to pin a specific driver version, while deploying on AKS? I can't find one...

@fragolinux No, the driver version is managed by AKS, unless you uninstall the managed csi driver, and install the open source one.
