### ISSUE TITLE
Why do we have ControllerPublishVolume capability?

### ISSUE THREAD

**Issue by gnufied** [kubernetes-sigs/azurefile-csi-driver#1467]
I noticed that we are disabling volume attachment via:

https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/deploy/v1.29.0/csi-azurefile-driver.yaml#L10

So why do we have the `ControllerPublishVolume` capability in the CSI driver?

**Comment by andyzhangx** [comment]
good catch, this PR would remove this cap: https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1468, thanks.
