### ISSUE TITLE
NSF protocol (service endpoints) partially working when the vnet contains multiple subnets

### ISSUE THREAD

**Issue by djsly** [kubernetes-sigs/azurefile-csi-driver#1606]
**What happened**:
We have multiple subnets under our VNET which are consumed by different nodepools in AKS. There I only a single Subnet that is configured/allowed in the vnetRules when the Storage account is created by the CSI driver and the networking is configured. 
**What you expected to happen**:
We should be able to configure the CSI driver with multiple Subnet since the default Azureconfig doesn't contain all subnets by default. 
**How to reproduce it**:
create an AKS with multiple subnet, have those subnet used by different nodepools and try mounting the AzureFile from pods on those different subnets.
**Anything else we need to know?**:

**Environment**:

- CSI Driver version: version from the latest 1.27.3 AKS version ( image: mcr.microsoft.com/oss/kubernetes-csi/azuredisk-csi:v1.28.4)
- Kubernetes version (use `kubectl version`): 1.27.3
- OS (e.g. from /etc/os-release): AzureLinux
- Kernel (e.g. `uname -a`): 5.15.133.1-1.cm2
- Install tools: AKS
- Others: containerd://1.6.22

**Comment by andyzhangx** [comment]
we already have a `subnetName` parameter, so if user inputs `subnetName: subnet1, subnet2`, the csi driver would try to update service endpoint with those subnets one by one (not implemented yet), does it work in your scenario? @djsly 

https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/5ce7fba12d84194ed59a94515bad62f606b8c435/pkg/azurefile/controllerserver.go#L344-L349

**Comment by djsly** [comment]
Yes. That makes sense. I recall try to put an array for the subnet name but
only a string was supported.

Sorry, miss that comment before.
