### ISSUE TITLE
[CSI Parameter] Parameter readOnly not working

### ISSUE THREAD

**Issue by ParaTrix** [kubernetes-sigs/azurefile-csi-driver#1607]
**What happened**:
The parameter readOnly in spec.csi configuration is not working, set to true won't stop pod from writing data.

**What you expected to happen**:
When set to true, pods are unable to perform write on the Azure file share.

**How to reproduce it**:
Just create a static PV with spec.csi.readOnly = true.

**Anything else we need to know?**:
From example configuration: [pv-azurefile-csi.yaml](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/deploy/example/pv-azurefile-csi.yaml):

There is a readOnly parameters under spec.csi, so I tested it at my ARO cluster, but I noticed that when I set it to true, exec into the pod, and I still able to modify or delete files in the fileshare.

I also noticed that in [driver-parameters](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/driver-parameters.md), there is no such option.

So may I ask the status of this parameter, does it work or not yet implemented?

**Environment**:

Sorry, Azure RedHat Openshift cluster doesn't contains any pods on kube-system namespace.

I also tried to list all pods in all namespaces to find any string like mcr or azurefile, but no result returned.

- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
could you set `Pod.Spec.Volumes.PersistentVolumeClaim.ReadOnly` as true or set `-o ro` in mount options in pv, csi.readOnly flag is not passed correctly in csi driver, that's a known issue in CSI driver, you could find details as below:
https://github.com/kubernetes/kubernetes/issues/69843
https://github.com/kubernetes/kubernetes/issues/70505

I will remove this field to avoid confusion, thanks for reporting.

**Comment by ParaTrix** [comment]
Thanks for the timely response, Pod.Spec.Volumes.PersistentVolumeClaim.ReadOnly set to true do work in ARO cluster.

Have a nice day.
