### ISSUE TITLE
Feature Request: Support for Reducing Azure File Share Size via PVC in Kubernetes

### ISSUE THREAD

**Issue by galz-cyera** [kubernetes-sigs/azurefile-csi-driver#1633]
Feature request: Allow reducing PVC size from through K8S

While it is possible to reduce a Fileshare size through Azure portal (once every 24 hours), it isn't possible to do it from the PVC directly. This limits automation and operational flexibility.

**Comment by andyzhangx** [comment]
volume size reducing is not supported by k8s
