### ISSUE TITLE
New 1.30 patch release with commits after 2/22/2024

### ISSUE THREAD

**Issue by jwstein3400** [kubernetes-sigs/azurefile-csi-driver#1799]
**What happened**:
There have been multiple changes merged to the 1.30 branch without a release:
https://github.com/kubernetes-sigs/azurefile-csi-driver/commits/release-1.30/

**What you expected to happen**:
I am requesting a new release 1.30+ that teams can align with.

**How to reproduce it**:
Review releases: https://github.com/kubernetes-sigs/azurefile-csi-driver/releases
Note there are no 1.30 patch releases, while 1.29.4 was released on 3/27

**Anything else we need to know?**:
We are specifically waiting on a stable release with the following issue resolved: https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/1777

**Environment**:
N/A

**Comment by andyzhangx** [comment]
https://github.com/kubernetes-sigs/azurefile-csi-driver/releases/tag/v1.30.1 is published, @jwstein3400 are you using aks managed driver or open source installed driver?
