### ISSUE TITLE
[feature] Support snapshot & restore 

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azurefile-csi-driver#18]
https://kubernetes-csi.github.io/docs/snapshot-restore-feature.html#snapshot--restore-feature

**Comment by andyzhangx** [comment]
needs to figure out where is the go sdk of azure file snapshot first: https://github.com/Azure/azure-sdk-for-go/issues/4093

**Comment by andyzhangx** [comment]
here is the azure file snapshot example:
https://github.com/Azure/azure-storage-file-go/blob/d93e19c84c2af7958331fb3ec8fd04eb0d76a25e/azfile/zt_examples_test.go#L521-L602

**Comment by tall49er** [comment]
Can I working on it?

**Comment by andyzhangx** [comment]
@tall49er sure, thanks.

**Comment by ZeroMagic** [comment]
Wait for Storage Team to release the new feature, clone snapshot (create new file share from snapshot).
