### ISSUE TITLE
PVC fails to be provision

### ISSUE THREAD

**Issue by ran-haim** [kubernetes-sigs/azurefile-csi-driver#1845]
I have installed the driver on an on-prem k8s, and I cannot get pvc to be provisioned in azure file share.
I also see that after it fails the controllers go into crash loop.

There is no real information in the controllers to why this happens, only this:
type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "azurefile-sc": rpc error: code = Unavailable desc = error reading from server: EOF
I0417 16:06:25.006917       1 controller.go:1359] provision "default/azure-test-pvc" class "azurefile-sc": started
E0417 16:06:25.007127       1 connection.go:142] Lost connection to unix:///csi/csi.sock.
F0417 16:06:25.007213       1 connection.go:97] Lost connection to CSI driver, exiting

any idea what's going on?

**Comment by andyzhangx** [comment]
@ran-haim what is your azure file csi driver version? and what's the azurefile controller logs?
```
kubectl logs csi-azurefile-controller-xxx -c azurefile -n kube-system > csi-azurefile-controller.log
```

there is a controller panic bug fixed in v1.30.1, refer to https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/1790#issuecomment-2033690346

**Comment by ran-haim** [comment]
What I wrote in the message is what I got from the azurefile controller - nothing else is really there.
I tested it yesterday and It rebooted the controller, and then failed on deleting the pvc (now on crashloop).

`Defaulted container "csi-provisioner" out of: csi-provisioner, csi-attacher, csi-snapshotter, csi-resizer, liveness-probe, azurefile
I0418 11:22:36.098775       1 feature_gate.go:249] feature gates: &{map[HonorPVReclaimPolicy:true]}
I0418 11:22:36.098841       1 csi-provisioner.go:154] Version: v3.5.0-0-gab68435fa
I0418 11:22:36.098846       1 csi-provisioner.go:177] Building kube configs for running in cluster...
I0418 11:22:37.100043       1 common.go:111] Probing CSI driver for readiness
I0418 11:22:37.103936       1 csi-provisioner.go:230] Detected CSI driver file.csi.azure.com
I0418 11:22:37.103957       1 csi-provisioner.go:240] Supports migration from in-tree plugin: kubernetes.io/azure-file
I0418 11:22:37.104248       1 common.go:111] Probing CSI driver for readiness
I0418 11:22:37.105577       1 csi-provisioner.go:302] CSI driver does not support PUBLISH_UNPUBLISH_VOLUME, not watching VolumeAttachments
I0418 11:22:37.105903       1 controller.go:732] Using saving PVs to API server in background
I0418 11:22:37.106114       1 leaderelection.go:245] attempting to acquire leader lease kube-system/file-csi-azure-com...
I0418 11:22:59.493956       1 leaderelection.go:255] successfully acquired lease kube-system/file-csi-azure-com
I0418 11:22:59.494112       1 leader_election.go:178] became leader, starting
I0418 11:22:59.594732       1 volume_store.go:97] Starting save volume queue
I0418 11:22:59.594767       1 clone_controller.go:66] Starting CloningProtection controller
I0418 11:22:59.594770       1 controller.go:811] Starting provisioner controller file.csi.azure.com_ip-10-0-134-127.us-west-1.compute.internal_5b70a87f-10e6-4401-abed-a3a226a60
ff7!
I0418 11:22:59.594800       1 clone_controller.go:82] Started CloningProtection controller
I0418 11:22:59.695559       1 controller.go:1502] delete "pvc-0d78203d-820d-4d11-9004-ea037ead8aae": started
I0418 11:22:59.695727       1 controller.go:860] Started provisioner controller file.csi.azure.com_ip-10-0-134-127.us-west-1.compute.internal_5b70a87f-10e6-4401-abed-a3a226a60f
f7!
E0418 11:22:59.835675       1 controller.go:1512] delete "pvc-0d78203d-820d-4d11-9004-ea037ead8aae": volume deletion failed: rpc error: code = Unavailable desc = error reading
from server: EOF
W0418 11:22:59.835736       1 controller.go:989] Retrying syncing volume "pvc-0d78203d-820d-4d11-9004-ea037ead8aae", failure 0
E0418 11:22:59.835760       1 controller.go:1007] error syncing volume "pvc-0d78203d-820d-4d11-9004-ea037ead8aae": rpc error: code = Unavailable desc = error reading from serve
r: EOF
I0418 11:22:59.835875       1 event.go:298] Event(v1.ObjectReference{Kind:"PersistentVolume", Namespace:"", Name:"pvc-0d78203d-820d-4d11-9004-ea037ead8aae", UID:"e86564db-a41e-
4ffe-a385-616768130841", APIVersion:"v1", ResourceVersion:"19037802", FieldPath:""}): type: 'Warning' reason: 'VolumeFailedDelete' rpc error: code = Unavailable desc = error re
ading from server: EOF
I0418 11:23:00.836522       1 controller.go:1502] delete "pvc-0d78203d-820d-4d11-9004-ea037ead8aae": started
E0418 11:23:00.842583       1 connection.go:142] Lost connection to unix:///csi/csi.sock.
F0418 11:23:00.842648       1 connection.go:97] Lost connection to CSI driver, exiting
`

We are using the helm chart to install, according to the CSIDriver the version is v1.29.2.
Is there a way to use the helm chart with the latest version?

**Comment by andyzhangx** [comment]
```
helm uninstall azurefile-csi-driver -n kube-system
helm install azurefile-csi-driver azurefile-csi-driver/azurefile-csi-driver --namespace kube-system --version v1.30.1
```

**Comment by ran-haim** [comment]
same problem with new version.

> 
I0418 12:21:00.594198       1 controller.go:860] Started provisioner controller file.csi.azure.com_ip-10-0-151-154.us-west-1.compute.internal_72739e4c-9833-4220-bbd2-33280b6c5018!
I0418 12:21:00.594400       1 event.go:364] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"azure-test-pvc", UID:"64264413-76fa-4918-9af4-6279bf53857f", APIVersion:"v1", ResourceVersion:"19647118", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/azure-test-pvc"
I0418 12:21:00.600863       1 controller.go:1082] Temporary error received, adding PVC 64264413-76fa-4918-9af4-6279bf53857f to claims in progress
W0418 12:21:00.600876       1 controller.go:934] Retrying syncing claim "64264413-76fa-4918-9af4-6279bf53857f", failure 0
E0418 12:21:00.600892       1 controller.go:957] error syncing claim "64264413-76fa-4918-9af4-6279bf53857f": failed to provision volume with StorageClass "azurefile-sc": rpc error: code = Unavailable desc = error reading from server: EOF
I0418 12:21:00.600902       1 event.go:364] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"azure-test-pvc", UID:"64264413-76fa-4918-9af4-6279bf53857f", APIVersion:"v1", ResourceVersion:"19647118", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "azurefile-sc": rpc error: code = Unavailable desc = error reading from server: EOF
I0418 12:21:01.601603       1 controller.go:1366] provision "default/azure-test-pvc" class "azurefile-sc": started
E0418 12:21:01.601798       1 connection.go:193] Lost connection to unix:///csi/csi.sock.
I0418 12:21:01.601802       1 event.go:364] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"azure-test-pvc", UID:"64264413-76fa-4918-9af4-6279bf53857f", APIVersion:"v1", ResourceVersion:"19647118", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/azure-test-pvc"
F0418 12:21:01.601875       1 connection.go:114] Lost connection to CSI driver, exiting

**Comment by andyzhangx** [comment]
since you are not providing the cloud config, you need to set secret in storage class, you could refer to https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/1790#issue-2218660386

```
I0418 12:40:13.175749       1 azure.go:95] could not read cloud config from secret kube-system/azure-storage-secret
I0418 12:40:13.175757       1 azure.go:105] use default AZURE_CREDENTIAL_FILE env var: /etc/kubernetes/azure.json
I0418 12:40:13.175773       1 azure.go:111] InitializeCloudFromSecret: failed to get cloud config from file /etc/kubernetes/azure.json: open /etc/kubernetes/azure.json: no such file or directory
I0418 12:40:13.175786       1 azure.go:117] no cloud config provided, error: open /etc/kubernetes/azure.json: no such file or directory, driver will run without cloud config
I0418 12:40:13.175794       1 azure.go:152] starting controller server...
I0418 12:40:13.175801       1 azurefile.go:370] cloud: , location: , rg: , VnetName: , VnetResourceGroup: , SubnetName: 
```

**Comment by ran-haim** [comment]
ah, I tried to set it in the helm install, somehow it did not add it.
I will try to add it manually.

**Comment by ran-haim** [comment]
Works!
thanks for the help.
