### ISSUE TITLE
Move helm chart version to strict SemVer 2

### ISSUE THREAD

**Issue by ed-boykin** [kubernetes-sigs/azurefile-csi-driver#1888]
Helm v3 requires strict SemVer2 versioning. In particular OCI repositories will not support the current versioning scheme used by the azurefile-csi-driver.  ex: v1.29.5.

Security requirements may require cached pull-through on charts, or for 3rd party charts to be stored in private OCI repos.

Would like to see the Chart.yaml version field use proper SemVer2  by removing the 'v', ex: version: 1.29.5  instead of version: v.1.29.5

[Helm Chart versioning](https://helm.sh/docs/topics/charts/#charts-and-versioning)
[SemVer2](https://semver.org/spec/v2.0.0.html)

**Comment by andyzhangx** [comment]
@ed-boykin 
there are `appVersion` and `version` fields, which one should not have `v`? and for compatibility concern, we won't do that for existing v1.30 or earlier versions, we could fix is in v1.31 or later version.

https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/a628f71cb509359659e5fe9ff93e97658e78292a/charts/v1.30.2/azurefile-csi-driver/Chart.yaml#L2-L5

**Comment by ed-boykin** [comment]
The 'version' field is the important one. This is used by helm tools especially when packaging the chart and when pushing to an OCI repo.
[Charts and Versioning](https://helm.sh/docs/topics/charts/#charts-and-versioning)

Understood about not fixing prior versions.

**Comment by andyzhangx** [comment]
we could only fix this from 1.31

**Comment by ed-boykin** [comment]
That would be ok and VERY helpful. Thanks.
