### ISSUE TITLE
Older helm chart versions disappeared

### ISSUE THREAD

**Issue by mbrt** [kubernetes-sigs/azurefile-csi-driver#2005]
**What happened**:

After https://github.com/kubernetes-sigs/azurefile-csi-driver/commit/9f686e31986d1f5b72cdb2a63b5017ae642081a2, a bunch of older versions of the chart disappeared.

After that commit, it seems to be no longer possible to install those versions.

Note how, installing e.g. `v.1.1.0` is not even possible by using a different branch or tag in the repo, because the index always [points back to the master branch](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/88e38d2897476a39959df049edea738791c645fb/charts/index.yaml#L29).

**What you expected to happen**:

I would expect that all stable versions after `v1.0.0` keep being available indefinitely, or there's a documented way to get them.

**How to reproduce it**:

The easiest for me is to create a `kustomization.yaml` file in a local directory:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: azurefile-csi-driver
  version: v1.1.0
  repo: https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/v1.1.0/charts
  releaseName: azurefile-csi-driver
  namespace: kube-system
```

And run:

```
$ kustomize build --enable-helm .
Error: Error: chart "azurefile-csi-driver" version "v1.1.0" not found in https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts repository
: unable to run: 'helm pull --untar --untardir /home/mbrt/tmp/azurefile-csi-driver-v1.1.0 --repo https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts azurefile-csi-driver --version v1.1.0' with env=[HELM_CONFIG_HOME=/tmp/kustomize-helm-158786256/helm HELM_CACHE_HOME=/tmp/kustomize-helm-158786256/helm/.cache HELM_DATA_HOME=/tmp/kustomize-helm-158786256/helm/.data] (is 'helm' installed?): exit status 1
```

Note that this fail whatever URL you pull the chart from (as mentioned above).

**Possible fix?**

An easy fix would probably be to add back the releases to `index.yaml` and have them just point to older tags in git, where the files were not deleted. This would keep the number of directory in `master` low without breaking old releases.

**Comment by andyzhangx** [comment]
@mbrt are you still using `v1.0.0` version? that version was released more than 3 years ago, it's out of support already.
You could add following repo address if you still want to use that version:
```
helm repo add azurefile-csi-driver https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/release-1.0/charts
```

**Comment by mbrt** [comment]
@andyzhangx uhm, unfortunately we have a production cluster stuck at Kubernetes 1.16 and `azure-csi-driver` `v1.1.0` is the latest version supporting it. Until we finish migrating off of that thing, we still need the version.

Although your suggestion works for `v1.0.0`, it doesn't for `v1.1.0`. Yes, we can vendor the chart inside out GitOps repo, but I thought that stable releases disappearing looked somewhat unnecessary, so I decided to report here.

**Comment by mbrt** [comment]
Why was this closed as completed? Am I missing the fix somewhere, or was it decided not to address this?

**Comment by andyzhangx** [comment]
> Why was this closed as completed? Am I missing the fix somewhere, or was it decided not to address this?

check this comment: https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/2005#issuecomment-2244521061
