### ISSUE TITLE
switch to use lease-file for vhd disk file locking

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azurefile-csi-driver#201]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

We use azure file metadata to do the vhd disk locking, while it won't work if one disk is used by multiple clusters(csi drivers):
https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/6ef7cf783a86fd2652876ea45f9b0e6fba1cf019/pkg/azurefile/controllerserver.go#L313-L314

By using azure file lease API: https://docs.microsoft.com/en-us/rest/api/storageservices/lease-file, we could have an azure platform locking way, it's more safe.

**Describe alternatives you've considered**

**Additional context**

**Comment by dr0pdb** [comment]
This can be tackled once the Azure SDK supports the lease file. https://github.com/Azure/azure-storage-file-go/issues/50
