### ISSUE TITLE
add unit test for getAccountInfo func

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azurefile-csi-driver#204]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

need to write fakeDriver first
https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/6ef7cf783a86fd2652876ea45f9b0e6fba1cf019/pkg/azurefile/azurefile.go#L367-L393

**Describe alternatives you've considered**

**Additional context**

**Comment by andyzhangx** [comment]
@animeshk08 could you also take a look at this? thanks.

**Comment by animeshk08** [comment]
The UT already exists here: https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/f0a7d581749fd29fcb4340adceb2a63bebc929b3/pkg/azurefile/azurefile_test.go#L512

The method is nearly covered completely.

The line coverage can be found here: https://coveralls.io/builds/32107068/source?filename=pkg/azurefile/azurefile.go#L396

I think the issue can be closed.

**Comment by andyzhangx** [comment]
thanks
