### ISSUE TITLE
Snapshot restore does not work if the storage account has limited access.

### ISSUE THREAD

**Issue by 0x113** [kubernetes-sigs/azurefile-csi-driver#2121]
**What happened**:
I wanted to restore data from a CSI snapshot but the PVC was stuck in "Pending" state due to the following error:
```
failed to provision volume with StorageClass "az-test-sc": rpc error: code = Unknown desc = exec error: exit status 1, output: INFO: Scanning...
INFO: Login with identity succeeded.
INFO: Authenticating to destination using Azure AD
INFO: Authenticating to source using Azure AD
INFO: Failed to create one or more destination container(s). Your transfers may still succeed if the container already exists.
INFO: Any empty folders will be processed, because source and destination both support folders
INFO: Failed to scan directory/file . Logging errors in scanning logs.

failed to perform copy command due to error: cannot start job due to error: GET https://<fileshare>.file.core.usgovcloudapi.net/<share-pvc-name>
--------------------------------------------------------------------------------
RESPONSE 403: 403 This request is not authorized to perform this operation.
ERROR CODE: AuthorizationFailure
--------------------------------------------------------------------------------
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.
RequestId:xxxxxx
Time:xxxxxxx</Message></Error>
--------------------------------------------------------------------------------
.
```

The storage account mentioned above does not allow public access - it only allows access from the AKS VNet.

**What you expected to happen**:
Since the AKS VNet was added to the list of networks that can access the storage account, I expected the restore to work.

**How to reproduce it**:
1. Create an AKS cluster with a user-assigned managed identity that has enough permissions to access the storage account.
2. Create a storage account and enable access to it only from AKS VNet (Go to "Networking" -> "Firewalls and virtual networks" -> "Enabled from selected virtual networks and IP addresses" and select cluster VNet and subnet)
3. Create a StorageClass on the cluster that points to the previously created storage account:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: az-test-sc
mountOptions:
- nouser_xattr
- mfsymlinks
- nosharesock
- actimeo=30
parameters:
  resourceGroup: <storage-account-resource-group>
  skuName: Standard_LRS
  storageAccount: <storage-account-name>
  server: <storage-account-name>.file.core.usgovcloudapi.net
provisioner: file.csi.azure.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
```
4. Deploy a simple app that is set to use the previously created StorageClass.
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: az-test-pvc
  namespace: az-test-ns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: az-test-sc
  resources:
    requests:
      storage: 25Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: az-test-pod
  namespace: az-test-ns
spec:
  containers:
  - image: mcr.microsoft.com/oss/nginx/nginx:1.15.5-alpine
    name: test-pod
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
    volumeMounts:
      - name: azure
        mountPath: /mnt/data
  volumes:
  - name: azure
    persistentVolumeClaim:
      claimName: az-test-pvc
```
5. Take a snapshot of the app using Velero or manually by creating a VolumeSnapshot resource.
6. Try to restore the app from the taken snapshot.
7. The PVC will be stuck in "Pending" with the error mentioned above.

**Anything else we need to know?**:
To be sure it's not a problem with the AKS setup, I provisioned a VM and assigned the same identity the cluster was set up with. Also, I added the VM's VNet to the list of VNets that can access the storage account. Finally, I installed `azcopy` command on the VM and verified that it could access the file share.

**Environment**:

- CSI Driver version: 1.30.5
- Kubernetes version (use `kubectl version`): 1.29.5
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools: The app was deployed on AKS cluster on Azure Government cloud
- Others:

**Comment by andyzhangx** [comment]
that's an expected limitation since the azcopy runs on aks control plane which is not in the allowed list of VNets in the storage account

**Comment by 0x113** [comment]
Thank you for getting back to me @andyzhangx.

Is there any workaround for this issue or the only fix is to enable public access to the storage account?

**Comment by andyzhangx** [comment]
the only workaround is to enable public access to the storage account

**Comment by 0x113** [comment]
Understood. Thank you for the help! I'm going to close this issue since it is an expected limitation.

**Comment by andyzhangx** [comment]
Try “useDataPlaneAPI: oauth” in storage class parameter, it should work in managed azure file csi driver on AKS now
