### ISSUE TITLE
documented about option volumeHandle 

### ISSUE THREAD

**Issue by eliyahu77** [kubernetes-sigs/azurefile-csi-driver#221]
Hi * , 

I wil glad to know what this option volumeHandle define and what can be the values of this parameters.
https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/deploy/example/pv-azurefile-csi.yaml

**Comment by andyzhangx** [comment]
it's arbitrary volumeid, make sure it's a uniqe id

**Comment by eliyahu77** [comment]
this is need to be just a random ID  or the volume ID from azure ?

**Comment by andyzhangx** [comment]
just a random ID is ok
