### ISSUE TITLE
Mount to sub  folder 

### ISSUE THREAD

**Issue by eliyahu77** [kubernetes-sigs/azurefile-csi-driver#222]
Hi * ,
there is any option to mount to sub folder on the share ? 
Option#2: Static Provisioning(use an existing azure file share)  without azure-secret 
https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/deploy/example/e2e_usage.md

BR Eliyahu

**Comment by andyzhangx** [comment]
no, you need to mount file share first
