### ISSUE TITLE
helm install fails customresource definition already exists

### ISSUE THREAD

**Issue by eliyahu77** [kubernetes-sigs/azurefile-csi-driver#223]
Hi * ,
helm version: v2.14.3

this issues related  to  azurefile-csi-driver and azuredisk-csi-driver , when install the following charts 
azuredisk v0.6.0
azurefile v.0.5.0 
 I get the following  error "helm install fails customresource definition already exists"

**Comment by andyzhangx** [comment]
Hi @eliyahu77 
thanks for reporting issue, to unblock your deployment, could you try following command to install azure disk & azure file drivers? thanks.

```
curl -skSL https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/deploy/install-driver-standalone.sh | bash -s v0.6.0 --

curl -skSL https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/deploy/install-driver-standalone.sh | bash -s v0.5.0 --
```

**Comment by andyzhangx** [comment]
/assign @ZeroMagic 
could you take a look at helm install issue, thanks.

**Comment by eliyahu77** [comment]
HI  , 
there is option to add argument to the following  script install-driver-standalone.sh   to accept ,  "cloud_provider_file_path" , because development  of k8s  are create this file under name cloud_config , or other name

**Comment by andyzhangx** [comment]
> HI ,
> there is option to add argument to the following script install-driver-standalone.sh to accept , "cloud_provider_file_path" , because development of k8s are create this file under name cloud_config , or other name

@eliyahu77 do you mean user could self-define `/etc/kubernetes/azure.json` path? Currently it's hard coded as following path:
https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/55189ff589b512d44445be98b1eb8e680542191a/deploy/csi-azurefile-controller.yaml#L166-L168

**Comment by andyzhangx** [comment]
This PR(https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/225) is to support Setting Azure cloud provider from Kubernetes secrets:
Since `v1.15.0`, Azure cloud provider supports reading the cloud config from Kubernetes secrets. The secret is a serialized version of `azure.json` file with key cloud-config. The secret should be put in `kube-system` namespace and its name should be `azure-cloud-provider`.

**Comment by ZeroMagic** [comment]
> I get the following error "helm install fails customresource definition already exists"

@eliyahu77  Could you give the k8s version and the full failed log? So that we can know the concrete failed CRDs.

**Comment by eliyahu77** [comment]
k8s:  v1.15.3
helm version: v2.14.3
azuredisk v0.6.0
azurefile v.0.5.0

**Comment by eliyahu77** [comment]
first i was install the azure disk , and after install azure file charts,

only whem I remove the follwing  files from "azurefile crd-csi-node-info.yaml,crd-csi-driver-registry.yaml"  chart   , only the the helm cli was update

**Comment by ZeroMagic** [comment]
Got it. We do have some common crds in both of azuredisk and azurefile. I will fix it.
Thanks @eliyahu77

**Comment by andyzhangx** [comment]
> Got it. We do have some common crds in both of azuredisk and azurefile. I will fix it.
> Thanks @eliyahu77

@ZeroMagic how do we fix it? renaming common crds?

**Comment by ZeroMagic** [comment]
This is the solution(https://github.com/kubernetes-sigs/blobfuse-csi-driver/issues/167#issuecomment-643874746). 
The PR(https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/308) has solved it.
