### ISSUE TITLE
use azure file with no secret and use mount to subfolder inside the share

### ISSUE THREAD

**Issue by eliyahu77** [kubernetes-sigs/azurefile-csi-driver#224]
HI *, 
Option 2 
https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/deploy/example/e2e_usage.md

the share is configure under SC , so if  I want to use same storagecalss but different  path  ,  there is option to use PVC with PV and then  it will be able to use the sub folder 

if it possible it will be good  to have example for it .

**Comment by andyzhangx** [comment]
I think you want to use this subPath: https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath
This is a common k8s volume path usage, not related to azure file driver.
