### ISSUE TITLE
`subscriptionID` in device params applies to NFS as well?

### ISSUE THREAD

**Issue by kewalaka** [kubernetes-sigs/azurefile-csi-driver#2282]
Minor documentation query - the `subscriptionID` parameter listed [on the device parameters](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/driver-parameters.md) says it is only for the SMB protocol.

I'm using it with NFS to specify a storage account in a different sub, it seems to be fine.

Just checking this scenario is supported?

**Comment by andyzhangx** [comment]
yes, it also applies for nfs
