### ISSUE TITLE
AKS: Azure file csi & private endpoints

### ISSUE THREAD

**Issue by aelmanaa** [kubernetes-sigs/azurefile-csi-driver#238]
**What happened**:

Hello,

I'm using version 0.5 of azure file csi. So far it has been working well for us. 
However, we've noticed that the IP was resolving to a public one so we decided to use private endpoint. which means that  <storageaccountname>.privatelink.file.core.windows.net is resolving to a  private IP.
When mouting a PVC to a pod, we start getting 403 errors:
" error: could not get storage key for storage account xxx: could not get storage key"

**What you expected to happen**:
mounting azure file using private endpoints should continue to work as before
**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: 0.5
- Kubernetes version (use `kubectl version`): v1.16.7

**Comment by andyzhangx** [comment]
we don't support `accountname.privatelink.file.core.windows.net` now, currently we have hard coded the address as `accountname.file.core.windows.net`

**Comment by aelmanaa** [comment]
> we don't support `accountname.privatelink.file.core.windows.net` now, currently we have hard coded the address as `accountname.file.core.windows.net`
wow ,, that's bit tricky for us :( 
 In fact, we were planning to use  network policies within kubernetes. Hence, to control egress traffic of pods, we need to specify the destination IP.  without private endpoints, we are limited to public IPs (which can change).
Any idea when it would be supported?

Moreover , I don't understand why it's a problem if you hardcode accountname.file.core.windows.net. In fact,  when I perform nslookup of "accountname.file.core.windows.net" , I get as result "accountname.privatelink.file.core.windows.net" as CNAME then a privateIP as address. This is managed by DNS resolution, so you don't need to manage it on your side

**Comment by andyzhangx** [comment]
the error  `could not get storage key for storage account xxx: could not get storage key"`, actually happens in creating file share, could you make sure your storage account is in the node resource group? You could also specify resource group by:
https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/deploy/example/storageclass-azurefile-existing-share.yaml

**Comment by aelmanaa** [comment]
@andyzhangx  It was working fine before I created the private endpoint. 
there is also something really streange,  I see the following in the error log:

>  client 'abfa830c-dba3-4a07-bdca-eeed37d664a1' with object id 'abfa830c-dba3-4a07-bdca-eeed37d664a1' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/listKeys/action' over scope

I don't know where this value  "abfa830c-dba3-4a07-bdca-eeed37d664a1" comes from.  we don't have any Service principal or user with this object id in our system

**Comment by aelmanaa** [comment]
hello @andyzhangx 

ok I've progressed in my investigations. We have 2 clusters running on 2 different k8s versions:

- Cluster1 runs with k8s 1.15.10

- Cluster2 runs with k8s 1.16.7

it works pefectly fine with Cluster1 but fails with Cluster2. I will upgrade the version of Cluster1 to 1.16.7 and see if it breaks or not. will keep you posted

**Comment by andyzhangx** [comment]
could you paste the full pod description with error events, thanks

**Comment by aelmanaa** [comment]
I'm creating the volumes dynamically . Hence the error occurs during the creation of the PVC (pvc remains in pending state)

-  storage class
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefilecsistd
parameters:
  location: <my-location>
  resourceGroup: <my-rg>
  skuName: Standard_ZRS
  storageAccount: <my-storageaccount>
provisioner: file.csi.azure.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
```

- PVC
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aemdynpvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Ti
  storageClassName: azurefilecsistd
  volumeMode: Filesystem
```

- kubectl describe pvc aemdynpvc

```
  Normal  ExternalProvisioning  3m26s (x4363 over 18h)  persistentvolume-controller                                                                waiting for a volume to be created, either by external provisioner "file.csi.azure.com" or manually created by system administrator
```

- kubectl get events

```
3s          Warning   ProvisioningFailed     persistentvolumeclaim/aemdynpvc   failed to provision volume with StorageClass "azurefilecsistd": rpc error: code = Unknown desc = failed to create file share(pvc-xxx) on account(xxx) type(Standard_ZRS) rg(xxx) location(xxx) size(5120), error: could not get storage key for storage account xxx: could not get storage key for storage account xxx: Retriable: true, RetryAfter: 0001-01-01 00:00:00 +0000 UTC, HTTPStatusCode: 403, RawError: storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'xxx' with object id 'xxx' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/listKeys/action' over scope '/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Storage/storageAccounts/xxx' or the scope is invalid. If access was recently granted, please refresh your credentials."
```

As I told you , it was working fine before and the SP of the cluster has access to the storage account. 

As I said, I tested the resolution from a pod and also from a node  (nslookup <storageaccount>.file.core.windows.net) and I get the right result. Hence, the problem is not coming from here. 
However, noticed something when I execute "sudo" commands on the node

```
root@aks-agentpool-xxx-xxx:/# sudo echo hello
sudo: unable to resolve host aks-agentpool-xxx-xxx
hello
```

**Comment by andyzhangx** [comment]
the error is obvious:
```
"AuthorizationFailed" Message="The client 'xxx' with object id 'xxx' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/listKeys/action' over scope '/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Storage/storageAccounts/xxx' or the scope is invalid. If access was recently granted, please refresh your credentials."
```

you may check whether your sp has expired or have permission to that storage account:
```
aadClientId=$(az aks show --resource-group <RG_NAME> --name <CLUSTER_NAME> --query "servicePrincipalProfile.clientId" --output tsv)
echo $aadClientId
az ad sp credential list --id $aadClientId
```

**Comment by aelmanaa** [comment]
@andyzhangx indeed sorry, error in the permission for one of the clusters.  thanks a lot for your help
