### ISSUE TITLE
[feature] make azure file csi driver run on Windows

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azurefile-csi-driver#24]
**Is your feature request related to a problem? Please describe.**

Currently CSI driver is linux based, cannot run on Windows. The main difficulty is design difference between Linux and Windows, all devices are files in Linux while it's not true for Windows. 
Here is a issue link in moby talking about this issue: https://github.com/moby/moby/issues/38479

**Describe the solution you'd like in detail**

We could make the attacher and azure file csi driver running as a standalone process on Windows, that could work. (could refer to kube-proxy and kubelet implementation in aks-engine: https://github.com/Azure/aks-engine/blob/master/parts/k8s/kuberneteswindowssetup.ps1#L129-L130)
For the provision part, it could still run on Linux(on master node?). That would make it a little easier to implement.

**Describe alternatives you've considered**

**Additional context**

**Comment by andyzhangx** [comment]
you could refer to https://github.com/kubernetes/enhancements/blob/master/keps/sig-windows/20190714-windows-csi-support.md
cc @kkmsft

**Comment by andyzhangx** [comment]
@kkmsft any update on azure file driver? I see you already did some work on azure disk, could you port those code to azure file driver as well, thanks.

**Comment by kkmsft** [comment]
Yes, PR will be out this week. Testing the changes.

**Comment by andyzhangx** [comment]
awesome

**Comment by andyzhangx** [comment]
already supported: https://github.com/kubernetes-sigs/azurefile-csi-driver/tree/master/deploy/example/windows
