### ISSUE TITLE
improve unit test coverage

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azurefile-csi-driver#258]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

improve UT coverage including
 - controllerserver
 - nodeserver
 - identityserver
 - version

https://coveralls.io/github/kubernetes-sigs/azurefile-csi-driver?branch=master

![image](https://user-images.githubusercontent.com/4178417/80330808-d1785a00-8878-11ea-9529-eb7eb03cfa10.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by Dhiraj240** [comment]
@andyzhangx Would like to work on it.

**Comment by andyzhangx** [comment]
> @andyzhangx Would like to work on it.

thanks, this is a big part, just update which part your are working on this issue when you have any progress.

**Comment by andyzhangx** [comment]
and there are some easy parts, e.g. `version.go`, this issue is to improve the test code coverage, current ratio is awful, thanks.

**Comment by andyzhangx** [comment]
cc @kushthedude to take a look, thanks

**Comment by animeshk08** [comment]
Working on unit tests for https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/pkg/azurefile/nodeserver.go. Mentioning to avoid redundant work :)

**Comment by animeshk08** [comment]
Update:

Uncovered files:
* `server.go`: Need to find a way to mock grpc requests.

Improve coverage:
 * `controllerserver.go`: Need to create mock file client.
* `nodeserver.go`: Mock mount/unmount operation to remove the need of running the command with root privileges.

**Comment by andyzhangx** [comment]
thanks @animeshk08 really impressive work!  
Can you improve code coverage on `csi-common`? thanks

Current code coverage:
![image](https://user-images.githubusercontent.com/4178417/84569999-f68b4280-adbc-11ea-95b3-6ab5252027ca.png)

cc @Sakuralbj

**Comment by animeshk08** [comment]
Sure!
`controllerserver-default.go` has unimplemented methods which I have omitted. Hence the low coverage for that file.
I will start work on `server.go`.

**Comment by andyzhangx** [comment]
it's now 80%!
![image](https://user-images.githubusercontent.com/4178417/86123809-b93ce980-bb0c-11ea-8785-572be73f353a.png)

**Comment by andyzhangx** [comment]
it's now 85%, thanks for the contribution! @animeshk08  now close this issue.
![image](https://user-images.githubusercontent.com/4178417/87791790-72255700-c875-11ea-99cb-9b35298d2563.png)
