### ISSUE TITLE
azurefile Function not implemented message calling python function os.listxattr

### ISSUE THREAD

**Issue by scivm** [kubernetes-sigs/azurefile-csi-driver#259]
**What happened**:

Function not implemented error message when calling a python function os.listxattr

**What you expected to happen**:

function call to succeed as it does with original azurefile driver

**How to reproduce it**:

Use azurefile csi driver and calling python function gives error:

```
jovyan@jupyter-shamberger-20michael-20-28ext-29:~$ python3
Python 3.7.4 (default, Aug 13 2019, 20:35:49)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.listxattr("./Untitled1.ipynb")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 38] Function not implemented: './Untitled1.ipynb'
```

**Anything else we need to know?**:

```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-standard
mountOptions:
- dir_mode=0750
- file_mode=0700
- uid=1000
- gid=100
- mfsymlinks
- nobrl
- cache=none
parameters:
  skuName: Standard_LRS
provisioner: file.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

**Environment**:
- CSI Driver version:  master
- Kubernetes version (use `kubectl version`): 1.15.10
- OS (e.g. from /etc/os-release): ubuntu
- Kernel (e.g. `uname -a`):  Linux jupyter-shamberger-20michael-20-28ext-29 4.15.0-1071-azure #76-Ubuntu SMP Wed Feb 12 03:02:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
hi, do you know what's underlying `./Untitled1.ipynb`, it's more like azure file issue itself since azure file is not 100% unix file system compatible.

**Comment by andyzhangx** [comment]
azure file does not support support xattrs now.

**Comment by TiloGit** [comment]
@andyzhangx  any plans to support [xattrs](https://en.wikipedia.org/wiki/Extended_file_attributes)?
