### ISSUE TITLE
release folders missing script rbac-csi-azurefile-node.yaml

### ISSUE THREAD

**Issue by scivm** [kubernetes-sigs/azurefile-csi-driver#260]
**What happened**:

The deploy folder has various releases such as v0.5.0 and v0.6.0.   Inside those folders, the script rbac-csi-azurefile-node.yaml is missing.  This causes installation to give errors.

**What you expected to happen**:

Installation to succeed

**How to reproduce it**:

install-driver.sh v0.6.0

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: and released version
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
thanks for reporting, as a workaround, you could try this:
```
curl -skSL https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/v0.6.0/deploy/install-driver.sh | bash -s v0.6.0 --
```

**Comment by andyzhangx** [comment]
fixed by commit: https://github.com/kubernetes-sigs/azurefile-csi-driver/commit/33d43f3c8afefdeaeceef178aabf8923afdec519
