### ISSUE TITLE
Undefined DriverName in version.go

### ISSUE THREAD

**Issue by Dhiraj240** [kubernetes-sigs/azurefile-csi-driver#266]
I just found that there was undefined variable issue in ```version.go``` file.
Hence added it new PR

**Comment by Dhiraj240** [comment]
@andyzhangx https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/265 solves the issue. Please merge

**Comment by animeshk08** [comment]
This issue can be closed now. @Dhiraj240 @andyzhangx
