### ISSUE TITLE
pvc pending with error "sa azurefile cannot create secrets"

### ISSUE THREAD

**Issue by aelmanaa** [kubernetes-sigs/azurefile-csi-driver#271]
Hello,

I see a weird warning  in a pending pvc:

couldn't create secret secrets is forbidden: User "system:serviceaccount:kube-system:csi-azurefile-controller-sa" cannot create resource "secrets" in API group "" in the namespace "default"

why is azure file csi trying to create a secret?  we are using v0.5 and I don't see a permission to create a secret in the installation files

kubectl auth can-i create secrets --as system:serviceaccount:kube-system:csi-azurefile-controller-sa 
-> no

**Comment by aelmanaa** [comment]
Everything has been working fine for several weeks. The only thing that I did yesterday,:  I installed the following plugins:

https://github.com/Azure/secrets-store-csi-driver-provider-azure
https://github.com/kubernetes-sigs/secrets-store-csi-driver
https://github.com/Azure/aad-pod-identity

**Comment by andyzhangx** [comment]
@aelmanaa I think you should go to `install-csi-driver-v0.5.0.md` to install `v0.5.0`, the latest stable version is `v0.6.0`, so you should follow this page to install `v0.6.0`: https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/v0.6.0/docs/install-csi-driver-v0.6.0.md

**Comment by aelmanaa** [comment]
@andyzhangx you shouldn’t close the issue .
I was using v0.5 and it suddenly broke ! As I told you the problem is coming from the fact that you don t specify a proper version here:  mcr.microsoft.com/k8s/csi/azurefile-csi:latest

Why don’t you specify « azurefile-csi:0.5 » 
instead of « azurefile-csi:latest » ? Because of this , if there is a scale up for instance , my node pulls the latest version (which might not be inline with the installed version).

**Comment by aelmanaa** [comment]
@andyzhangx just changed the title of the issue. To summarize there are 2 issues here :

*no proper version when pulling azure file container

*azurefile latest is not backward compatible with v0.5 —> as I told you , I was using v0.5 in AKS cluster with rbac enabled and it suddenly broke !

**Comment by andyzhangx** [comment]
pls follow this guide to install `v0.5.0` driver:
https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/install-csi-driver-v0.5.0.md

It's already using `v0.5.0` version, there could be a doc issue in the before, I think it's already fixed.

**Comment by aelmanaa** [comment]
@andyzhangx  No the doc has not been fixed. please check those files. they are still with "mcr.microsoft.com/k8s/csi/azurefile-csi:latest"

https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/v0.5.0/deploy/csi-azurefile-controller.yaml

same with: https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/v0.6.0/deploy/csi-azurefile-controller.yaml

so the error is still there

**Comment by andyzhangx** [comment]
@aelmanaa pls follow this guide to install v0.6.0 driver:
https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/install-csi-driver-v0.6.0.md

or install v0.5.0 driver from https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/install-csi-driver-v0.5.0.md

I realized this is really going to make people confused, will change the tags, thanks.

**Comment by aelmanaa** [comment]
@andyzhangx ok thanks! indeed, now everything is versioned!  Yesterday everything was breaking so I just installed the "master" version to unlock the situation. do you think I can safelly instlall v0.6.0 without impacting current mounts ?

**Comment by andyzhangx** [comment]
> @andyzhangx ok thanks! indeed, now everything is versioned! Yesterday everything was breaking so I just installed the "master" version to unlock the situation. do you think I can safelly instlall v0.6.0 without impacting current mounts ?

Yes, it should be safe
