### ISSUE TITLE
Support for tags parameter

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azurefile-csi-driver#281]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like in detail**

Add `tags` parameter in azure file creation, and the tags would be created in newly created storage account, could refer to https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/236

May do it in in-tree driver first.

/assign @ZeroMagic 

**Describe alternatives you've considered**

**Additional context**

**Comment by ZeroMagic** [comment]
Do we also need to set `tags` parameter into `Metadata` of file share? https://github.com/Azure/azure-sdk-for-go/blob/v43.0.0/services/storage/mgmt/2019-06-01/storage/models.go#L2669

**Comment by andyzhangx** [comment]
I think we can set tags in both azure storage account and file share if possible
