### ISSUE TITLE
Enable Cloud Provider Config file as a parameter during driver installation, needed for ARO support

### ISSUE THREAD

**Issue by ezYakaEagle442** [kubernetes-sigs/azurefile-csi-driver#282]
**What happened**:

The [CSI driver doc](https://github.com/kubernetes-sigs/azurefile-csi-driver#prerequisite) states : 
The driver initialization depends on a Cloud provider config file, usually it's /etc/kubernetes/azure.json on all kubernetes nodes deployed by AKS or aks-engine, here is azure.json example. This driver also supports read cloud config from kuberenetes secret.
 
Indeed this is what I see in the [HELM Chart](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/charts/v0.6.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml#L90) 

**What you expected to happen**:

The driver should be installed correctly in Azure RedHat OpenShift 4.3

**How to reproduce it**:

I am testing the CSI driver for Azure disk on ARO 4.3, snippet in progress available at [https://github.com/ezYakaEagle442/aro-pub-storage/blob/master/setup-store-CSI-driver-azure-file.md](https://github.com/ezYakaEagle442/aro-pub-storage/blob/master/setup-store-CSI-driver-azure-file.md) 

```sh
oc get secrets -n kube-system
oc describe secret azure-cloud-provider -n kube-system
azure_cnf_secret=$(oc get secret azure-cloud-provider -n kube-system -o jsonpath="{.data.cloud-config}" | base64 --decode)
echo "Azure Cloud Provider config secret " $azure_cnf_secret
```

Then the logs show the azurefile container fails to read the file /etc/kubernetes/azure.json :

DRIVER INFORMATION:
-------------------
Build Date: "2020-04-22T12:48:54Z"
Compiler: gc
Driver Name: file.csi.azure.com
Driver Version: v0.6.0
Git Commit: 9e45d9a7187c2b3426d66a31615a775bc1d4cc1c
Go Version: go1.13.4
Platform: linux/amd64

Streaming logs below:
I0519 06:52:50.958568       1 azure.go:31] **AZURE_CREDENTIAL_FILE env var set as /etc/kubernetes/azure.json**
E0519 06:52:50.958586       1 azure.go:39] **Failed to load config from file: /etc/kubernetes/azure.json**
F0519 06:52:50.958594       1 azurefile.go:111] **failed to get Azure Cloud Provider**

```sh
for pod in $(oc get pods -l app=csi-azurefile-node -n kube-system -o custom-columns=:metadata.name)
do
	oc describe pod $pod -n kube-system | grep -i "Error"
    oc logs $pod -c liveness-probe -n kube-system #| grep -i "Error"
    oc logs $pod -c node-driver-registrar # | grep -i "Error"
    oc logs $pod -c azurefile -n kube-system # | grep -i "Error"
done
```

**Anything else we need to know?**:

The above [DS runs with SA ](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/charts/v0.6.0/azurefile-csi-driver/templates/csi-azurefile-node.yaml#L18) csi-azurefile-node-sa :

I added this SCC but I still got the same error after a clean uninstall / reinstall :
 ```sh
oc adm policy add-scc-to-user privileged system:serviceaccount:kube-system:csi-azurefile-node-sa
oc describe scc privileged
 ```
 
In openshift the creds file is located in “/etc/kubernetes/**cloud.conf**”, so you would need to replace the path in the deployment for the driver from “/etc/kubernetes/azure.json” to “/etc/kubernetes/**cloud.conf**”.

[CSI driver doc states](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/read-from-secret.md) : This driver also supports reading the cloud config from Kubernetes secrets. The secret is a serialized version of **azure.json file with key cloud-config. The secret should be put in kube-system namespace and its name should be azure-cloud-provider.**

see similar issue with Azure disk Driver : [https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/398](https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/398)

**Environment**:
- CSI Driver version: v0.6.0
- Kubernetes version (use `kubectl version`): ARO 4.3 ==> openshift-clients-4.3.14-202004180552 , Server Version: 4.3.18, Kubernetes Version: v1.16.2
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by TiloGit** [comment]
@andyzhangx  Please link guide from @ezYakaEagle442  on your how to page. Very useful for ARO instances.  
https://github.com/ezYakaEagle442/aro-pub-storage/blob/master/setup-store-CSI-driver-azure-file.md

`oc create configmap azure-cred-file --from-literal=path="/etc/kubernetes/cloud.conf" -n kube-system`

**Comment by andyzhangx** [comment]
> @andyzhangx Please link guide from @ezYakaEagle442 on your how to page. Very useful for ARO instances.
> https://github.com/ezYakaEagle442/aro-pub-storage/blob/master/setup-store-CSI-driver-azure-file.md
> 
> `oc create configmap azure-cred-file --from-literal=path="/etc/kubernetes/cloud.conf" -n kube-system`

@TiloGit thanks, I already added a ARO setup link in README page: https://github.com/kubernetes-sigs/azurefile-csi-driver/commit/1a733ff42a1005f9fcdbb4d22d2641c35d2c62d0
