### ISSUE TITLE
Redundant Check

### ISSUE THREAD

**Issue by animeshk08** [kubernetes-sigs/azurefile-csi-driver#286]
**What happened**:
The check for TargetPath is redundant in the method:
https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/7b2d070b9badab1f9f63fa4b530be05444a8816d/pkg/azurefile/nodeserver.go#L41

First check: https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/7b2d070b9badab1f9f63fa4b530be05444a8816d/pkg/azurefile/nodeserver.go#L49

Second check: https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/7b2d070b9badab1f9f63fa4b530be05444a8816d/pkg/azurefile/nodeserver.go#L58

**What you expected to happen**:
The second check can be removed.

**How to reproduce it**:
NA
**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
thanks, just go ahead to remove the second check, thanks.
