### ISSUE TITLE
Explain how to enable Feature Gate in AKS

### ISSUE THREAD

**Issue by ezYakaEagle442** [kubernetes-sigs/azurefile-csi-driver#293]
**Is your feature request related to a problem?/Why is this needed**

Can not test Volume Snapshot without this documentation.

[https://github.com/kubernetes-sigs/azurefile-csi-driver/tree/master/deploy/example/snapshot](https://github.com/kubernetes-sigs/azurefile-csi-driver/tree/master/deploy/example/snapshot) states that VolumeSnapshotDataSource Feature Gate must be enabled, but how to configurer that in AKS ?

**Describe the solution you'd like in detail**

A short doc explaining how to enable VolumeSnapshotDataSource Feature Gate in AKS as it is documented in ARO : 

- [https://docs.openshift.com/container-platform/4.3/nodes/clusters/nodes-cluster-enabling-features.html](https://docs.openshift.com/container-platform/4.3/nodes/clusters/nodes-cluster-enabling-features.html)
- [https://docs.kasten.io/install/openshift/openshift.html#openshift-and-csi](https://docs.kasten.io/install/openshift/openshift.html#openshift-and-csi)

**Describe alternatives you've considered**

**Additional context**

**Comment by andyzhangx** [comment]
since Azure Disk CSI driver already uses snapshot v2.0.0 interfance, minimum supported k8s version is `1.17.0`, that feature gate is enabled by default(beta) on AKS, and I have updated the snapshot doc: https://kubernetes-csi.github.io/docs/snapshot-controller.html
