### ISSUE TITLE
Test: Improve test coverage for controlserver

### ISSUE THREAD

**Issue by animeshk08** [kubernetes-sigs/azurefile-csi-driver#305]
The test coverage of `controlserver` is 52.98%. Currently, the tests include only negative cases. To include the positive test cases a mocked client is needed as lines like: https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/645b2b95d71411d710b5cdafe88c2e3c7dcfa086/pkg/azurefile/azurefile.go#L192
are returning HTTP timeout error.

Can refer to: https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/299

Current coverage:

![azurefilecoverage](https://user-images.githubusercontent.com/32506591/84569530-eff0d100-ada4-11ea-861b-2ca12191a6b4.png)

**Comment by andyzhangx** [comment]
@animeshk08 thanks for the update.
the mock client is here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/azure/clients/fileclient/mockfileclient/interface.go#L59-L62

@ZeroMagic  is trying to update the latest cloud provider lib code from k/k, should be in PR:https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/298

**Comment by animeshk08** [comment]
Hi @andyzhangx, I had a look again at the tests for `controllerserver`. I believe the fileclient mentioned by you is not the one being used.
The mocks are needed for: https://github.com/Azure/azure-sdk-for-go/blob/master/storage/fileserviceclient.go
and https://github.com/Azure/azure-storage-file-go/blob/master/azfile/url_file.go.

Please let me know how to move forward from here.

**Comment by andyzhangx** [comment]
> Hi @andyzhangx, I had a look again at the tests for `controllerserver`. I believe the fileclient mentioned by you is not the one being used.
> The mocks are needed for: https://github.com/Azure/azure-sdk-for-go/blob/master/storage/fileserviceclient.go and https://github.com/Azure/azure-storage-file-go/blob/master/azfile/url_file.go.
> 
> Please let me know how to move forward from here.

@animeshk08 there is a working PR(https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/298) to use management API.

**Comment by ZeroMagic** [comment]
Hi @animeshk08 , the PR is completed and waiting for review. After switching to management API, the mocks in `k8s.io/legacy-cloud-providers/azure` are enough for you to use. Could refer to https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/azure/azure_storage_test.go.

Due to the SDK change, some original unit tests are invalid and have to be deprecated. Could you help to rewrite them?

**Comment by animeshk08** [comment]
Hi, @ZeroMagic Thank you for the update. This will definitely make things easier. I will update the unit tests once the PR is merged :)

**Comment by andyzhangx** [comment]
> Hi, @ZeroMagic Thank you for the update. This will definitely make things easier. I will update the unit tests once the PR is merged :)

that PR is merged
