### ISSUE TITLE
add snapshot e2e test

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azurefile-csi-driver#312]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

could refer to https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/test/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go

depends on https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/313, switch to `v2.0.1` first

**Describe alternatives you've considered**

**Additional context**

**Comment by ZeroMagic** [comment]
Has added in #349
