### ISSUE TITLE
switch snapshot feature from v1.1.0 to 2.0.1

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azurefile-csi-driver#313]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

Current snapshot feature is using `v1.1.0`, should switch to use `v2.0.1` (`v2.0.1` introduces a snapshot controller)
https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/9881ffd5e4754ea4f7a3a911b609d8fe3458414c/deploy/csi-azurefile-controller.yaml#L69

could refer to 
 - https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/6cbc2015328bf6921fc4c5e0c5a821f076d33ca5/deploy/csi-azuredisk-controller.yaml#L71
 - https://github.com/kubernetes-sigs/azuredisk-csi-driver/commit/91ea28fe710cd67f347349f4bad806d032580b53
 - https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/260

**Describe alternatives you've considered**

**Additional context**

**Comment by ZeroMagic** [comment]
Fixed in #349.
