### ISSUE TITLE
Update remaining methods in Controllerserver with management SDK

### ISSUE THREAD

**Issue by animeshk08** [kubernetes-sigs/azurefile-csi-driver#326]
**Is your feature request related to a problem?/Why is this needed**
Some of the methods were not covered in this PR: https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/298. Some examples include,
* https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/3677c80f4fd968f6fc9d0def28f41b6c13d65a9d/pkg/azurefile/controllerserver.go#L605
* https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/3677c80f4fd968f6fc9d0def28f41b6c13d65a9d/pkg/azurefile/controllerserver.go#L485
* https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/3677c80f4fd968f6fc9d0def28f41b6c13d65a9d/pkg/azurefile/controllerserver.go#L411

and others which primarily make calls to https://github.com/Azure/azure-storage-file-go/blob/master/azfile/url_file.go

These remaining methods are also needed to be updated to use management SDK.

**Describe the solution you'd like in detail**
Can refer to: https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/298
**Describe alternatives you've considered**

**Additional context**

**Comment by ZeroMagic** [comment]
Currently, the azurefile team has not provided snapshot related API in management SDK. For the management plane, there are just the six APIs(https://docs.microsoft.com/en-us/rest/api/storagerp/fileshares). The code is located at https://github.com/Azure/azure-sdk-for-go/blob/master/services/storage/mgmt/2019-06-01/storage/fileshares.go

So we only can use the data plane to control the snapshot now.
