### ISSUE TITLE
azure file csi v0.7: installation file links are broken

### ISSUE THREAD

**Issue by aelmanaa** [kubernetes-sigs/azurefile-csi-driver#330]
Hello,

not able to install azure file csi v0.7

if you try to open the follwing link: 
https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/deploy/v0.7.0/crd-csi-node-info.yaml

--> 404: Not Found

the other links work fine. for instance:

https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/deploy/v0.7.0/rbac-csi-azurefile-controller.yaml

--> OK

Remark:  you should also fix the base repo in this link https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/v0.7.0/deploy/install-driver.sh.
Please put  "https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/deploy/v0.7.0/" instead of "https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/deploy"

**Comment by andyzhangx** [comment]
could you take a look? @Sakuralbj

**Comment by andyzhangx** [comment]
@aelmanaa pls try use following command to install v0.7.0:
```
curl -skSL https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/v0.7.0/deploy/install-driver.sh | bash -s v0.7.0 --
```

detailed doc could be found here: https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/install-csi-driver-v0.7.0.md

**Comment by aelmanaa** [comment]
hello @andyzhangx  yes sorry about that, the repo in in the script is indeed the right one.
I'll wait for your investigation regarding: 
https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/deploy/v0.7.0/crd-csi-node-info.yaml

**Comment by andyzhangx** [comment]
we are going to remove `crd-csi-node-info.yaml` since it's not necessary, pls follow this guide to install v0.7.0:
https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/install-csi-driver-v0.7.0.md

**Comment by aelmanaa** [comment]
@andyzhangx 

but the script will fail here:
kubectl apply -f $repo/crd-csi-node-info.yaml

Just tried and it failed as expected

 curl -skSL https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/v0.7.0/deploy/install-driver.sh | bash -s v0.7.0 --
Installing Azure File CSI driver, version: v0.7.0 ...
error: unable to read URL "https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/deploy/v0.7.0/crd-csi-node-info.yaml", server reported 404 Not Found, status code=404

**Comment by andyzhangx** [comment]
thanks, pls try again
```
curl -skSL https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/v0.7.0/deploy/install-driver.sh | bash -s v0.7.0 --
```

should be fixed by https://github.com/kubernetes-sigs/azurefile-csi-driver/commit/9749957acad666ac6879695477a2c989648b5730

**Comment by aelmanaa** [comment]
thanks @andyzhangx
