### ISSUE TITLE
Add GET_VOLUME_STATS Capability to NodeService Capability

### ISSUE THREAD

**Issue by onesolpark** [kubernetes-sigs/azurefile-csi-driver#334]
**What happened**:
Kubelet is not exposing volume stats even though it is implemented through #306 

**What you expected to happen**:
Expose volume stats through kubelet metric

**How to reproduce it**:
Create PVC and check for metric in kubelet metric endpoint

**Anything else we need to know?**:
```csi.NodeServiceCapability_RPC_GET_VOLUME_STATS``` should be added to node service capability so kubelet can retrieve metrics.
Not really sure if this was blocked to wait for the next release.

https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/26d02c5f2f29e0237047f4c384493b9a98b7083b/pkg/azurefile/azurefile.go#L170-L172

**Environment**:
- CSI Driver version: master-branch
- Kubernetes version (use `kubectl version`): 1.17.3

**Comment by moonek** [comment]
@andyzhangx 
When will this feature be released?

**Comment by andyzhangx** [comment]
> @andyzhangx
> When will this feature be released?

It's already in master branch, would you try first? thanks.
