### ISSUE TITLE
VolumeSnapshot never reaches ReadyToUse state

### ISSUE THREAD

**Issue by michael-niemand** [kubernetes-sigs/azurefile-csi-driver#347]
**What happened**:
A VolumeSnapshot of a PVC with a StorageClass using the azurefile-csi-driver is not successful; the VolumeSnapshot stays in ReadyToUse state: <nil> forever

**What you expected to happen**:

The VolumeSnapshot is being created and goes into Ready To Use state at some point

**How to reproduce it**:

- have a basically new AKS 1.17.7 cluster
- install the VolumeSnaphsot CRDs, following the Kubernets 1.17 blog post: https://kubernetes.io/blog/2019/12/09/kubernetes-1-17-feature-cis-volume-snapshot-beta/
- install the master branch version of this azurefile-csi-driver (tried 0.7 before, too)
- create a storage class according to the example listed in the README.md
- deploy a ReadWriteMany PVC using that storage class (identical to example, only size and name changed)
- Create a VolumeSnapshot of that PVC (again, from example, only names and namespaces changed)

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: master 
- Kubernetes version (use `kubectl version`): 1.17.7 AKS / 1.18.3 kubectl
- Others:
I installed the disk driver, too (0.7 version) and was able to create a snapshot of a volume based on the disk driver

**Comment by andyzhangx** [comment]
actually it's not working, there is also a tracking issue here: https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/313
cc @ZeroMagic

**Comment by andyzhangx** [comment]
We will definitely working on this  feature to make it available again soon, just need to switch to snapshot beta interface.
