### ISSUE TITLE
Project stuck in pending

### ISSUE THREAD

**Issue by RenaShahMSFT** [kubernetes-sigs/azurefile-csi-driver#353]
[csi-azurefile-node.log](https://github.com/kubernetes-sigs/azurefile-csi-driver/files/4992733/csi-azurefile-node.log)

**What happened**:
Error when following https://github.com/kubernetes-sigs/azurefile-csi-driver/tree/master/deploy/example/nfs#how-to-use-nfs-feature

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
I think `kubectl describe pvc pvc-name` would display the error since there is already error msg in azure file controller:
```
E0721 05:50:18.584403       1 utils.go:116] GRPC error: rpc error: code = Internal desc = failed to ensure storage account: could not get storage key for storage account azfilesnfsaksdemosa: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 403, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 403, RawError: {"error":{"code":"AuthorizationFailed","message":"The client 'xxx' with object id 'xxx' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/listKeys/action' over scope '/subscriptions/xxx/resourceGroups/azfilesnfsaksdemorg/providers/Microsoft.Storage/storageAccounts/azfilesnfsaksdemosa' or the scope is invalid. If access was recently granted, please refresh your credentials."}}
```
