### ISSUE TITLE
Helm chart should allow secrets to pull Docker images

### ISSUE THREAD

**Issue by fredgate** [kubernetes-sigs/azurefile-csi-driver#371]
**Is your feature request related to a problem?/Why is this needed**
The Helm chart allow to change Docker images repository when they are not hosted on Docker hub. But it does not allow to provide a secret used to authenticate in case these repositories are private.

**Describe the solution you'd like in detail**
The chart should add a optional variable thats contains secrets used to authenticate. These secrets could then be attached to the pods to pull the images.

I can provide the pull request.

**Comment by andyzhangx** [comment]
@fredgate thanks for the offer!
