### ISSUE TITLE
multi-arch tag does not work on containerd on Windows

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azurefile-csi-driver#382]
**What happened**:
multi-arch tag does not work on containerd on Windows, if I switch to use `mcr.microsoft.com/k8s/csi/azurefile-csi:v0.9.0-windows-1809-amd64` tag it works.

```
Events:
  Type     Reason     Age                From                 Message
  ----     ------     ----               ----                 -------
  Normal   Scheduled  113s               default-scheduler    Successfully assigned kube-system/csi-azurefile-node-win-pgnck to 1094k8s001
  Normal   Pulling    111s               kubelet, 1094k8s001  Pulling image "mcr.microsoft.com/oss/kubernetes-csi/livenessprobe:v2.0.1-alpha.1-windows-1809-amd64"
  Normal   Pulled     90s                kubelet, 1094k8s001  Successfully pulled image "mcr.microsoft.com/oss/kubernetes-csi/livenessprobe:v2.0.1-alpha.1-windows-1809-amd64"
  Normal   Created    90s                kubelet, 1094k8s001  Created container liveness-probe
  Normal   Started    88s                kubelet, 1094k8s001  Started container liveness-probe
  Normal   Pulling    88s                kubelet, 1094k8s001  Pulling image "mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v1.2.1-alpha.1-windows-1809-amd64"
  Normal   Pulled     86s                kubelet, 1094k8s001  Successfully pulled image "mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v1.2.1-alpha.1-windows-1809-amd64"
  Normal   Created    86s                kubelet, 1094k8s001  Created container node-driver-registrar
  Normal   Started    84s                kubelet, 1094k8s001  Started container node-driver-registrar
  Warning  Failed     82s (x2 over 83s)  kubelet, 1094k8s001  Back-off pulling image "mcr.microsoft.com/k8s/csi/azurefile-csi:latest"
  Normal   Pulling    70s (x2 over 84s)  kubelet, 1094k8s001  Pulling image "mcr.microsoft.com/k8s/csi/azurefile-csi:latest"
  Warning  Failed     70s (x2 over 83s)  kubelet, 1094k8s001  Failed to pull image "mcr.microsoft.com/k8s/csi/azurefile-csi:latest": rpc error: code = NotFound desc = failed to pull and unpack image "mcr.microsoft.com/k8s/csi/azurefile-csi:latest": no match for platform in manifest: not found
```

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig windows

**Comment by andyzhangx** [comment]
```
# docker manifest inspect mcr.microsoft.com/k8s/csi/azurefile-csi:latest
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1165,
         "digest": "sha256:e7ca2f4f546d91d5ace7654709f0150174378f43b113836f6ab2e8b7df18ebbc",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 951,
         "digest": "sha256:5c950f577899130d49fba421b811bcee865c6e2d47ba64bffc7e3fd1f6cd4718",
         "platform": {
            "architecture": "amd64",
            "os": "windows"
         }
      }
   ]
}
```

**Comment by jayunit100** [comment]
Any update here? Curious wether containerd support for multi arch windows images is production ready or not , I think I've seen similar issues w nanoserver

**Comment by andyzhangx** [comment]
> Any update here? Curious wether containerd support for multi arch windows images is production ready or not , I think I've seen similar issues w nanoserver

@AbelHu do you know this issue? thanks.

**Comment by AbelHu** [comment]
@marosset may have the info

**Comment by marosset** [comment]
osVersion is missing from the above manifests. 
osVersion is required for containerd to pull multi-arch images on windows.

See docker manifest inspect mcr.microsoft.com/oss/kubernetes/pause:3.4.1 which correctly sets image metadata.
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 526,
         "digest": "sha256:8067f086e87d3307acd57458b479607346634937175a100f89892ea6854e0a42",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1158,
         "digest": "sha256:565501aebaf23dd687a04ae41511819c854b0447aab91acf70217cc56885ea47",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.17763.1697"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1158,
         "digest": "sha256:b2705d14522126946cb4c869b6656bf597b64693e8f412d7f3a9e1e2bb5bcd60",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.18362.1256"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1158,
         "digest": "sha256:a705346c5eb032801fc26d45bacecfa12a92e0a1d2b8fd400ff133be6a13c209",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.18363.1316"
         }
      },

**Comment by marosset** [comment]
It looks like @chewong already addressed this issue with

https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/462

https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/462/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R151-R156

Do these images just need to be rebuilt with these changes?

**Comment by marosset** [comment]
Actually looks like v0.10.0 is fixed

 docker manifest inspect mcr.microsoft.com/k8s/csi/azurefile-csi:v0.10.0
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1165,
         "digest": "sha256:f46dda6e4c6e668b5c58ca9185a5ec8a1b4748d207b9886d7641e9319dd9bb88",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 951,
         "digest": "sha256:49997de8a64715f1384dfad7eafb8295f31a3d7b0dac40ced47a04def9d89c9d",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.17763.1637"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 951,
         "digest": "sha256:d609128f0358a56d07349ce51cbb8b7b245dc6350c8bd664c2b27b65e70488eb",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.18362.1256"
         }
      },

**Comment by andyzhangx** [comment]
thanks, I will try again on containerd cluster.

**Comment by abhisheksinghbaghel** [comment]
@marosset issue is with the latest manifest list. vx.x.x ones are ok.
Potential fix for azuredisk-csi being discussed here https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/702

azureuser@abhib-dev-ubuntu-18:~/go/src/sigs.k8s.io/azuredisk-csi-driver/deploy$ docker manifest inspect mcr.microsoft.com/k8s/csi/azurefile-csi:latest{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1165,
         "digest": "sha256:c3c285af61abe8d8aacaedc7744fc44890caedd0b18f21b1f659f413b1c1b901",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 951,
         "digest": "sha256:1c56abbee556b61d38ed80467711923d84faf6c7a6298b15ccd71b28463a73e7",
         "platform": {
            "architecture": "amd64",
            "os": "windows"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 951,
         "digest": "sha256:25544e12654e1afd997b60f351d80a94dfdd5bbbf631af5b7917bec86ddd7a2f",
         "platform": {
            "architecture": "amd64",
            "os": "windows"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 951,
         "digest": "sha256:f9b2c5019a8c06d8b9002d181962e16fec59c3c839041a6d07b06cc907222671",
         "platform": {
            "architecture": "amd64",
            "os": "windows"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 951,
         "digest": "sha256:0cdd9cc0de957047a61586252f7f6e0429b8fc901122238b6040e9cbb7d923e8",
         "platform": {
            "architecture": "amd64",
            "os": "windows"
         }
      }
   ]
}
