### ISSUE TITLE
test: enable ` csi-proxy.exe` before executing Windows unit tests

### ISSUE THREAD

**Issue by mayankshah1607** [kubernetes-sigs/azurefile-csi-driver#426]
**What happened**:

Following https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/421#discussion_r488569749, the unit test pipeline on Windows will have to be changed to run `csi-proxy.exe` to avoid type casting errors. 

**What you expected to happen**:

**How to reproduce it**:

Run unit tests on Windows using the `go test` command. Though the tests pass, a lot of the tests are deliberately asserting on the type casting error to prevent failures.

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
csi-proxy.exe could be downloaded here: https://kubernetesartifacts.azureedge.net/csi-proxy/v0.2.0/binaries/csi-proxy.tar.gz
and it could be configured as a service or simply run as a process is ok in unit test
https://github.com/kubernetes-csi/csi-proxy/blob/master/cmd/csi-proxy/main.go#L22-L25

**Comment by andyzhangx** [comment]
it's done
