### ISSUE TITLE
failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com

### ISSUE THREAD

**Issue by junsaw** [kubernetes-sigs/azurefile-csi-driver#449]
I am seeing this on my csi-attacher container:

I1003 15:36:17.456440       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:36:17.456492       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:36:26.640187       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:36:26.640225       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:36:37.385733       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:36:37.385751       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:36:46.843777       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:36:46.843816       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:36:56.952952       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:36:56.952966       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:37:03.675270       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:37:03.675285       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:37:12.282778       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:37:12.282817       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:37:17.746687       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:37:17.746712       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:37:23.790661       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:37:23.790748       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:37:34.256887       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:37:34.256914       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:37:43.512586       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:37:43.512598       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:37:53.907870       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:37:53.907926       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:38:04.132452       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:38:04.132480       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:38:14.722219       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:38:14.722257       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:38:25.503858       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:38:25.503882       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:38:31.619306       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:38:31.619346       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:38:38.493903       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:38:38.493917       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:38:44.259015       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:38:44.259039       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:38:50.340987       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:38:50.341025       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:39:00.420237       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:39:00.420269       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:39:08.666072       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:39:08.666088       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:39:17.156405       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:39:17.156485       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:39:26.260980       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:39:26.260998       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:39:33.995269       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:39:33.995550       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:39:44.128702       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:39:44.128728       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:39:54.399474       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:39:54.399489       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:40:01.645758       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:40:01.646134       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:40:11.922614       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:40:11.922639       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:40:18.802317       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:40:18.802346       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:40:25.028270       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:40:25.028315       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:40:30.624068       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:40:30.624105       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:40:35.803625       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:40:35.803650       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:40:43.570915       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:40:43.570940       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:40:54.211832       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:40:54.211859       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:41:03.976113       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:41:03.976139       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:41:13.640830       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:41:13.640855       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:41:23.803920       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:41:23.803950       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:41:33.255008       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:41:33.255559       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:41:39.390267       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:41:39.390281       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:41:46.026961       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:41:46.026976       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:41:55.014374       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:41:55.014413       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:42:01.671906       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:42:01.672141       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:42:12.573583       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:42:12.573610       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:42:18.236567       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:42:18.236596       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:42:28.209873       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:42:28.209899       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:42:36.392741       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:42:36.392778       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:42:47.336173       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:42:47.336198       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:42:53.314211       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:42:53.314249       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:43:01.655551       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:43:01.655569       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:43:10.646257       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:43:10.646282       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:43:15.756246       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:43:15.756273       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:43:21.323170       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:43:21.323254       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:43:29.099106       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:43:29.099259       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:43:39.414428       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:43:39.414443       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:43:48.828900       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:43:48.828926       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:43:57.546889       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:43:57.546914       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:44:04.752491       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:44:04.752516       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:44:12.982577       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:44:12.982599       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:44:20.511528       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:44:20.511554       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:44:25.768982       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:44:25.769017       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:44:34.778615       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:44:34.778635       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:44:39.898672       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:44:39.898705       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:44:48.344049       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:44:48.344092       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:44:56.701845       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:44:56.701869       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1003 15:45:06.081468       1 leaderelection.go:352] lock is held by k8s-node01 and has not yet expired
I1003 15:45:06.081498       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
^C

**Comment by andyzhangx** [comment]
that's expected since you have more than 1 driver controller, is there any functionality broken?

**Comment by junsaw** [comment]
my mounted files shares tend to reset their connection back to Azure. I will have to dig a little deeper to determine the root cause.  Please note: I am connectivity to the File Share over Private Link via VPN connection

**Comment by junsaw** [comment]
Thanks for the confirmation.
