### ISSUE TITLE
Randomly fails to mount Azure Fileshare volume

### ISSUE THREAD

**Issue by arindamdat** [kubernetes-sigs/azurefile-csi-driver#456]
**What happened**:
Randomly fails to mount Azure Fileshare. Pod stays in `ContainerCreating` state forever. Describing the Pod, found the following:

> Type     Reason              Age                      From                                         Message
>   ----     ------              ----                     ----                                         -------
>   Warning  FailedMount         8m23s (x103 over 3h54m)  kubelet, aks-npbalanced-14900033-vmss000001  MountVolume.WaitForAttach failed for volume "pvc-b3e955ca-e3a6-4bcf-846b-98234b22ac2b" : volume attachment is being deleted
>   Warning  FailedMount         3m3s (x79 over 3h54m)    kubelet, aks-npbalanced-14900033-vmss000001  Unable to attach or mount volumes: unmounted volumes=[storage-volume], unattached volumes=[storage-volume default-token-6w4nx]: timed out waiting for the condition
>   Warning  FailedAttachVolume  2m15s (x115 over 3h54m)  attachdetach-controller                      AttachVolume.Attach failed for volume "pvc-4a9462d2-17f4-4c32-9178-706b5b91f7bb" : volume attachment is being deleted

When I delete the pod and a new pod is scheduled, this problem goes away and the volume is mounted.
If a deployment has 2 replicas, then one pod runs without any issue but the other pod is stuck with this issue most of the time.
Following is a portion of log from
**`kubectl logs -n kube-system csi-azurefile-node-d459v -c azurefile`**

> I1014 07:56:12.787162       1 utils.go:111] GRPC call: /csi.v1.Identity/Probe
> I1014 07:56:12.787190       1 utils.go:112] GRPC request: 
> I1014 07:56:12.787200       1 utils.go:118] GRPC response: ready:<value:true > 
> I1014 07:56:38.842570       1 utils.go:111] GRPC call: /csi.v1.Node/NodeUnpublishVolume
> I1014 07:56:38.842621       1 utils.go:112] GRPC request: volume_id:"plt-dev-euw-rg#pltfilestoragedev#collaboration#" target_path:"/var/lib/kubelet/pods/cb0633b5-d18f-44b8-b89d-5ab9d8a9932f/volumes/kubernetes.io~csi/pvc-b3e955ca-e3a6-4bcf-846b-98234b22ac2b/mount" 
> I1014 07:56:38.842635       1 nodeserver.go:92] NodeUnPublishVolume: called with args {VolumeId:plt-dev-euw-rg#pltfilestoragedev#collaboration# TargetPath:/var/lib/kubelet/pods/cb0633b5-d18f-44b8-b89d-5ab9d8a9932f/volumes/kubernetes.io~csi/pvc-b3e955ca-e3a6-4bcf-846b-98234b22ac2b/mount XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
> I1014 07:56:38.842656       1 nodeserver.go:102] NodeUnpublishVolume: unmounting volume plt-dev-euw-rg#pltfilestoragedev#collaboration# on /var/lib/kubelet/pods/cb0633b5-d18f-44b8-b89d-5ab9d8a9932f/volumes/kubernetes.io~csi/pvc-b3e955ca-e3a6-4bcf-846b-98234b22ac2b/mount
> I1014 07:56:38.855715       1 mount_helper_common.go:71] "/var/lib/kubelet/pods/cb0633b5-d18f-44b8-b89d-5ab9d8a9932f/volumes/kubernetes.io~csi/pvc-b3e955ca-e3a6-4bcf-846b-98234b22ac2b/mount" is a mountpoint, unmounting
> I1014 07:56:38.855752       1 mount_linux.go:238] Unmounting /var/lib/kubelet/pods/cb0633b5-d18f-44b8-b89d-5ab9d8a9932f/volumes/kubernetes.io~csi/pvc-b3e955ca-e3a6-4bcf-846b-98234b22ac2b/mount
> I1014 07:56:38.890792       1 mount_helper_common.go:85] "/var/lib/kubelet/pods/cb0633b5-d18f-44b8-b89d-5ab9d8a9932f/volumes/kubernetes.io~csi/pvc-b3e955ca-e3a6-4bcf-846b-98234b22ac2b/mount" is unmounted, deleting the directory
> I1014 07:56:38.890877       1 nodeserver.go:107] NodeUnpublishVolume: unmount volume plt-dev-euw-rg#pltfilestoragedev#collaboration# on /var/lib/kubelet/pods/cb0633b5-d18f-44b8-b89d-5ab9d8a9932f/volumes/kubernetes.io~csi/pvc-b3e955ca-e3a6-4bcf-846b-98234b22ac2b/mount successfully

**What you expected to happen**:
Azure fileshare should have been mounted successfully always.
**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: v0.8.0
- Kubernetes version (use `kubectl version`): 1.17.7

**Comment by andyzhangx** [comment]
@arindamdat from the log `volume attachment is being deleted`, it actually fails here:
https://github.com/kubernetes/kubernetes/blob/6d01c5a58996d1619ac049c2b3077274299eb2d0/pkg/volume/csi/csi_attacher.go#L636-L638

What is your storage class, pvc and deployment configs? I would like to repro it if possible.

**Comment by andyzhangx** [comment]
could you also share the `csi-attacher` container logs from csi-azurefile-controller? thanks.

**Comment by arindamdat** [comment]
Hi @andyzhangx , thanks for your reply. The information (storageClass, deployment, pvc, attacher logs etc) which you sought, are available here https://www.dropbox.com/sh/isthz1lp28fnycd/AAA0KXFA-b9jjvU9FSO0GF-Ca?dl=0
Looking at the `csi-attacher` log, this particular portion seemed interesting to me, so just copy-pasting that particular portion here too:

> I1014 07:54:46.447345       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:54:51.462758       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:54:56.482591       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:55:01.498498       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:55:06.516239       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:55:10.674761       1 reflector.go:432] k8s.io/client-go/informers/factory.go:135: Watch close - *v1beta1.VolumeAttachment total 4 items received
> I1014 07:55:11.536833       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:55:16.552950       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:55:21.569896       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:55:26.591036       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:55:31.610393       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:55:36.629840       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:55:41.654067       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:55:46.693474       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:55:51.710689       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:55:56.729169       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:56:01.746246       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:56:06.769358       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:56:11.785602       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:56:16.803352       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:56:19.244832       1 reflector.go:432] k8s.io/client-go/informers/factory.go:135: Watch close - *v1beta1.CSINode total 0 items received
> I1014 07:56:21.823056       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:56:26.840338       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:56:31.861885       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:56:36.878388       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:56:41.895038       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:56:46.916404       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:56:51.931756       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:56:56.950251       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:57:01.965721       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:57:06.991448       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:57:12.015972       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:57:17.034727       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:57:22.062093       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:57:27.078747       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:57:32.097664       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:57:37.116552       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:57:42.135473       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:57:47.152070       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:57:52.169783       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:57:57.187673       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:58:02.204787       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:58:07.222472       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:58:12.241174       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:58:17.258076       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:58:22.275394       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:58:27.297910       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:58:32.315649       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:58:32.950515       1 reflector.go:432] k8s.io/client-go/informers/factory.go:135: Watch close - *v1.PersistentVolume total 0 items received
> I1014 07:58:37.333348       1 leaderelection.go:283] successfully renewed lease kube-system/external-attacher-leader-file-csi-azure-com
> I1014 07:58:41.929384       1 controller.go:198] Started VA processing "csi-af19655753a8b30ac5fafa5c02e2dec3eef284b1c579d627077a9aa2f29384cc"
> I1014 07:58:41.929425       1 csi_handler.go:209] CSIHandler: processing VA "csi-af19655753a8b30ac5fafa5c02e2dec3eef284b1c579d627077a9aa2f29384cc"
> I1014 07:58:41.929433       1 csi_handler.go:260] Starting detach operation for "csi-af19655753a8b30ac5fafa5c02e2dec3eef284b1c579d627077a9aa2f29384cc"
> I1014 07:58:41.929498       1 csi_handler.go:267] Detaching "csi-af19655753a8b30ac5fafa5c02e2dec3eef284b1c579d627077a9aa2f29384cc"
> I1014 07:58:41.929515       1 csi_handler.go:575] Saving detach error to "csi-af19655753a8b30ac5fafa5c02e2dec3eef284b1c579d627077a9aa2f29384cc"
> I1014 07:58:41.938871       1 csi_handler.go:586] Saved detach error to "csi-af19655753a8b30ac5fafa5c02e2dec3eef284b1c579d627077a9aa2f29384cc"
> I1014 07:58:41.938898       1 csi_handler.go:219] Error processing "csi-af19655753a8b30ac5fafa5c02e2dec3eef284b1c579d627077a9aa2f29384cc": failed to detach: persistentvolume "pvc-2b1ed3ba-b1a5-4488-9abe-abd218cd5885" not found
> I1014 07:58:41.939076       1 controller.go:158] Ignoring VolumeAttachment "csi-af19655753a8b30ac5fafa5c02e2dec3eef284b1c579d627077a9aa2f29384cc" change

**Comment by andyzhangx** [comment]
sorry I cannot repro with your config, is it possible to try on another cluster, I think there is volume controller is wrong in your cluster, ask MS support to reconcile your cluster may help. I have tried using same PVC on 6 pods, could not repro:
```
# k get po -o wide
NAME                                    READY   STATUS    RESTARTS   AGE   IP             NODE                                NOMINATED NODE   READINESS GATES
deployment-azurefile-85f5f58689-6j6bg   1/1     Running   0          25s   10.240.0.101   aks-agentpool-20968559-vmss000002   <none>           <none>
deployment-azurefile-85f5f58689-8pdzb   1/1     Running   0          25s   10.240.0.25    aks-agentpool-20968559-vmss000002   <none>           <none>
deployment-azurefile-85f5f58689-gvn2x   1/1     Running   0          25s   10.240.0.65    aks-agentpool-20968559-vmss000002   <none>           <none>
deployment-azurefile-85f5f58689-nqhck   1/1     Running   0          25s   10.240.0.27    aks-agentpool-20968559-vmss000002   <none>           <none>
deployment-azurefile-85f5f58689-pjxdz   1/1     Running   0          25s   10.240.0.42    aks-agentpool-20968559-vmss000002   <none>           <none>
deployment-azurefile-85f5f58689-t55mk   1/1     Running   0          25s   10.240.0.136   aks-agentpool-20968559-vmss000003   <none>           <none>
# k get no
NAME                                STATUS   ROLES   AGE   VERSION
aks-agentpool-20968559-vmss000002   Ready    agent   22h   v1.17.11
aks-agentpool-20968559-vmss000003   Ready    agent   22h   v1.17.11
virtual-node-aci-linux              Ready    agent   47h   v1.14.3-vk-azure-aci-v1.2.1.1

```

**Comment by arindamdat** [comment]
Hi, @andyzhangx I am getting this kind of logs from `csi-attacher`. Could this be related to this issue?
```
I1127 08:58:10.906284       1 leaderelection.go:352] lock is held by aks-npbalanced-14900033-vmss000005 and has not yet expired
I1127 08:58:10.906307       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1127 08:58:19.098191       1 leaderelection.go:352] lock is held by aks-npbalanced-14900033-vmss000005 and has not yet expired
I1127 08:58:19.098231       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1127 08:58:24.711635       1 leaderelection.go:352] lock is held by aks-npbalanced-14900033-vmss000005 and has not yet expired
I1127 08:58:24.711657       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1127 08:58:31.214519       1 leaderelection.go:352] lock is held by aks-npbalanced-14900033-vmss000005 and has not yet expired
I1127 08:58:31.214540       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1127 08:58:38.048561       1 leaderelection.go:352] lock is held by aks-npbalanced-14900033-vmss000005 and has not yet expired
I1127 08:58:38.048615       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1127 08:58:47.361463       1 leaderelection.go:352] lock is held by aks-npbalanced-14900033-vmss000005 and has not yet expired
I1127 08:58:47.361488       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1127 08:58:53.862065       1 leaderelection.go:352] lock is held by aks-npbalanced-14900033-vmss000005 and has not yet expired
I1127 08:58:53.862276       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
I1127 08:58:59.136973       1 leaderelection.go:352] lock is held by aks-npbalanced-14900033-vmss000005 and has not yet expired
I1127 08:58:59.136995       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com

```

**Comment by arindamdat** [comment]
One more important point: I've started getting this error when multiple services/application started sharing the same Azure fileshare.

**Comment by arindamdat** [comment]
![image](https://user-images.githubusercontent.com/7764767/100431658-7e8cac80-30be-11eb-8914-ed1d1ddc3b03.png)
And if you have a look at this screenshot, you will see volume attaching is being succeeded only on this `***-vmss000005` node, which according to above logs has acquired the lock.

**Comment by arindamdat** [comment]
![image](https://user-images.githubusercontent.com/7764767/100433042-7fbed900-30c0-11eb-9d11-07ba34259e39.png)
To satisfy my suspicion, I forced all pods to be scheduled on `***-vmss000005`, and everything is successful now. Volume mounted and pod running successfully.
@andyzhangx , Sorry for providing the information so late, but this information might be useful to finding out root cause. It doesn't seem to be an AKS cluster issue, but an issue with the driver itself?

**Comment by andyzhangx** [comment]
`csi-attacher` logs looks normal since there are two controllers, one is leader and holding the lock. Does it only fail on `vmss000001`? you could `kubectl cordon vmss000001` and then reimage that node, looks like there is sth. wrong with that node.

**Comment by arindamdat** [comment]
@andyzhangx , I tested it with all 4 nodes. Except `vmss000005`, volume attachment fails on all other nodes with the same error `timed out waiting for the condition`. Do you suggest to reimage all other nodes except `vmss000005`?

**Comment by arindamdat** [comment]
@andyzhangx , unfortunately reimaging the node didn't work. I cordoned and drained a node, reimaged it. Then I scheduled the pods on that node. Still it fails with the same error.

**Comment by arindamdat** [comment]
Reimaging the nodes didn't work. Then I completely deleted the entire nodepool and re-created. Still the same issue persists.

**Comment by arindamdat** [comment]
What I found is that, it's trying to attach wrong `PersistentVolume`. Things are happening as below:

- The pods are using `PersistentVolumeClaim ` with name `col-wopi-svc-api-pvc`
- The PVC is Bound to a PersistentVolume with name `pvc-84db26d9-0b42-49a5-a856-af1913c71495`
- However, the Error Message says `AttachVolume.Attach failed for volume "pvc-715d05c1-ea17-4421-a26f-b5544f6445ad"`. Notice the name of the PersistentVolume is different here. This PersistentVolume is already bound by another Claim from another deployment.
**Any idea what is going wrong?**

**Comment by andyzhangx** [comment]
could you run:
 - `kubectl get VolumeAttachment`
 - `kubectl get VolumeAttachment xxx -o yaml`
to provide more details?

I think you kube-controller-manager could be in stale state, one workaround is file a ticket to ask MS support to reconcile the cluster, let me know whether that works.

**Comment by arindamdat** [comment]
The yaml output of a VolumeAttachment is given below:
```
apiVersion: storage.k8s.io/v1
kind: VolumeAttachment
metadata:
  annotations:
    csi.alpha.kubernetes.io/node-id: aks-npbalanced-14900033-vmss000002
  creationTimestamp: "2020-11-29T08:14:48Z"
  finalizers:
  - external-attacher/file-csi-azure-com
  managedFields:
  - apiVersion: storage.k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:csi.alpha.kubernetes.io/node-id: {}
        f:finalizers:
          .: {}
          v:"external-attacher/file-csi-azure-com": {}
      f:status:
        f:attached: {}
    manager: csi-attacher
    operation: Update
    time: "2020-11-29T08:14:48Z"
  - apiVersion: storage.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:attacher: {}
        f:nodeName: {}
        f:source:
          f:persistentVolumeName: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-11-29T08:14:48Z"
  name: csi-7c9974fcadcb0829cf65a2e5dbc3b9e21b9ba4af01c78234a834a401860808c1
  resourceVersion: "38830508"
  selfLink: /apis/storage.k8s.io/v1/volumeattachments/csi-7c9974fcadcb0829cf65a2e5dbc3b9e21b9ba4af01c78234a834a401860808c1
  uid: 5a5c7af3-c0ba-4f0f-9fc0-cd3cac48cb82
spec:
  attacher: file.csi.azure.com
  nodeName: aks-npbalanced-14900033-vmss000002
  source:
    persistentVolumeName: pvc-e6232929-d523-4545-b0c1-7da2ea8a200c
status:
  attached: true

```
One question: can you please little elaborate what made you to suspect that the `kube-controller-manager` could be in stale state? P.S: There are 10s of other services running on the nodes with persistence enabled (though not with Azure fileshare, but other kinds like disk etc).

**Comment by arindamdat** [comment]
HI @andyzhangx , after deleting the cluster and recreating it (it was our Dev cluster), the issue seems to have resolved!

**Comment by andyzhangx** [comment]
@arindamdat thanks for the reply, I think it's an upstream issue, already worked out a PR to fix this issue: https://github.com/kubernetes/kubernetes/pull/96952

**Comment by darose** [comment]
@andyzhangx I see this issue was closed due to going stale.  But the issue does not appear to have been fixed, as the PR you referenced was also closed due to going stale. (https://github.com/kubernetes/kubernetes/pull/96952)

We are still experiencing this issue in our Azure cluster, on csi driver v1.2.0.  Has this somehow been fixed in a later version?

**Comment by andyzhangx** [comment]
> @andyzhangx I see this issue was closed due to going stale. But the issue does not appear to have been fixed, as the PR you referenced was also closed due to going stale. ([kubernetes/kubernetes#96952](https://github.com/kubernetes/kubernetes/pull/96952))
> 
> We are still experiencing this issue in our Azure cluster, on csi driver v1.2.0. Has this somehow been fixed in a later version?

@darose not sure whether this is a bug in prior version, and we did not hit such issue in latest version(which has big csi-attacher version num)
