### ISSUE TITLE
Consider adding AZURE prefix to all env variables in E2E

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/azurefile-csi-driver#459]
Running tests in environments which deal with multiple providers, not just Azure, is a pretty common use case. We should consider renaming all the Azure specific environment variables to add an `AZURE_` prefix such that there are no collisions with other providers. For example, `LOCATION` should be `AZURE_LOCATION`. This might require some changes in kubetest as well. 

This is a follow up from https://github.com/kubernetes/test-infra/pull/19699.

/cc @chewong

**Comment by andyzhangx** [comment]
> Running tests in environments which deal with multiple providers, not just Azure, is a pretty common use case. We should consider renaming all the Azure specific environment variables to add an `AZURE_` prefix such that there are no collisions with other providers. For example, `LOCATION` should be `AZURE_LOCATION`. This might require some changes in kubetest as well.
> 
> This is a follow up from [kubernetes/test-infra#19699](https://github.com/kubernetes/test-infra/pull/19699).
> 
> /cc @chewong

sound reasonable for me, anyone could make the code change? thanks.

**Comment by CecileRobertMichon** [comment]
I can take it

/assign
