### ISSUE TITLE
Build Windows containers for multiple Windows server versions (including 2004)

### ISSUE THREAD

**Issue by marosset** [kubernetes-sigs/azurefile-csi-driver#460]
**Is your feature request related to a problem?/Why is this needed**

Windows containers must match the OS version of the host/node they are running on.
Currently the container images referenced in https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/deploy/v0.9.0/csi-azurefile-node-windows.yaml are only built for a single Windows OS version (2019).

**Describe the solution you'd like in detail**

We should update the build process/files to build mulit-arch images with a seperate image for each Windows Server OS listed at https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#windows-os-version-support

**Describe alternatives you've considered**

**Additional context**

This PR updates the build process for the pause image to build it for multiple Windows OS versions using buildx
https://github.com/kubernetes/kubernetes/pull/91452

**Comment by andyzhangx** [comment]
and we should use docker cli to add this field, it's already implemented in master branch:
https://github.com/docker/cli/pull/2578

**Comment by chewong** [comment]
It largely depends on the docker cli version that is installed in the kubekins image. For now, to add the os version without https://github.com/docker/cli/pull/2578, we could follow something similar to https://github.com/kubernetes/kubernetes/blob/master/build/pause/Makefile#L98-L105. WDYT?

**Comment by andyzhangx** [comment]
> It largely depends on the docker cli version that is installed in the kubekins image. For now, to add the os version without [docker/cli#2578](https://github.com/docker/cli/pull/2578), we could follow something similar to https://github.com/kubernetes/kubernetes/blob/master/build/pause/Makefile#L98-L105. WDYT?

ok for me, thanks.
