### ISSUE TITLE
Unable to get NFS volume mounts working.

### ISSUE THREAD

**Issue by PetterT2** [kubernetes-sigs/azurefile-csi-driver#475]
**What happened**:
Errors mounting NFS Azure file share.

-Container startup error/unable to mount

-PersitantVolumeClaim get stuck in pending:
Normal ExternalProvisioning 3s (x6 over 65s) persistentvolume-controller waiting for a volume to be created, either by external provisioner "file.csi.azure.com" or manually created by system administrator

-Mounting directly in pod via bash resulted in Permission Denied (example from portal file share)
sudo apt update
sudo apt install nfs-common
sudo mkdir -p /mount/storageaccountname/test1
sudo mount -t nfs storageaccountname.file.core.windows.net:/storageaccountname/test1 /mount/storageaccountname/test1 -o vers=4,minorversion=1,sec=sys

**What you expected to happen**:
The AKS pods should mount the NFS fileshare

**How to reproduce it**:
We tried following the instructions on:
https://docs.microsoft.com/en-us/azure/aks/azure-files-csi#create-nfs-file-share-storage-class

Create storage account via portal: 
Using same resource group as our aks cluster/target
West Europe
FileStorage
LRS
next->
Public endpoint (selected networks)
Add/select aks-vnet of our target (same resource group as selected above)
Microsoft network routing (default)
->next
->next
Secure transfer required: disabled
Allow Blob public access: enabled (default)
->next->create

Create file share in the storage account:
New file share->
100GiB
Select NFS (Preview)

Yaml/Json
{
"apiVersion": "storage.k8s.io/v1",
"kind": "StorageClass",
"metadata": {
"name": "volume-test1-nfs"
},
"provisioner": "file.csi.azure.com",
"parameters": {
"storageAccount": "teststorageaccountname",
"protocol": "nfs",
"shareName": "test1"
},
"reclaimPolicy": "Delete",
"volumeBindingMode": "Immediate",
"allowVolumeExpansion": true
}

(Also tried with only the basic params in the webpage guide)

{
"apiVersion": "v1",
"kind": "PersistentVolumeClaim",
"metadata": {
"name": "volume-claim-test1-nfs"
},
"spec": {
"accessModes": [
"ReadWriteMany"
],
"resources": {
"requests": {
"storage": "100Gi"
}
},
"storageClassName": "volume-test1-nfs"
}
}

deployment snippet:
.....
"spec": {
		"template": {
			"spec": {
				"containers": [
					{
						"volumeMounts": [
                                                       {
								"name": "test1-volume-nfs",
								"mountPath": "/test/test1nfs"
							}
......
"volumes": [
{
	"name": "test1-volume-nfs",
	"persistentVolumeClaim": {
		"claimName": "volume-claim-test1-nfs",
		"readOnly":false
	}
}
]

this results in pending status for volume claim.
"Normal ExternalProvisioning 3s (x6 over 65s) persistentvolume-controller waiting for a volume to be created, either by external provisioner "file.csi.azure.com" or manually created by system administrator"

skipping storage class above and adding PV->PVC like:
{
  "apiVersion": "v1",
  "kind": "PersistentVolume",
  "metadata": {
    "name": "volume-test1-nfs"
  },
  "spec": {
    "capacity": {
      "storage": "10Gi"
    },
    "accessModes": [
      "ReadWriteMany"
    ],
    "persistentVolumeReclaimPolicy": "Retain",
    "csi": {
      "driver": "file.csi.azure.com",
      "readOnly": false,
      "volumeHandle": "volume-test1-nfsid",
      "volumeAttributes": {
        "resourceGroup": "resurcegroupfromportal, i.e same",
        "storageAccount": "storageaccountname created above",
        "shareName": "test1",
        "protocol": "nfs"
      }
    }
  }
}

PVC:
{
  "apiVersion": "v1",
  "kind": "PersistentVolumeClaim",
  "metadata": {
    "name": "volume-claim-test1-nfs"
  },
  "spec": {
    "accessModes": [
      "ReadWriteMany"
    ],
    "resources": {
      "requests": {
        "storage": "10Gi"
      }
    },
	"volumeName":"volume-test1-nfs",
	"storageClassName":""
  }
}

after setting "storageClassName":"", the PVC gets status bound, but containers status hangs in ContainerCreating, with mount error on the nfs volume.

Tried all combos documents on the web and some guesswork from the examples in this repo, but no luck.

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
looks like you have not installed azure file csi driver? try: https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/install-csi-driver-v0.9.0.md

**Comment by PetterT2** [comment]
Thanks, it worked after installing the driver!

This would have been helpful to have in the guide section about kube-entities: https://docs.microsoft.com/en-us/azure/aks/azure-files-csi#create-nfs-file-share-storage-class.

For someone not knowing the preview state of NFS, it's hard to know that it is required to install the cis-driver manually and that it's not available as part of the NFS-Preview in AKS.

After installation of https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/v0.9.0/deploy/install-driver.sh
, it worked by:
{
  "apiVersion": "storage.k8s.io/v1",
  "kind": "StorageClass",
  "metadata": {
    "name": "storageclass-test1-nfs"
  },
  "provisioner": "file.csi.azure.com",
  "parameters": {
	"resourceGroup":"SameAsAKSTarget",
    "storageAccount": "storageaccountname",
    "protocol": "nfs",
	"shareName": "test1"
  }
}

{
  "apiVersion": "v1",
  "kind": "PersistentVolumeClaim",
  "metadata": {
    "name": "volume-claim-test1-nfs"
  },
  "spec": {
    "accessModes": [
      "ReadWriteMany"
    ],
    "resources": {
      "requests": {
        "storage": "100Gi"
      }
    },
    "storageClassName": "storageclass-test1-nfs"
  }
}

deployment snippet:
.....
"spec": {
"template": {
"spec": {
"containers": [
{
"volumeMounts": [
{
"name": "test1-volume-nfs",
"mountPath": "/test/test1nfs"
}
......
"volumes": [
{
"name": "test1-volume-nfs",
"persistentVolumeClaim": {
"claimName": "volume-claim-test1-nfs",
"readOnly":false
}
}
]

**Comment by andyzhangx** [comment]
thanks for the reply.
Currently there are two ways to install CSI drivers:
1.	Use “--aks-custom-headers EnableAzureDiskFileCSIDriver=true” to install CSI driver in AKS cluster creation
2.	Install CSI driver manually by user on existing cluster: https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/install-azurefile-csi-driver.md

@palma21 do you think we need to add doc for # 2 in AKS CSI driver doc, there are quite a lot customers already has a cluster and they want to use CSI driver new features, they need to install CSI driver on existing cluster.
