### ISSUE TITLE
Support NFS shares with private endpoints

### ISSUE THREAD

**Issue by queeno** [kubernetes-sigs/azurefile-csi-driver#528]
**Is your feature request related to a problem?/Why is this needed**
The CSI driver should use a private endpoint for an NFS share, if available.

**Describe the solution you'd like in detail**
If a private endpoint has been provisioned in the storage account, this should be used to access the NFS share.

**Describe alternatives you've considered**
If it's impossible to automatically discover, the DNS name for the private endpoint should be passed to the CSI driver via another mean, ie. storage class.

**Comment by andyzhangx** [comment]
it should already be supported, would you add a new parameter(`server`) in storage class:

Name | Meaning | Example | Mandatory | Default value 
--- | --- | --- | --- | ---
server | specify Azure storage account server address | existing server address, e.g. `accountname.privatelink.file.core.windows.net` | No | if empty, driver will use default `accountname.file.core.windows.net` or other sovereign cloud account address

**Comment by queeno** [comment]
Thanks for pointing this out. I managed to get this working.
