### ISSUE TITLE
Update example with static azurefile nfs share with kubernetes

### ISSUE THREAD

**Issue by abhiramani-iptiq** [kubernetes-sigs/azurefile-csi-driver#545]
**Is your feature request related to a problem?/Why is this needed**
Update example with static azurefile nfs share with kubernetes.we need static share so we can create our share with our own naming conventions

**Describe the solution you'd like in detail**
need example with static azurefile nfs share with kubernetes.

**Describe alternatives you've considered**
using dymanic provisioning for now

**Additional context**
updated document with static share examples

**Comment by andyzhangx** [comment]
it's here:
https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/deploy/example/pv-azurefile-nfs.yaml
https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/deploy/example/pvc-azurefile-csi-static.yaml

**Comment by abhiramani-iptiq** [comment]
Hi
do we still need to create storage class? because i see pv is also requires resource group and storage account name and below storage class also needs it so i see kind of duplicate to create both


apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-nfs
provisioner: file.csi.azure.com
parameters:
  resourceGroup: mypoc-rg
  storageAccount: mypocfilesnfs
  protocol: nfs

**Comment by abhiramani-iptiq** [comment]
yes tested works without creating StorageClass
