### ISSUE TITLE
Azure Files Static  Mount failed: exit status 32

### ISSUE THREAD

**Issue by junsaw** [kubernetes-sigs/azurefile-csi-driver#546]
I am using the azure file csi driver version *.10, using the Azure File Static configuration, I am unable to mount drive on the host/pod. 

ounting arguments: -t cifs -o dir_mode=0777,file_mode=0777,uid=0,gid=0,mfsymlinks,nosharesock,vers=3.0,actimeo=30,<masked> //jrinfrak8ssa.file.core.windows.net/junior-k8s-influxdb /var/lib/kubelet/plugins/kubernetes.io/csi/pv/junior-k8s-influxdb/globalmount
Output: mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
I0129 01:21:21.542172       1 utils.go:108] GRPC call: /csi.v1.Node/NodeGetCapabilities
I0129 01:21:21.542192       1 utils.go:109] GRPC request: {}
I0129 01:21:21.542233       1 utils.go:114] GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}}]}
I0129 01:21:21.547041       1 utils.go:108] GRPC call: /csi.v1.Node/NodeStageVolume
I0129 01:21:21.547062       1 utils.go:109] GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/junior-k8s-influxdb/globalmount","volume_capability":{"AccessType":{"Mount":{"mount_flags":["dir_mode=0777","file_mode=0777","uid=0","gid=0","mfsymlinks","nosharesock"]}},"access_mode":{"mode":5}},"volume_context":{"resourceGroup":"junior-infra-rg-eu","shareName":"junior-k8s-influxdb","storageAccount":"jrinfrak8ssa"},"volume_id":"k8s-influxdb"}
W0129 01:21:21.547173       1 azurefile.go:432] parsing volumeID(k8s-influxdb) return with error: error parsing volume id: "k8s-influxdb", should at least contain two #
I0129 01:21:21.547183       1 azurefile.go:322] got storage account(jrinfrak8ssa) from secret
I0129 01:21:21.547207       1 nodeserver.go:193] cifsMountPath(/var/lib/kubelet/plugins/kubernetes.io/csi/pv/junior-k8s-influxdb/globalmount) fstype() volumeID(k8s-influxdb) context(map[resourceGroup:junior-infra-rg-eu shareName:junior-k8s-influxdb storageAccount:jrinfrak8ssa]) mountflags([dir_mode=0777 file_mode=0777 uid=0 gid=0 mfsymlinks nosharesock]) mountOptions([dir_mode=0777 file_mode=0777 uid=0 gid=0 mfsymlinks nosharesock vers=3.0 actimeo=30])
I0129 01:21:21.547277       1 mount_linux.go:146] Mounting cmd (mount) with arguments (-t cifs -o dir_mode=0777,file_mode=0777,uid=0,gid=0,mfsymlinks,nosharesock,vers=3.0,actimeo=30,<masked> //jrinfrak8ssa.file.core.windows.net/junior-k8s-influxdb /var/lib/kubelet/plugins/kubernetes.io/csi/pv/junior-k8s-influxdb/globalmount)
E0129 01:21:21.842271       1 mount_linux.go:150] Mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t cifs -o dir_mode=0777,file_mode=0777,uid=0,gid=0,mfsymlinks,nosharesock,vers=3.0,actimeo=30,<masked> **//jrinfrak8ssa.file.core.windows.net/junior-k8s-influxdb /var/lib/kubelet/plugins/kubernetes.io/csi/pv/junior-k8s-influxdb/globalmount**
Output: mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)

E0129 01:21:21.842316       1 utils.go:112] GRPC error: rpc error: code = Internal desc = volume(k8s-influxdb) mount "//jrinfrak8ssa.file.core.windows.net/junior-k8s-influxdb" on "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/junior-k8s-influxdb/globalmount" failed with mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t cifs -o dir_mode=0777,file_mode=0777,uid=0,gid=0,mfsymlinks,nosharesock,vers=3.0,actimeo=30,<masked> **//jrinfrak8ssa.file.core.windows.net/junior-k8s-influxdb /var/lib/kubelet/plugins/kubernetes.io/csi/pv/junior-k8s-influxdb/globalmount**
Output: mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)

**Persistent Volume yaml:**

apiVersion: v1
kind: PersistentVolume
metadata:
  name: junior-k8s-influxdb
  namespace: k8s-influxdb
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # if set as "Delete" file share would be removed in pvc deletion
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict  # https://linux.die.net/man/8/mount.cifs
    - nosharesock
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: k8s-influxdb  # make sure it's a unique id in the cluster
    volumeAttributes:
      resourceGroup: junior-infra-rg-eu  # optional, only set this when storage account is not in the same resource group as agent node
      storageAccount: jrinfrak8ssa
      shareName: junior-k8s-influxdb  # only file share name, don't use full path
    nodeStageSecretRef:
      name:  azure-jrinfrak8ssa-secret
      namespace:  k8s-influxdb

Any help will be much appreciated.

**Comment by junsaw** [comment]
Configuration Error, my issue is my share got deleted. Please ensure that the share exists

**Comment by andyzhangx** [comment]
close issue since it's resolved
