### ISSUE TITLE
csi drivers don't work with the virtual node of AKS

### ISSUE THREAD

**Issue by chunliu** [kubernetes-sigs/azurefile-csi-driver#548]
**What happened**:

When enabling the virtual node on an AKS cluster which has the csi drivers installed, the **csi-azuredisk-node** and **csi-azurefile-node** pods created for the virtual node would fail with status `ProviderFailed`. 

![image](https://user-images.githubusercontent.com/2128551/106348125-db932180-62fe-11eb-93fc-67298ae21efb.png)

`kubectl describe pod` shows: `ACI does not support providing args without specifying the command. Please supply both command and args to the pod spec.`

**What you expected to happen**:

The pods should work on the virtual node. 

**How to reproduce it**:

Enable the virtual node on the AKS cluster which has the csi drivers installed. 

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`): v1.18.14
- OS (e.g. from /etc/os-release): virtual node version v1.18.4-vk-azure-aci-v1.3.2
- Kernel (e.g. `uname -a`): 
- Install tools: --aks-custom-headers EnableAzureDiskFileCSIDriver=true
- Others:

**Comment by andyzhangx** [comment]
CSI driver does not work on virtual node now, there is a feature request: https://github.com/virtual-kubelet/azure-aci/issues/88

**Comment by andyzhangx** [comment]
BTW, which csi driver version are you running with? Node driver should not be scheduled on the virtual node: 
https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/2796568606098d9cbb9f14ea34031c787136f172/deploy/csi-azurefile-node.yaml#L21-L29

**Comment by chunliu** [comment]
The drivers were installed with `--aks-custom-headers EnableAzureDiskFileCSIDriver=true`. I guess the version is v0.9.0?
```
❯ kubectl get daemonset -n kube-system csi-azurefile-node -o jsonpath='{range .spec.template.spec.containers[*]}{.image}{"\n"}{end}'
mcr.microsoft.com/oss/kubernetes-csi/livenessprobe:v1.1.0
mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v2.0.1
mcr.microsoft.com/k8s/csi/azurefile-csi:v0.9.0
```
And there seems no affinity defined in it. `❯ kubectl get daemonset -n kube-system csi-azurefile-node -o jsonpath='{.spec.template.spec.affinity}'` returned nothing.

**Comment by andyzhangx** [comment]
the AKS built-in CSI driver is still on v0.9.0, we will GA this feature in March with v1.0.0, stay tuned.
