### ISSUE TITLE
ARO: csi-azurefile-controller crash (NFS) panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by TiloGit** [kubernetes-sigs/azurefile-csi-driver#569]
**What happened**:
Create first PVC with NFS storage class uses and both controller get to CrashLoopBackOff

**What you expected to happen**:
get my PVC with NFS

**How to reproduce it**:
Delete PVC and the CrashLoopBackOff stops

**Anything else we need to know?**:
Logs:  [csi-azurefile-controller-7db68c9c5c-j75jc-azurefile.log](https://github.com/kubernetes-sigs/azurefile-csi-driver/files/6046169/csi-azurefile-controller-7db68c9c5c-j75jc-azurefile.log)

```
I0225 22:46:31.032944       1 utils.go:119] GRPC request: {"capacity_range":{"required_bytes":107374182400},"name":"pvc-c4d2b2b0-49a1-44de-ae26-c0be56b85f23","parameters":{"location":"canadacentral","resourceGroup":"CL-EXT-OCP-NPRD-RG","storageAccount":"ocpnfsstg"},"volume_capabilities":[{"AccessType":{"Mount":{}},"access_mode":{"mode":5}}]}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1535ec0]
```

PVC Events: 
```
Generated from file.csi.azure.com_cl-ext-ocp-cls01-nprd-wz28q-worker-canadacentral1-myid
failed to provision volume with StorageClass "azure-file-nfs": rpc error: code = Unavailable desc = transport is closing
```

POD status: 
```
[tilo@clexjpbapd01 cp4a-setup]$ kubectl get po -o wide -n kube-system | grep csi-azurefile-controller
csi-azurefile-controller-7db68c9c5c-4mxlt   1/6     CrashLoopBackOff   78         164m   10.53.177.12   cl-ext-ocp-cls01-nprd-wz28q-worker-canadacentral1-zztwh   <none>           <none>
csi-azurefile-controller-7db68c9c5c-j75jc   1/6     CrashLoopBackOff   76         164m   10.53.177.4    cl-ext-ocp-cls01-nprd-wz28q-worker-canadacentral1-vgtjr   <none>           <none>

```
**Environment**:
- CSI Driver version:  Driver Version: v1.1.0
- Kubernetes version (use `kubectl version`): OC Server Version: 4.5.31  Kubernetes Version: v1.18.3+e574db2
- OS (e.g. from /etc/os-release):  Red Hat Enterprise Linux CoreOS 45.82.202101291733-0 (Ootpa)
- Kernel (e.g. `uname -a`):   4.18.0-193.41.1.el8_2.x86_64   cri-o://1.18.4-6.rhaos4.5.gitbe796d1.el8
- Install tools: kubectl
- Others: Azure OpenShift (ARO)

**Comment by andyzhangx** [comment]
crash is expected since you don't provide any cloud cloud credentials for the controller:
```
I0225 22:46:10.172601       1 azure_auth.go:232] Using AzurePublicCloud environment
I0225 22:46:10.172645       1 azure.go:418] Azure cloud provider is starting without credentials
```

follow guide here for configuration now: https://github.com/Azure/OpenShift/issues/216

**Comment by TiloGit** [comment]
I did set the config map, without that it wouldn't even deploy. 

`oc create configmap azure-cred-file --from-literal=path="/etc/kubernetes/cloud.conf" -n kube-system`

**Comment by andyzhangx** [comment]
> cloud.conf

does your `cloud.conf` has following fields?
```
{
"tenantId": "$tenantId",
"subscriptionId": $subId,
"resourceGroup": "$managed_rg_name",
"useManagedIdentityExtension": false,
"aadClientId": "$aadClientId",
"aadClientSecret": "$aadClientSecret"
}
```

**Comment by TiloGit** [comment]
not sure, I assumed the ARO has it after using the CM. 

I followed https://github.com/ezYakaEagle442/aro-pub-storage/blob/master/setup-store-CSI-driver-azure-file.md
And succefully got a SMB created. Now just sorting out NFS. 

you can close this ticket or add a more graceful way of handling lack of cloud_conf. 

Thanks for your help.
