### ISSUE TITLE
error while creating mount source path 

### ISSUE THREAD

**Issue by rajdhandus** [kubernetes-sigs/azurefile-csi-driver#570]
**What happened**: Not able to launch statefulset

**What you expected to happen**: Able to launch statefulset configured with NFS file mount

**How to reproduce it**: Launch multiple statefulsets back to back

**Anything else we need to know?**:

```
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       ContainerCannotRun
      Message:      error while creating mount source path '/var/lib/kubelet/pods/9dfd3bcb-621a-4b9b-b18d-7db36f8a5238/volumes/kubernetes.io~csi/pvc-b6735cfd-682a-4c82-a316-e2819d0bdb64/mount': mkdir /var/lib/kubelet/pods/9dfd3bcb-621a-4b9b-b18d-7db36f8a5238/volumes/kubernetes.io~csi/pvc-b6735cfd-682a-4c82-a316-e2819d0bdb64/mount: file exists
      Exit Code:    128
      Started:      Sat, 27 Feb 2021 01:46:34 -0500
      Finished:     Sat, 27 Feb 2021 01:46:34 -0500
    Ready:          False
    Restart Count:  7
```

**Environment**:
- CSI Driver version: Version: v2.1.0-0-gb7a8fe9fe
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-19T09:16:25Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"5de7fd1f9555368a86eb0f8f664dc58055c17269", GitTreeState:"clean", BuildDate:"2021-01-18T09:31:01Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from /etc/os-release): Ubuntu 18.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
is this still an issue now? how to repro this issue?
