### ISSUE TITLE
[PV expansion]MountVolume.NodeExpandVolume failed : Expander.NodeExpand found CSI plugin kubernetes.io/csi/file.csi.azure.com to not support node expansion

### ISSUE THREAD

**Issue by aviorma** [kubernetes-sigs/azurefile-csi-driver#573]
**What happened**:

Mount issue with expended PVC
MountVolume.NodeExpandVolume failed : Expander.NodeExpand found CSI plugin kubernetes.io/csi/file.csi.azure.com to not support node expansion

**What you expected to happen**:
expansion sucess

**How to reproduce it**:

Create a pvc from azurefile-csi
expend the pvc size 
**Anything else we need to know?**:

**Environment**:
- CSI Driver version: bundled in AKS
- Kubernetes version (use `kubectl version`):
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"5de7fd1f9555368a86eb0f8f664dc58055c17269", GitTreeState:"clean", BuildDate:"2021-01-18T09:31:01Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from /etc/os-release): AKS + CSI ENABLED (Ubuntu 18.04.5 LTS)
- Kernel (e.g. `uname -a`): 5.4.0-1036-azure
- Install tools: AKS
- Others:

**Comment by andyzhangx** [comment]
hi @gnufied, do you know in that condition the above error would happen? It failed here: https://github.com/kubernetes/kubernetes/blob/v1.18.14/pkg/volume/csi/expander.go#L80, while Azure File CSI driver does not implement `NodeExpand` and also it does not have `NodeServiceCapability_RPC_EXPAND_VOLUME` cap.

There is no such issue in k8s 1.20.2. Thanks.

**Comment by aviorma** [comment]
it is happening when i am trying the expand my PVC with v1.18.14 AKS with CSI enabled with this 
        --aks-custom-headers EnableAzureDiskFileCSIDriver=true

**Comment by andyzhangx** [comment]
@aviorma could you provide full events of `kubectl describe pvc pvc-name`

**Comment by aviorma** [comment]
`Events:
  Type     Reason                  Age   From                                 Message
  ----     ------                  ----  ----                                 -------
  Warning  ExternalExpanding       15s   volume_expand                        Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
  Normal   Resizing                15s   external-resizer file.csi.azure.com  External resizer is resizing volume pvc-f0593669-852a-4ef6-8c65-b4ccfb8335fa
  Normal   VolumeResizeSuccessful  14s   external-resizer file.csi.azure.com  Resize volume succeeded`

**Comment by aviorma** [comment]
> pvc-f0593669-852a-4ef6-8c65-b4ccfb8335fa   1200       RWX            Delete           Bound    sisense/storage                                                                                                             sisense-azurefile-csi-premium            6d16h

1200 displayed with no Gi suffix 

is it ok ?

**Comment by andyzhangx** [comment]
o, you should resize pvc instead of pv, I just tried on aks 1.18.14, it works well:
 - `k edit pvc persistent-storage-statefulset-azurefile-nonroot-0` change `spec.resources.requests.storage` and then it should work:

```
# k describe pvc persistent-storage-statefulset-azurefile-nonroot-0
Name:          persistent-storage-statefulset-azurefile-nonroot-0
Namespace:     default
StorageClass:  azurefile-csi
Status:        Bound
Volume:        pvc-adb30cfc-c321-4944-b310-969b90c1a9ce
Labels:        app=nginx
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-class: azurefile-csi
               volume.beta.kubernetes.io/storage-provisioner: file.csi.azure.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      120
Access Modes:  RWX
VolumeMode:    Filesystem
Mounted By:    statefulset-azurefile-nonroot-0
Events:
  Type     Reason                  Age                From                                                                                               Message
  ----     ------                  ----               ----                                                                                               -------
  Normal   Provisioning            92s                file.csi.azure.com_csi-azurefile-controller-77c6f6465c-drnfs_8c7aed77-b4dd-4c1e-a222-e5995b618105  External provisioner is provisioning volume for claim "default/persistent-storage-statefulset-azurefile-nonroot-0"
  Normal   ExternalProvisioning    80s (x2 over 92s)  persistentvolume-controller                                                                        waiting for a volume to be created, either by external provisioner "file.csi.azure.com" or manually created by system administrator
  Normal   ProvisioningSucceeded   72s                file.csi.azure.com_csi-azurefile-controller-77c6f6465c-drnfs_8c7aed77-b4dd-4c1e-a222-e5995b618105  Successfully provisioned volume pvc-adb30cfc-c321-4944-b310-969b90c1a9ce
  Warning  ExternalExpanding       19s                volume_expand                                                                                      Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
  Normal   Resizing                19s                external-resizer file.csi.azure.com                                                                External resizer is resizing volume pvc-adb30cfc-c321-4944-b310-969b90c1a9ce
  Normal   VolumeResizeSuccessful  19s                external-resizer file.csi.azure.com                                                                Resize volume succeeded
```

**Comment by aviorma** [comment]
As is sad it works 
the value in the PV is 

```
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: "1200"
```

Is it ok ? or should you add GI ?

**Comment by andyzhangx** [comment]
`1200` means `1200Gi` by default, so this is not an issue now, it works? How did you get the original error?

**Comment by aviorma** [comment]
PV expansion directly ..

**Comment by andyzhangx** [comment]
> PV expansion directly ..

thanks, I see, I leave this question(support PV expansion) to @gnufied since he is feature owner

**Comment by gnufied** [comment]
> PV expansion directly ..

does not sound like a bug. In this case the expansion happens entirely in control-plane and in external-resizer and kubelet plays no part in it, but since you expanded PV manually you ended up disrupting the state-machine we use. I don't think we support that operation.
