### ISSUE TITLE
Issue assigning a PV via a PVC to a Pod

### ISSUE THREAD

**Issue by BristolITDave** [kubernetes-sigs/azurefile-csi-driver#582]
What I'm trying to do: Use Azure Files CSI with ext4 to allow ReadWriteMany operations to pods. 
At the moment I've got a single volume file, a single pvclaim file, and a single app deployment.
In azure I get green ticks on the GUI and describe gives similar results.

**What happened**: 
Error from pod creation - stuck on ContainerCreating

Events:
  Type     Reason       Age               From               Message
  ----     ------       ----              ----               -------
  Normal   Scheduled    12s               default-scheduler  Successfully assigned generic-moodle-testing/app-moodle-http-7b75c7499b-66fdw to aks-agentpool-37477834-vmss000001
  Warning  FailedMount  2s (x5 over 10s)  kubelet            MountVolume.MountDevice failed for volume "pv-azurefile" : rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8

**What you expected to happen**:
pod to mount the volume successfully

**How to reproduce it**:
Please see attached files. Note that the secret is imported and seems to work but not attached here for obvious reasons.

**Anything else we need to know?**:
I've reported this on slack in #provider-azure - but got told to report it here instead.

**Environment**:
- CSI Driver version: 1.0.0 
- Kubernetes version (use `kubectl version`): client: 1.20.4 server: 1.19.7 
- OS (e.g. from /etc/os-release): local OS is Windows 10. remote is Azure
- Kernel (e.g. `uname -a`): n/A
- Install tools: N/A
- Others: N/A

[Generic-Azure-CSI-Dynamic.zip](https://github.com/kubernetes-sigs/azurefile-csi-driver/files/6101413/Generic-Azure-CSI-Dynamic.zip)

**Comment by andyzhangx** [comment]
ext4 fsType is actually a vhd disk, it only supports ReadWriteOnce, does not support ReadWriteMany

**Comment by BristolITDave** [comment]
Ok thanks Andy - I'll close this because I'll have to go a different route. (Still an odd error message though!)
