### ISSUE TITLE
support using existing azure file share in storage class

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azurefile-csi-driver#59]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

scenario is like this:
https://github.com/csi-driver/blobfuse-csi-driver#option1-use-existing-credentials-in-k8s-cluster

Need to add a new parameter(`shareName`) in azure file storage class, and create an azure file if it does not exist:

https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/224a7d36921cc7ce354cef12c9e8ae791cc1371a/pkg/azurefile/controllerserver.go#L90

**Describe alternatives you've considered**

**Additional context**

/assign

**Comment by ashishranjan738** [comment]
I think i can take this up

**Comment by andyzhangx** [comment]
it's not a urgent feature, let me change the interface in azure cloud provider first since currently it still uses `func (s *Share) Create(options *FileRequestOptions)`  other than `func (s *Share) CreateIfNotExists(options *FileRequestOptions)` func

**Comment by lenisha** [comment]
we have a scenario to mount azure files using the cluster identity or secrets coming from Vault

**Comment by andyzhangx** [comment]
The PR(https://github.com/kubernetes/kubernetes/pull/77042) is already merged in v1.14.2, upgrade to use  that lib and a few code change could make this feature work.
