### ISSUE TITLE
[in-tree storage driver] The specifed resource name contains invalid characters

### ISSUE THREAD

**Issue by chewong** [kubernetes-sigs/azurefile-csi-driver#600]
**What happened**:

Failing tests in https://testgrid.k8s.io/provider-azure-master-signal#aks-engine-azure-file

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
@nearora-msft could you take a look at this issue? thanks.
```
Mar 18 20:29:30.000: INFO: At 2021-03-18 20:24:48 +0000 UTC - event for pvc-79plr: {persistentvolume-controller } ProvisioningFailed: Failed to provision volume with StorageClass "azurefile-5541-kubernetes.io-azure-file-dynamic-sc-xxvzj": failed to create share kubetest-S70tgAp5-dyna-pvc-39da3a4f-b076-4d93-bf18-c633ea8875e8 in account f91d8817c921645aa859800: failed to get file share(kubetest-S70tgAp5-dyna-pvc-39da3a4f-b076-4d93-bf18-c633ea8875e8), err: storage.FileSharesClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidResourceName" Message="The specifed resource name contains invalid characters.\nRequestId:1ed4651c-a01a-004c-0a34-1c7845000000\nTime:2021-03-18T20:24:47.9501026Z"
```

https://storage.googleapis.com/kubernetes-jenkins/logs/aks-engine-azure-file-master/1372638203026083840/build-log.txt
