### ISSUE TITLE
selft managed cluster mount azurefile failed

### ISSUE THREAD

**Issue by situzhiheng** [kubernetes-sigs/azurefile-csi-driver#610]
What happened: 
1. install csi follow https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/install-csi-driver-master.md
2. refer https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/deploy/example/e2e_usage.md#option2-pvpvc mount the existing azurefile to the pod and get the error message as below:
----------------
Events:
  Type     Reason                  Age   From                     Message
  ----     ------                  ----  ----                     -------
  Normal   Scheduled               24s   default-scheduler        Successfully assigned default/client01 to node01
  Normal   SuccessfulAttachVolume  24s   attachdetach-controller  AttachVolume.Attach succeeded for volume "pv-azurefile"
  Warning  FailedMount             0s    kubelet                  MountVolume.MountDevice failed for volume "pv-azurefile" : rpc error: code = Internal desc = volume(unique-volumeid) mount "//xxx.file.core.chinacloudapi.cn/xxx" on "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-azurefile/globalmount" failed with mount failed: exit status 1
Mounting command: mount
Mounting arguments: -t cifs -o dir_mode=0777,file_mode=0777,uid=0,gid=0,mfsymlinks,cache=strict,nosharesock,vers=3.0,actimeo=30,<masked> //xxx.file.core.chinacloudapi.cn/xxx /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-azurefile/globalmount
Output: mount error: could not resolve address for xxx.file.core.chinacloudapi.cn: Unknown error

troubleshooting:
follow https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/csi-debug.md troubleshooting.
1. csi-azurefile-node-xxx status is running
2. pv status is bound
3. azurefile can be mounted on the node
4. csi-azurefile-node logs as below: 
Streaming logs below:
I0410 09:33:10.739684       1 azure.go:56] reading cloud config from secret
W0410 09:33:10.749341       1 azure_config.go:51] Failed to get cloud-config from secret: failed to get secret azure-cloud-provider: secrets "azure-cloud-provider" not found, skip initializing from secret
I0410 09:33:10.749363       1 azure.go:62] could not read cloud config from secret
I0410 09:33:10.749370       1 azure.go:65] AZURE_CREDENTIAL_FILE env var set as /etc/kubernetes/cloud.conf
I0410 09:33:10.749522       1 azure.go:82] read cloud config from file: /etc/kubernetes/cloud.conf successfully
I0410 09:33:10.752590       1 azure_auth.go:232] Using AzureChinaCloud environment
I0410 09:33:10.752631       1 azure.go:443] Azure cloud provider is starting without credentials
I0410 09:33:10.764505       1 mount_linux.go:163] Detected OS without systemd
I0410 09:33:10.764523       1 driver.go:93] Enabling controller service capability: CREATE_DELETE_VOLUME
I0410 09:33:10.764529       1 driver.go:93] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
I0410 09:33:10.764532       1 driver.go:93] Enabling controller service capability: CREATE_DELETE_SNAPSHOT
I0410 09:33:10.764535       1 driver.go:93] Enabling controller service capability: EXPAND_VOLUME
I0410 09:33:10.764540       1 driver.go:112] Enabling volume access mode: SINGLE_NODE_WRITER
I0410 09:33:10.764546       1 driver.go:112] Enabling volume access mode: SINGLE_NODE_READER_ONLY
I0410 09:33:10.764549       1 driver.go:112] Enabling volume access mode: MULTI_NODE_READER_ONLY
I0410 09:33:10.764553       1 driver.go:112] Enabling volume access mode: MULTI_NODE_SINGLE_WRITER
I0410 09:33:10.764556       1 driver.go:112] Enabling volume access mode: MULTI_NODE_MULTI_WRITER
I0410 09:33:10.764560       1 driver.go:103] Enabling node service capability: STAGE_UNSTAGE_VOLUME
I0410 09:33:10.764564       1 driver.go:103] Enabling node service capability: GET_VOLUME_STATS
I0410 09:33:10.764725       1 server.go:118] Listening for connections on address: &net.UnixAddr{Name:"//csi/csi.sock", Net:"unix"}
I0410 09:33:11.182570       1 utils.go:118] GRPC call: /csi.v1.Identity/GetPluginInfo
I0410 09:33:11.182589       1 utils.go:119] GRPC request: {}
I0410 09:33:11.185280       1 utils.go:125] GRPC response: {"name":"file.csi.azure.com","vendor_version":"v1.1.0"}
I0410 09:33:11.630668       1 utils.go:118] GRPC call: /csi.v1.Identity/GetPluginInfo
I0410 09:33:11.630686       1 utils.go:119] GRPC request: {}
I0410 09:33:11.630763       1 utils.go:125] GRPC response: {"name":"file.csi.azure.com","vendor_version":"v1.1.0"}
I0410 09:33:12.094571       1 utils.go:118] GRPC call: /csi.v1.Node/NodeGetInfo
I0410 09:33:12.094592       1 utils.go:119] GRPC request: {}
I0410 09:33:12.094635       1 utils.go:125] GRPC response: {"node_id":"node01"}
I0410 10:21:42.662020       1 utils.go:118] GRPC call: /csi.v1.Node/NodeStageVolume
I0410 10:21:42.662041       1 utils.go:119] GRPC request: {"secrets":"***stripped***","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-azurefile/globalmount","volume_capability":{"AccessType":{"Mount":{"mount_flags":["dir_mode=0777","file_mode=0777","uid=0","gid=0","mfsymlinks","cache=strict","nosharesock"]}},"access_mode":{"mode":5}},"volume_context":{"resourceGroup":"kube","shareName":"paping","storageAccount":"testtool"},"volume_id":"unique-volumeid"}
W0410 10:21:42.662315       1 azurefile.go:477] parsing volumeID(unique-volumeid) return with error: error parsing volume id: "unique-volumeid", should at least contain two #
I0410 10:21:42.662326       1 azurefile.go:367] got storage account(testtool) from secret
I0410 10:21:42.662436       1 nodeserver.go:210] cifsMountPath(/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-azurefile/globalmount) fstype() volumeID(unique-volumeid) context(map[resourceGroup:kube shareName:paping storageAccount:testtool]) mountflags([dir_mode=0777 file_mode=0777 uid=0 gid=0 mfsymlinks cache=strict nosharesock]) mountOptions([dir_mode=0777 file_mode=0777 uid=0 gid=0 mfsymlinks cache=strict nosharesock vers=3.0 actimeo=30])
I0410 10:21:42.662486       1 mount_linux.go:146] Mounting cmd (mount) with arguments (-t cifs -o dir_mode=0777,file_mode=0777,uid=0,gid=0,mfsymlinks,cache=strict,nosharesock,vers=3.0,actimeo=30,<masked> //testtool.file.core.chinacloudapi.cn/paping /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-azurefile/globalmount)
E0410 10:22:02.777923       1 mount_linux.go:150] Mount failed: exit status 1
Mounting command: mount
Mounting arguments: -t cifs -o dir_mode=0777,file_mode=0777,uid=0,gid=0,mfsymlinks,cache=strict,nosharesock,vers=3.0,actimeo=30,<masked> //testtool.file.core.chinacloudapi.cn/paping /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-azurefile/globalmount
Output: mount error: could not resolve address for testtool.file.core.chinacloudapi.cn: Unknown error

Environment: 
1. self managed cluster running on VM in azure china E2 region
2. kubernetes version v1.19.8
3. docker version: 20.10.4
4. system: CentOS Linux 8

**Comment by andyzhangx** [comment]
the error said `could not resolve address for testtool.file.core.chinacloudapi.cn`, do you know whether `testtool.file.core.chinacloudapi.cn` exists?

**Comment by situzhiheng** [comment]
Sure, I have tried to mount it on the node, it's work.
![image](https://user-images.githubusercontent.com/30501125/114276672-45941980-9a5a-11eb-9dd2-5ca157fa7702.png)

**Comment by andyzhangx** [comment]
I think dns resolution in the driver daemonset is broken on that centos node:
```
k exec -it csi-azurefile-node-rpmg2 -c azurefile -n kube-system sh
# apt update && apt install dnsutils -y
# nslookup testtool.file.core.chinacloudapi.cn
Server:         10.0.0.10
Address:        10.0.0.10#53

Non-authoritative answer:
testtool.file.core.chinacloudapi.cn     canonical name = file.sha20prdstr01a.store.core.chinacloudapi.cn.
Name:   file.sha20prdstr01a.store.core.chinacloudapi.cn
Address: 40.73.81.72
```

**Comment by situzhiheng** [comment]
yes, it has worked again after re-install csi. But I still not understand why the driver broken suddenly.
