### ISSUE TITLE
azurefile-csi StorageClass not created

### ISSUE THREAD

**Issue by TaharInfo** [kubernetes-sigs/azurefile-csi-driver#632]
I want to enable csi-driver in my AKS cluster using the helm charts (v1.1.0) via Terraform, it creates the necessary pods (csi-azurefile-node and csi-azurefile-controller), but if I understand, it should create two additional StorageClasses : 
- `azurefile-csi`
- `azurefile-csi-premium`

This should be used in my `Persistent Volume Claim` to create automatically the PVs and storage accounts :
`storage_class_name = azurefile-csi` 

I tried to create my custom StorageClass using : 
`storage_provisioner   = "file.csi.azure.com"`
In this case, I was not able to create a PVC with this StorageClass.

Is it possible to enable CSI Driver on my AKS cluster using this repo ? 
or it's only possible with [AZ CLI for the moment](https://docs.microsoft.com/en-us/azure/aks/csi-storage-drivers#limitations)?
`--aks-custom-headers EnableAzureDiskFileCSIDriver=true`

I'm also referring to this doc : https://docs.microsoft.com/en-us/azure/aks/azure-files-csi#dynamically-create-azure-files-pvs-by-using-the-built-in-storage-classes

Thanks for your help

**Comment by andyzhangx** [comment]
you could install latest csi driver version using helm chart, while you still need to create the above two storage classes by your own.

**Comment by TaharInfo** [comment]
Thanks, it works.
