### ISSUE TITLE
add Pod Identity support

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azurefile-csi-driver#66]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

add support for [Pod Identity](https://github.com/Azure/aad-pod-identity) to enable finer grain scope of identity as an alternative to using the cluster’s identity.  We do see cases where Azure resources are closely associated with the cluster.  But we also see customers partitioning AKS clusters using namespaces, and in those cases it’s more likely that RBAC grants to resources like storage/key vault would be to Managed Identities that were scoped to a Kubernetes namespace. 

**Describe alternatives you've considered**

**Additional context**

**Comment by andyzhangx** [comment]
marked as long-term since in current stage, we don't want to depend on AAD pod identity component since AAD pod identity also depends on cluster identity, it would makes the deployment very complex in current stage.

**Comment by lukerogers** [comment]
I would love to see this feature. Right now we are using AAD Pod Identity for access in a multi-tenant cluster and will transition to [Azure Workload Identity](https://github.com/Azure/azure-workload-identity) when it's GA. I'm just adding my comment to show the value of this feature and say thanks for the awesome work being done here!

**Comment by nadworny** [comment]
Would also love to see it! ❤️

**Comment by andyzhangx** [comment]
> Us too. It's silly that we have to use keys that are being phased out when this should just work with managed identities.

@JohnGalt1717 there is `storeAccountKey` in storage class, you could set as `"false"` , by that way, account key won't be stored as k8s secret, and agent node would use kubelet identity to get account key directly during mount.

Name | Meaning | Example | Mandatory | Default value 
--- | --- | --- | --- | ---
storeAccountKey | whether store account key to k8s secret <br><br> Note:  <br> `false` means driver would leverage kubelet identity to get account key | `true`,`false` | No | `true`

**Comment by JohnGalt1717** [comment]
I tried that, but it still threw an error if the secret doesn't exist.  If I provide storageAccount and and storeAccountKey = false, then it shouldn't check for anything and should be using MI.  In my experience trying these, that isn't what happens.  And in fact, what it should be doing, is using MI if the secretName property isn't set.
