### ISSUE TITLE
Host OS can't find files in mount NFS 

### ISSUE THREAD

**Issue by beaverdevtools** [kubernetes-sigs/azurefile-csi-driver#665]
Hello All,

I created a StorageClass, PVs and PVCs, on an AzureFile NFS share by following this tutorial: https://github.com/kubernetes-sigs/azurefile-csi-driver/tree/master/deploy/example/nfs

 It works great on PHP-FPM pods, but it looks like there is a latency or indexing issue.
On my PHP app (Magento2) I create a product and add an image. Product created and image uploaded to the php pod in nfs mount directory with no issue until the php application is trying a chmod() on the file.

In Magento logs, the exception is that php is unable to find the file.

Into the php pod Shell if I copy paste the file Path, I can't find the file, but if I use tab to type the path on my command, I can chmod or whatever on the file.

It's like the host OS have no idea of the existent into the NFS mount, it can access it and interact with it but until the host os hasn't gone throuth directories, it can't see beyond. 

Is that a normal behaviour ?  How can I force indexing/discover ?

thanks in advance

I'm using a premium FS using NFS.
K8s 1.19.9 + csi driver v1.2 
pod is running a custom php:7.4-fpm docker.

**Comment by RenaShahMSFT** [comment]
Hi @beaverdevtools  - I am the product manager on Azure FIles NFS. We can look into your issue. Could you please pm me your account details and repro timestamp at rena[dot]shag[at]microsoft[dot]com

**Comment by beaverdevtools** [comment]
Hello @RenaShahMSFT  , thank you for your proposal, but I think I sent my support question in the wrong place. My bad.
Never the less, last week I managed to make my php app work using azurefile nfs shares. The php command chmod() was working great but since wednesday, i had to move from NFS to standard azureFile, because of this "chmod() file not found issue". Did something changed this week on the Azure side ? Because I didn't do anything it just stopped working out of the blue.  anyway thanks again :)

**Comment by RenaShahMSFT** [comment]
@beaverdevtools in case you still have the repro of this issue, please drop me a line. We would love to investigate and get a root cause of this issue.
