### ISSUE TITLE
remove azure.json dependency in node server

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azurefile-csi-driver#67]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

Currently driver depends on azure.json to get storage account key, need to remove this dependency

https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/938e19f4df57ace8448463c6d06e8f67b791d0f8/pkg/azurefile/nodeserver.go#L93

**Describe alternatives you've considered**

**Additional context**

**Comment by andyzhangx** [comment]
Update:
Need to write the storage account key into a k8s secret, here the blocking issue how to get kube client inside CSI driver, it's easy in built-in driver by `volume.VolumeHost.GetKubeClient()`

**Comment by ashishranjan738** [comment]
I would like to work on this @andyzhangx

**Comment by andyzhangx** [comment]
I am still investigating this issue, now it depends on CSI driver to get a kubeconfig which may be not a good idea now:
https://github.com/kubernetes-csi/cluster-driver-registrar/blob/9f072c9b88e27497ecf5c062f3b9dc55121694ce/cmd/csi-cluster-driver-registrar/main.go#L49

**Comment by ashishranjan738** [comment]
ok

**Comment by andyzhangx** [comment]
this issue is also related to https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/333
now when in-tree azure file driver creates an azure file volume, it would store azure storage account secret to a k8s secret naming as `azure-storage-account-{accountname}-secret`, we need to use same way as in-tree driver, related code is here: 
https://github.com/kubernetes/kubernetes/blob/a256498ba4e651ca0a3741707b4f5579a77e60ef/pkg/volume/azure_file/azure_provision.go#L193-L197

```
# k get secret
NAME                                                   TYPE                                  DATA   AGE
azure-storage-account-f3382f23a515e11ea9942e6-secret   Opaque                                2      40d
```

@ZeroMagic could you take a look? Thanks.

**Comment by andyzhangx** [comment]
Current plan is we are still going to store account key to k8s secret by default(same behavior as built-in driver), and there is a switch(`storeAccountKey`, by default `true`) to turn off this behavior, and user should make sure identity on agent node have read access to the storage account if turn off
