### ISSUE TITLE
Kubernetes Pods lose connection after Azure Storage Account Failover.

### ISSUE THREAD

**Issue by vlaguduva** [kubernetes-sigs/azurefile-csi-driver#673]
**Is your feature request related to a problem?/Why is this needed**

Pods are connected to a Azure Storage Account (with RA-GRS replication) one region; when the failover occurred on that storage account to move the corresponding replication, pods lost the connectivity; Error message received is "Host is down."
**Describe the solution you'd like in detail**
Pods should reconnect automatically.

**Describe alternatives you've considered**
Restart the pods connected to that storage account..

**Additional context**
MS TrackingID#210415006000418

**Comment by andyzhangx** [comment]
The original issue would be solved by Kernel `5.4.0-1049-azure` (latest node image kernel: `5.4.0-1055-azure`), it has the SMB client fix for an issue in DNS resolution after Azure files storage failover, using private-link (only supported in Azure File CSI driver) would also solve this issue.

duplicated to https://github.com/Azure/AKS/issues/2289
