### ISSUE TITLE
Volume mount fails as it looks for secret in default namespace

### ISSUE THREAD

**Issue by jmajoor** [kubernetes-sigs/azurefile-csi-driver#680]
I use an azureFile volume mount, that suddenly fails after migration to AKS 1.19 (from 1.18).

My volume definition specifies a secretName, which is located in the same namespace as the pod requiring this volume.
However I am now getting an error that it can't find `default/<secret name>`.

There is some mentioning of a secretNamespace field, but in io.k8s.api.core.v1.AzureFileVolumeSource there is no such field.

So it seems that it used to look in the same namespace, but now it is explicitly looking in the default namespace and I can't specify the secretNamespace as that field doesn't exist on the AzureFileVolumeSource API.

Documentation from k8s:
```
secretNamespace: the namespace of the secret that contains the Azure Storage Account Name and Key. Default is the same as the Pod.
```
I don't define a namespace and therefore expect it to be the same as the pod, which used to work.

**Comment by andyzhangx** [comment]
related to this issue: https://github.com/Azure/AKS/issues/2108#issuecomment-849619104, pls check whether the fixed version has been rolled out to your region, thanks.
fixed versions(`1.21.1`, `1.20.7`, `1.19.11`, `1.18.19`)

**Comment by andyzhangx** [comment]
```
# az aks get-versions -l eastus -o table
The behavior of this command has been altered by the following extension: aks-preview
KubernetesVersion    Upgrades
-------------------  ------------------------
1.21.1(preview)      None available
1.20.7               1.21.1(preview)
1.20.5               1.20.7, 1.21.1(preview)
1.19.11              1.20.5, 1.20.7
1.19.9               1.19.11, 1.20.5, 1.20.7
1.18.19              1.19.9, 1.19.11
1.18.17              1.18.19, 1.19.9, 1.19.11
```

**Comment by jmajoor** [comment]
Thanks for the quick response. Sorry I didn't notice that it had already been reported.
This was in westus2, which unfortunately doesn't have the fix yet, but hopefully soon (will work around it until then).
