### ISSUE TITLE
Change node tolerations

### ISSUE THREAD

**Issue by Flowman** [kubernetes-sigs/azurefile-csi-driver#695]
**Is your feature request related to a problem?/Why is this needed**

It would be good if we could change tolerations for the csi-azurefile-node.yaml. As is would be nice to control if it should be created on a master node or not, where it will never be used.

https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/780e01bbb7e4891bc8cce0289f26e69facaad5b8/charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml#L33

- operator: "Exists" installs on all server in the cluster.

**Describe the solution you'd like in detail**

Add a chart value to change tolerations for nodes.

**Comment by andyzhangx** [comment]
thanks, that would be a nice to have feature.

**Comment by andyzhangx** [comment]
added this new feature in v1.4.0
