### ISSUE TITLE
updating azure file csi driver to 1.3.0

### ISSUE THREAD

**Issue by mmillard0** [kubernetes-sigs/azurefile-csi-driver#696]
**What happened**:
When I try to update azure file csi driver to 1.3.0 version, I receive an error updating csi-azurefile-driver.yaml 

raised error:
##[error]The CSIDriver "file.csi.azure.com" is invalid: spec: Invalid value: storage.CSIDriverSpec{AttachRequired:(*bool)(0xc0099129b8), FSGroupPolicy:(*storage.FSGroupPolicy)(0xc00a5c76e0), PodInfoOnMount:(*bool)(0xc0099129b9), VolumeLifecycleModes:[]storage.VolumeLifecycleMode{"Persistent", "Ephemeral"}, StorageCapacity:(*bool)(nil), TokenRequests:[]storage.TokenRequest(nil), RequiresRepublish:(*bool)(nil)}: field is immutable

Can you explain how to update to azure file csi driver version 1.3.0 ?

**What you expected to happen**:
Resource CSIDriver named file.csi.azure.com is updated successfully.

**How to reproduce it**:
use a cluster with azure file csi driver v1.0.0 plugin installed. 

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: v1.0.0 to v1.3.0
- Kubernetes version (use `kubectl version`):Kubectl Client Version: v1.21.1, Kubectl Server Version: v1.20.7 
- OS (e.g. from /etc/os-release): AKSUbuntu-1804gen2containerd-2021.05.19
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

Regards

**Comment by andyzhangx** [comment]
```
kubectl delete CSIDriver file.csi.azure.com
kubectl create -f https://github.com/kubernetes-sigs/azurefile-csi-driver/blame/master/deploy/v1.3.0/csi-azurefile-driver.yaml
```

**Comment by mmillard0** [comment]
Ok, thank for your quick answer.
That's what I have done in my lab cluster but I wanted to be sure that it doesn't have impacts for my other clusters (dev, tst, acc and prd). Could you confirm that uninstall the csi driver won't impact my production cluster during the deployment (We are using azure devops to deploy) ?

**Comment by andyzhangx** [comment]
> Ok, thank for your quick answer.
> That's what I have done in my lab cluster but I wanted to be sure that it doesn't have impacts for my other clusters (dev, tst, acc and prd). Could you confirm that uninstall the csi driver won't impact my production cluster during the deployment (We are using azure devops to deploy) ?

@mmillard0 if you don't have azure file volume mounting/unmounting at that time, there is no impact if you uninstall csi driver, existing azure file mount is still valid.
