### ISSUE TITLE
I cannot create a PV dynamically without a cloud provider config file

### ISSUE THREAD

**Issue by Schildkroete23** [kubernetes-sigs/azurefile-csi-driver#710]
**What happened**:
I want to generate a PV dynamically without providing a cloud provider config file.  For this I provided a secret with the credentials of an exisiting Storage Account in Azure as describe [here](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/deploy/example/e2e_usage.md#option2-bring-your-own-storage-account). Unfortunately I got the following error message from the CSI Controller
`utils.go:123] GRPC error: rpc error: code = Internal desc = error creating azure client: azure: base storage service url required`
and the PV is not getting created.

**What you expected to happen**:
A PV should be dynamically created without a cloud provider config file when I provide a Storage Account as described [here](https://github.com/kubernetes-sigs/azurefile-csi-driver#option2-bring-your-own-storage-account).

**How to reproduce it**:
Just follow the steps described in the documentation ["Option#2: bring your own storage account"](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/deploy/example/e2e_usage.md#option2-bring-your-own-storage-account) without an existing cloud provider config file.

**Anything else we need to know?**:
I had a quick look into the code. Unfortunately, I'm not very familiar with GO. But as far as I understand the base URL is set with "[f.env.StorageEndpointSuffix](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/b5dacb53e2c049f710450e94d78bcf88b50897b0/pkg/azurefile/azurefile_client.go#L111)". And as far as I can see there is no way to set this value with a driver parameter.

**Environment**:
- CSI Driver version: 1.4.0
- Kubernetes version (use `kubectl version`): 1.18.10
- OS (e.g. from /etc/os-release): Ubuntu 20.04.1 LTS
- Kernel (e.g. `uname -a`): 5.4.0-72-generic
- Install tools: helm
- Others: /

Thanks for providing this driver and for your help!

**Comment by andyzhangx** [comment]
thanks, I fixed in master branch now

**Comment by Schildkroete23** [comment]
Thanks heaps Andy!
