### ISSUE TITLE
Update docs for NFS on ARO

### ISSUE THREAD

**Issue by ezYakaEagle442** [kubernetes-sigs/azurefile-csi-driver#718]
a correct SC using Azure Storage Private-Endpoint looks like this :
```sh
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-nfs
provisioner: file.csi.azure.com
parameters:
  resourceGroup: $RESOURCE_GROUP
  storageAccount: $STORAGE_ACCOUNT_NAME
  shareName: $SHARE_NAME
  server: $STORAGE_ACCOUNT_NAME.privatelink.file.core.windows.net
  protocol: nfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
```
The Driver parameters [doc](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/driver-parameters.md) refer only to PV, this is confusing.

Also when creating the Storage Acccount + FileShare **before** creating the SC, PVC and Pod in K8S ( tested with ARO), the deployment fails with 
 
Warning ProvisioningFailed 32s file.csi.azure.com_aro-azarc-101-r92cr-worker-francecentral2-7ddb9_37620af3-c7ba-445e-baf4-a7d0bb3c443c failed to provision volume with StorageClass "azurefile-csi-nfs": rpc error: code = Unknown desc = **failed to create file share(arofs) on account(stfrfileazarc) type(Premium_LRS) rg(rg-azarc-aro-francecentral) location() size(100),** error: storage.FileSharesClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidHeaderValue" Message="**The value for one of the HTTP headers is not in the correct format.\**nRequestId:53036019-d01a-0097-6416-68b3d0000000\nTime:2021-06-23T09:58:36.2578220Z"
Normal ExternalProvisioning 4s (x6 over 66s) persistentvolume-controller waiting for a volume to be created, either by external provisioner "file.csi.azure.com" or manually created by system administrator
Normal Provisioning 0s (x7 over 66s) file.csi.azure.com_aro-azarc-101-r92cr-worker-francecentral2-7ddb9_37620af3-c7ba-445e-baf4-a7d0bb3c443c External provisioner is provisioning volume for claim "default/persip

@andyzhangx

**Comment by ezYakaEagle442** [comment]
Also regarding Azure Cloud Config : 


azure-cloud-provider.yaml template : 
```sh
apiVersion: v1
data:
  cloud-config: ${AZURE_CLOUD_SECRET}
kind: Secret
metadata:
  name: azure-cloud-provider
  namespace: kube-system
type: Opaque
```

**/!\ IMPORTANT** : 
- the resourceGroup is the ARO Cluster RG
- both resourceGroup **AND** vnetResourceGroup must be specified
- vnetName **AND** subnetName  must be specified

```sh


cat <<EOF >> aml/deploy/cloud.conf
{
"tenantId": "$tenantId",
"subscriptionId": $subId,
"resourceGroup" : "$aro_rg_name", 
"vnetResourceGroup": "$aro_rg_name",
"vnetName": "$aro_vnet_name",
"subnetName": "$aro_worker_subnet_name",
"useManagedIdentityExtension": false,
"aadClientId": "$aadClientId",
"aadClientSecret": "$aadClientSecret"
}
EOF

cat aml/deploy/cloud.conf
export AZURE_CLOUD_SECRET=`cat aml/deploy/cloud.conf | base64 | awk '{printf $0}'; echo`
envsubst < ./aml/azure-cloud-provider.yaml > aml/deploy/azure-cloud-provider.yaml

cat aml/deploy/azure-cloud-provider.yaml
oc apply -f ./aml/deploy/azure-cloud-provider.yaml
```

**Comment by ezYakaEagle442** [comment]
Also, the doc should descibe the required Role : 
```sh
#  configure ARO SPN to access that storage account
# Role to be tested : Reader, Storage File Data SMB Share Reader, Storage Account Contributor
az role assignment create --assignee $aadClientId --scope $str_acc_id  --role Contributor
```

**Comment by andyzhangx** [comment]
what's your input value of 
```
parameters:
  resourceGroup: $RESOURCE_GROUP
  storageAccount: $STORAGE_ACCOUNT_NAME
  shareName: $SHARE_NAME
```

and is account(`stfrfileazarc`) in rg(`rg-azarc-aro-francecentral`) ?
@ezYakaEagle442

**Comment by ezYakaEagle442** [comment]
Hi @andyzhangx ,

I have fixed the issue :in the Cloud config  : , as the the resourceGroup should be the ARO Cluster MANAGED RG. ( aro-elvkhpbs in my case, not the RG I created rg-azarc-aro-francecentral).

I have also successfully tested the NFS sample using a Private-Endpoint , the [snippet is on my repo](https://github.com/ezYakaEagle442/azure-arc/blob/master/setup-aro.md#csi-pre-req).
