### ISSUE TITLE
Inline mount as cluster identity

### ISSUE THREAD

**Issue by jabbera** [kubernetes-sigs/azurefile-csi-driver#726]
I'd like to be able to use the cluster identity for inline mounts. I'm being forced to specify the account key in a secret which is not ideal IMO.

**Comment by andyzhangx** [comment]
inline volume only supports reading account key from secret in **same** namespace, it does not support cluster identity, that's by design, otherwise that's a security hole that one pod in one namespace could access any storage account that current cluster identity could access.

**Comment by jabbera** [comment]
Thanks!
