### ISSUE TITLE
MountVolume.SetUp failed : special device /var/lib/kubelet/plugins/kubernetes.io/csi/pv/xxxxx/globalmount does not exist

### ISSUE THREAD

**Issue by mmillard0** [kubernetes-sigs/azurefile-csi-driver#731]
**What happened**:
We have a deployment of 3 pods for high availability (using TopologySpead Constraints), one pod on each zone (we have 3 zones).
Pods states:
<pre><code>NAME                                 STATUS
wso2ei-deployment-8688d6d4df-xw47d   Pending
wso2ei-deployment-8688d6d4df-l7xbr   Running
wso2ei-deployment-8688d6d4df-pffzp   Running</code></pre>

One of the pods stays in pending state with error message:
<pre>
<code>Warning  FailedMount        2m26s (x38 over 77m)  kubelet             MountVolume.SetUp failed for volume "pvc-ac70056e-0663-406f-8166-4364cdc24793" : rpc error: code = Internal desc = Could not mount "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-ac70056e-0663-406f-8166-4364cdc24793/globalmount" at "/var/lib/kubelet/pods/71e52ff5-de96-4465-9ffb-e7021cade2c3/volumes/kubernetes.io~csi/pvc-ac70056e-0663-406f-8166-4364cdc24793/mount": mount failed: exit status 32
Mounting command: mount
Mounting arguments:  -o bind /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-ac70056e-0663-406f-8166-4364cdc24793/globalmount /var/lib/kubelet/pods/71e52ff5-de96-4465-9ffb-e7021cade2c3/volumes/kubernetes.io~csi/pvc-ac70056e-0663-406f-8166-4364cdc24793/mount
Output: mount: /var/lib/kubelet/pods/71e52ff5-de96-4465-9ffb-e7021cade2c3/volumes/kubernetes.io~csi/pvc-ac70056e-0663-406f-8166-4364cdc24793/mount: special device /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-ac70056e-0663-406f-8166-4364cdc24793/globalmount does not exist.</code>
</pre>

PVC detail:
<pre><code>NAME                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                 AGE
wso2ei-deploy-pv-claim   Bound    pvc-ac70056e-0663-406f-8166-4364cdc24793   5Ti        RWX            filecsi-aks-tst-wso2ei-car   135d</code></pre>

We are using a storageClass (with parameters resourcesGroup, shareName and storageAccount):
<pre><code>NAME                         PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
filecsi-aks-tst-wso2ei-car   file.csi.azure.com   Retain          Immediate           true                   481d</code></pre>

**What you expected to happen**:
3 pods running (one in each zone) with no mounting errors.

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: 1.4.0
- Kubernetes version (use `kubectl version`): Kubectl Client Version: v1.21.1, Kubectl Server Version: v1.20.7
- OS (e.g. from /etc/os-release): AKSUbuntu-1804gen2containerd-2021.05.19
- Kernel (e.g. `uname -a`):
- Install tools:
- Others: K8s version 1.20.7

Regards

**Comment by andyzhangx** [comment]
does this issue still repro? If yes, pls provide driver logs on that node by: https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/csi-debug.md#case2-volume-mountunmount-failed, it may be related to this similar issue: https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/620, which is caused by volumeid conflict between two PVs.
