### ISSUE TITLE
Ephemeral mounts causing pod startup delay

### ISSUE THREAD

**Issue by jabbera** [kubernetes-sigs/azurefile-csi-driver#732]
**What happened**: 2 minute delay starting pod when using ephemeral mount

**What you expected to happen**: No delay

**How to reproduce it**: Use ephemeral mount with this configuration:

```
            "name": USER_HOME_NAME,
            "csi": {
                "driver": "file.csi.azure.com",
                "volumeAttributes": {
                   "shareName": "user",
                   "resourceGroup": self.userStorageResourceGroup,
                   "storageAccount": self.userStorageAccount,
                   "mountOptions": f"dir_mode=0700,file_mode=0700,uid={spawner.environment['NB_UID']},gid={spawner.environment['NB_GID']},mfsymlinks,cache=strict,nosharesock,actimeo=30,nobrl"
                }
            }
        }
```

**Anything else we need to know?**:

Notice 2 minute delay in log!

```
I0707 14:13:38.142451       1 utils.go:118] GRPC call: /csi.v1.Node/NodePublishVolume
I0707 14:13:38.142473       1 utils.go:119] GRPC request: {"target_path":"/var/lib/kubelet/pods/7c655ce9-52cb-4baf-8db2-743aea9de34d/volumes/kubernetes.io~csi/user-home/mount","volume_capability":{"AccessType":{"Mount":{}},"access_mode":{"mode":1}},"volume_context":{"csi.storage.k8s.io/ephemeral":"true","csi.storage.k8s.io/pod.name":"jupyter-mbarry","csi.storage.k8s.io/pod.namespace":"jhub","csi.storage.k8s.io/pod.uid":"7c655ce9-52cb-4baf-8db2-743aea9de34d","csi.storage.k8s.io/serviceAccount.name":"default","mountOptions":"dir_mode=0700,file_mode=0700,uid=<SNIP>,gid=1000,mfsymlinks,cache=strict,nosharesock,actimeo=30,nobrl","resourceGroup":"<SNIP>","shareName":"user","storageAccount":"<SNIP>"},"volume_id":"csi-ea6fb36f84d865bd17d7cde4b6d12ecae556ec7e9ad652fa49032a42e19c29af"}
I0707 14:13:38.142642       1 nodeserver.go:63] NodePublishVolume: ephemeral volume(csi-ea6fb36f84d865bd17d7cde4b6d12ecae556ec7e9ad652fa49032a42e19c29af) mount on /var/lib/kubelet/pods/7c655ce9-52cb-4baf-8db2-743aea9de34d/volumes/kubernetes.io~csi/user-home/mount, VolumeContext: map[csi.storage.k8s.io/ephemeral:true csi.storage.k8s.io/pod.name:jupyter-<SNIP> csi.storage.k8s.io/pod.namespace:jhub csi.storage.k8s.io/pod.uid:7c655ce9-52cb-4baf-8db2-743aea9de34d csi.storage.k8s.io/serviceAccount.name:default getaccountkeyfromsecret:true mountOptions:dir_mode=0700,file_mode=0700,uid=<SNIP>,gid=1000,mfsymlinks,cache=strict,nosharesock,actimeo=30,nobrl resourceGroup:<SNIP> secretnamespace:jhub shareName:user storageAccount:<SNIP> storageaccount:]
W0707 14:13:38.142680       1 azurefile.go:476] parsing volumeID(csi-ea6fb36f84d865bd17d7cde4b6d12ecae556ec7e9ad652fa49032a42e19c29af) return with error: error parsing volume id: "csi-ea6fb36f84d865bd17d7cde4b6d12ecae556ec7e9ad652fa49032a42e19c29af", should at least contain two #
E0707 14:13:38.142708       1 utils.go:123] GRPC error: rpc error: code = InvalidArgument desc = failed to get account name from csi-ea6fb36f84d865bd17d7cde4b6d12ecae556ec7e9ad652fa49032a42e19c29af
I0707 14:15:40.230612       1 utils.go:118] GRPC call: /csi.v1.Node/NodePublishVolume
```

**Environment**:
- CSI Driver version: 1.4.0
- Kubernetes version (use `kubectl version`): AKS 1.20.5
- OS (e.g. from /etc/os-release): Whatever AKS uses
- Kernel (e.g. `uname -a`): Whatever AKS uses
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
the csi inline volume only supports following 3 parameters in `volumeAttributes`, it actually ignores the other parameters, could you try `secretName` instead:
https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/05db0f7cffb0494cedf013f80c716e756b40be97/deploy/example/nginx-pod-azurefile-inline-volume.yaml#L21-L26

**Comment by jabbera** [comment]
@andyzhangx I don't understand. I can't specify a storage account? Does that mean this only works with the managed storage account?

It works BTW, just has the crazy delay.

**Comment by andyzhangx** [comment]
> @andyzhangx I don't understand. I can't specify a storage account? Does that mean this only works with the managed storage account?
> 
> It works BTW, just has the crazy delay.

@jabbera did you have the complete `/NodePublishVolume` node driver logs? I don't think it would work.
I will propose a PR to forbid other fields in inline volume parameter list.

**Comment by jabbera** [comment]
I'll send them tomorrow. Please dont! I still don't understand why you would want to restrict this feature to the managed storage account by aks. Why can't I specify an arbitrary storage account? We don't use the managed account for anything so we can delete and recreate the cluster as needed. Storing persistent data in that account would be bad for us.

**Comment by andyzhangx** [comment]
`azure-secret` should be created by user and the storage account should be managed by user also.
There is a security issue if user could just specify a storage account in pod config, storage account could only be specified by storage class or PV which is managed by admin.

```console
kubectl create secret generic azure-secret --from-literal=azurestorageaccountname="xxx" --from-literal azurestorageaccountkey="xxx" --type=Opaque
```

**Comment by jabbera** [comment]
I need forgetting the account can be in the secret. Will try today.

**Comment by andyzhangx** [comment]
let me know if there is still issue, close it for now.

**Comment by rlaveycal** [comment]
Just a note for future readers. Because the driver caches access keys the inline option will work if you specify `storageAccount` as long as the access keys have been retrieved by a previous PV creation.
