### ISSUE TITLE
Make sure this driver works on OpenShift

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azurefile-csi-driver#74]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like in detail**

This driver requires k8s v1.13.x, so need to make sure OpenShift supports v1.13.x first.

**Describe alternatives you've considered**

**Additional context**

**Comment by ashishranjan738** [comment]
ahh i think openshift 4.1 supports 1.13.x as i am having a dev cluster of openshift. output ```[aranjan@localhost:~]$ oc get nodes
NAME                           STATUS   ROLES    AGE   VERSION
ip-10-0-136-255.ec2.internal   Ready    master   13h   v1.13.4+cb455d664
ip-10-0-137-68.ec2.internal    Ready    worker   13h   v1.13.4+cb455d664
ip-10-0-146-134.ec2.internal   Ready    worker   13h   v1.13.4+cb455d664
ip-10-0-146-209.ec2.internal   Ready    master   13h   v1.13.4+cb455d664
ip-10-0-173-184.ec2.internal   Ready    master   13h   v1.13.4+cb455d664
ip-10-0-173-208.ec2.internal   Ready    worker   13h   v1.13.4+cb455d664
```
