### ISSUE TITLE
[openshift] oc get pv / pvc shows wrong capacity

### ISSUE THREAD

**Issue by gmcbrien** [kubernetes-sigs/azurefile-csi-driver#774]
**What happened**:

We deployed a PV using azurefile-csi driver, which dynamically provisioned a new Azure 'File Share' of size 600Gi. The underlying PV was also provisioned.
Due to space constraints, we had to resize this to 1 Terabyte. This was done by editing the PVC directly, using oc edit, and entering 1Ti.

```
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Ti <---
  storageClassName: azurefile-csi
  volumeMode: Filesystem
  volumeName: pvc-12345678...
```

The fileshare in Azure portal reflects the new 1Ti size. The filesystem in the pod also shows the new size of 1Ti
But, with an `oc get pvc / pv` it shows as capacity of 1Ki. I also get repeating 'resize volume succeeded' messages in the `oc describe pvc`

```
❯ oc get pvc
NAME                     STATUS   VOLUME            CAPACITY   ACCESS MODES   STORAGECLASS      AGE
elasticsearch-backup     Bound    pvc-12345678...   1Ki        RWX            azurefile-csi     62d
```

Description of the PVC also shows the incorrect capacity
```
❯ oc describe pvc elasticsearch-backup
Name:          elasticsearch-backup
Namespace:     openshift-logging
StorageClass:  azurefile-csi
Status:        Bound
Volume:        pvc-12345678...
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: file.csi.azure.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      1Ki
Access Modes:  RWX
VolumeMode:    Filesystem
Mounted By:    elasticsearch-bkp-job-vfbdj
               elasticsearch-snapshots-manage-1629855900-ddzwq
Events:
  Type    Reason                  Age                    From                                 Message
  ----    ------                  ----                   ----                                 -------
  Normal  Resizing                107s (x446 over 3d2h)  external-resizer file.csi.azure.com  External resizer is resizing volume pvc-12345678...
  Normal  VolumeResizeSuccessful  107s (x446 over 3d2h)  external-resizer file.csi.azure.com  Resize volume succeeded
```
Extract from the azurefile-csi container logs. This error appears every 10 minutes. (PVC and UID redacted):

```
I0825 07:33:28.787696       1 connection.go:182] GRPC call: /csi.v1.Controller/ControllerExpandVolume
I0825 07:33:28.787719       1 connection.go:183] GRPC request: {"capacity_range":{"required_bytes":1099511627776},"volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":5}},"volume_id":"m-e-1-cluster-gtb2x-rg#cluster8wpvd#pvc-1111111-111111-1111171e5#"}
I0825 07:33:28.788990       1 event.go:281] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"openshift-logging", Name:"elasticsearch-backup", UID:"1111111-111111-1111171e5", APIVersion:"v1", ResourceVersion:"193930939", FieldPath:""}): type: 'Normal' reason: 'Resizing' External resizer is resizing volume pvc-1111111-111111-1111171e5
I0825 07:33:29.137183       1 connection.go:185] GRPC response: {"capacity_bytes":1024}
I0825 07:33:29.137537       1 connection.go:186] GRPC error: <nil>
I0825 07:33:29.137545       1 controller.go:364] Resize volume succeeded for volume "pvc-1111111-111111-1111171e5", start to update PV's capacity
I0825 07:33:29.144725       1 controller.go:370] Update capacity of PV "pvc-1111111-111111-1111171e5" to 1Ki succeeded
I0825 07:33:29.156367       1 controller.go:399] Resize PVC "openshift-logging/elasticsearch-backup" finished
I0825 07:33:29.156646       1 event.go:281] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"openshift-logging", Name:"elasticsearch-backup", UID:"1111111-111111-1111171e5", APIVersion:"v1", ResourceVersion:"193930939", FieldPath:""}): type: 'Normal' reason: 'VolumeResizeSuccessful' Resize volume succeeded
I0825 07:40:28.712774       1 leaderelection.go:283] successfully renewed lease kube-system/external-resizer-file-csi-azure-com
I0825 07:40:33.730886       1 leaderelection.go:283] successfully renewed lease kube-system/external-resizer-file-csi-azure-com
I0825 07:40:38.786959       1 leaderelection.go:283] successfully renewed lease kube-system/external-resizer-file-csi-azure-com
...
...
```

**What you expected to happen**:

I would expect the `oc get pvc` to reflect the correct size and only a one-time 'resize' log entry.

**How to reproduce it**:

Already outlined above, which I *believe* is in line with the resizing guide [here ](https://github.com/kubernetes-sigs/azurefile-csi-driver/tree/master/deploy/example/resize)

**Anything else we need to know?**:
* In general, everything works fine, just the size is wrongly reported. 
* This is an Openshift environment
* Rolling restart of the csi-azurefile-controller deployment didn't help

**Environment**:
- CSI Driver version: 
```
k8s/csi/azurefile-csi:v0.9.0
```
- Kubernetes version (use `kubectl version`):
```
Client Version: 4.6.21
Server Version: 4.7.18
Kubernetes Version: v1.20.0+87cc9a4
```
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by andyzhangx** [comment]
looks like it's a display issue with `oc` command since underlying size `"required_bytes":1099511627776` is passed and handled correctly. What about `kubectl describe pvc elasticsearch-backup` command?

**Comment by gmcbrien** [comment]
`kubectl describe pvc elasticsearch-backup` produces the same result as above (`Capacity:  1Ki`)

I also updated my `oc` client  to 4.7.13. No change there either.

**Comment by gmcbrien** [comment]
Further update:  I see various errors in the pods as below, with repeating errors concerning 'failed to acquire lease'

```
csi-azurefile-controller-579d6bf79-7qnj7 csi-provisioner I0825 08:59:42.548560       1 leaderelection.go:350] lock is held by m-e-1-cluster-gtb2x-worker-weurope-standard-e-4as-v4-2-pdrd9 and has not yet expired
csi-azurefile-controller-579d6bf79-7qnj7 csi-provisioner I0825 08:59:42.548587       1 leaderelection.go:246] failed to acquire lease kube-system/file-csi-azure-com
csi-azurefile-controller-579d6bf79-7qnj7 csi-attacher I0825 08:59:42.669965       1 leaderelection.go:352] lock is held by m-e-1-cluster-gtb2x-worker-weurope-standard-e-4as-v4-2-pdrd9 and has not yet expired
csi-azurefile-controller-579d6bf79-7qnj7 csi-attacher I0825 08:59:42.669986       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
csi-azurefile-controller-579d6bf79-7qnj7 csi-resizer I0825 08:59:44.392463       1 leaderelection.go:352] lock is held by m-e-1-cluster-gtb2x-worker-weurope-standard-e-4as-v4-2-pdrd9 and has not yet expired
csi-azurefile-controller-579d6bf79-7qnj7 csi-resizer I0825 08:59:44.392487       1 leaderelection.go:247] failed to acquire lease kube-system/external-resizer-file-csi-azure-com
csi-azurefile-controller-579d6bf79-7qnj7 csi-snapshotter I0825 08:59:45.152929       1 leaderelection.go:352] lock is held by m-e-1-cluster-gtb2x-worker-weurope-standard-e-4as-v4-2-pdrd9 and has not yet expired
csi-azurefile-controller-579d6bf79-7qnj7 csi-snapshotter I0825 08:59:45.152973       1 leaderelection.go:247] failed to acquire lease kube-system/external-snapshotter-leader-file-csi-azure-com
csi-azurefile-controller-579d6bf79-7qnj7 csi-attacher I0825 08:59:50.920755       1 leaderelection.go:352] lock is held by m-e-1-cluster-gtb2x-worker-weurope-standard-e-4as-v4-2-pdrd9 and has not yet expired
csi-azurefile-controller-579d6bf79-7qnj7 csi-attacher I0825 08:59:50.920785       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
csi-azurefile-controller-579d6bf79-7qnj7 csi-resizer I0825 08:59:52.645733       1 leaderelection.go:352] lock is held by m-e-1-cluster-gtb2x-worker-weurope-standard-e-4as-v4-2-pdrd9 and has not yet expired
csi-azurefile-controller-579d6bf79-7qnj7 csi-resizer I0825 08:59:52.645751       1 leaderelection.go:247] failed to acquire lease kube-system/external-resizer-file-csi-azure-com
csi-azurefile-controller-579d6bf79-7qnj7 csi-provisioner I0825 08:59:53.268596       1 leaderelection.go:350] lock is held by m-e-1-cluster-gtb2x-worker-weurope-standard-e-4as-v4-2-pdrd9 and has not yet expired
```

**Comment by andyzhangx** [comment]
> Further update: I see various errors in the pods as below, with repeating errors concerning 'failed to acquire lease'
> 
> ```
> csi-azurefile-controller-579d6bf79-7qnj7 csi-provisioner I0825 08:59:42.548560       1 leaderelection.go:350] lock is held by m-e-1-cluster-gtb2x-worker-weurope-standard-e-4as-v4-2-pdrd9 and has not yet expired
> csi-azurefile-controller-579d6bf79-7qnj7 csi-provisioner I0825 08:59:42.548587       1 leaderelection.go:246] failed to acquire lease kube-system/file-csi-azure-com
> csi-azurefile-controller-579d6bf79-7qnj7 csi-attacher I0825 08:59:42.669965       1 leaderelection.go:352] lock is held by m-e-1-cluster-gtb2x-worker-weurope-standard-e-4as-v4-2-pdrd9 and has not yet expired
> csi-azurefile-controller-579d6bf79-7qnj7 csi-attacher I0825 08:59:42.669986       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
> csi-azurefile-controller-579d6bf79-7qnj7 csi-resizer I0825 08:59:44.392463       1 leaderelection.go:352] lock is held by m-e-1-cluster-gtb2x-worker-weurope-standard-e-4as-v4-2-pdrd9 and has not yet expired
> csi-azurefile-controller-579d6bf79-7qnj7 csi-resizer I0825 08:59:44.392487       1 leaderelection.go:247] failed to acquire lease kube-system/external-resizer-file-csi-azure-com
> csi-azurefile-controller-579d6bf79-7qnj7 csi-snapshotter I0825 08:59:45.152929       1 leaderelection.go:352] lock is held by m-e-1-cluster-gtb2x-worker-weurope-standard-e-4as-v4-2-pdrd9 and has not yet expired
> csi-azurefile-controller-579d6bf79-7qnj7 csi-snapshotter I0825 08:59:45.152973       1 leaderelection.go:247] failed to acquire lease kube-system/external-snapshotter-leader-file-csi-azure-com
> csi-azurefile-controller-579d6bf79-7qnj7 csi-attacher I0825 08:59:50.920755       1 leaderelection.go:352] lock is held by m-e-1-cluster-gtb2x-worker-weurope-standard-e-4as-v4-2-pdrd9 and has not yet expired
> csi-azurefile-controller-579d6bf79-7qnj7 csi-attacher I0825 08:59:50.920785       1 leaderelection.go:247] failed to acquire lease kube-system/external-attacher-leader-file-csi-azure-com
> csi-azurefile-controller-579d6bf79-7qnj7 csi-resizer I0825 08:59:52.645733       1 leaderelection.go:352] lock is held by m-e-1-cluster-gtb2x-worker-weurope-standard-e-4as-v4-2-pdrd9 and has not yet expired
> csi-azurefile-controller-579d6bf79-7qnj7 csi-resizer I0825 08:59:52.645751       1 leaderelection.go:247] failed to acquire lease kube-system/external-resizer-file-csi-azure-com
> csi-azurefile-controller-579d6bf79-7qnj7 csi-provisioner I0825 08:59:53.268596       1 leaderelection.go:350] lock is held by m-e-1-cluster-gtb2x-worker-weurope-standard-e-4as-v4-2-pdrd9 and has not yet expired
> ```

@gmcbrien that's actually expected since you have 2 controller pods, one is backup, the other is primary.

**Comment by gmcbrien** [comment]
Thanks Andy, so the question remains, who / what is providing the GRPC response? `GRPC response: {"capacity_bytes":1024}`
It appears that the request is correct, but the response is wrong.

**Comment by andyzhangx** [comment]
@gmcbrien what's your csi driver version?

**Comment by andyzhangx** [comment]
aha, I see, this issue was fixed by https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/478 in v1.5.0

**Comment by gmcbrien** [comment]
Good find Andy, I did search through closed issues, but didn't manage to see this. I think we can close this bug and we'll get to upgrading our csi driver (which I think is still on 0.9.0)
