### ISSUE TITLE
Deployment CSI driver but can not work

### ISSUE THREAD

**Issue by JayChanggithub** [kubernetes-sigs/azurefile-csi-driver#775]
I plan to deploy the azure CSI for supporting StorageClass objects within my own kubernetes cluster(not AKS). And i follow up   
the [docs](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/read-from-secret.md) that i confuse this step **`"specify different cloud config secret in driver deployment"`** whats mean in this ?. And i already create azure.json and generate the secret via my azure tenant. Whether deploy this Azure CSI driver in own kubernetes cluster?

**Comment by andyzhangx** [comment]
to store cloud config, you could create `azure.json` or k8s secret

**Comment by JayChanggithub** [comment]
Yes. I have been use azure.json to generate secret of my kubernetes resource that according to [docs](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/read-from-secret.md) step 2 -> step 3. And i don't know which CSI driver deployment file to use it.  

```bash
# this is by azure.json to create it
$ kubectl get secret -n kube-system | grep azure                                                                                                                                                                                                                                                                                                                                                                               
azure-cloud-provider                             Opaque                                1      167m
```

**Comment by andyzhangx** [comment]
> Yes. I have been use azure.json to generate secret of my kubernetes resource that according to [docs](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/read-from-secret.md) step 2 -> step 3. And i don't know which CSI driver deployment file to use it. My question is about "specify different cloud config secret in driver deployment". Which file(configuration) should be modified for that?
> 
> ```shell
> # this is by azure.json to create it
> $ kubectl get secret -n kube-system | grep azure                                                                                                                                                                                                                                                                                                                                                                               
> azure-cloud-provider                             Opaque                                1      167m
> ```

@JayChanggithub  it would search secret `azure-cloud-provider` first, you could get disk controller logs to double check, follow: https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/csi-debug.md#case1-disk-createdeleteattachdetachsnapshotrestore-failed
