### ISSUE TITLE
Using fsgroup doen't redursively changes ownership and permissions on Azure files

### ISSUE THREAD

**Issue by mmillard0** [kubernetes-sigs/azurefile-csi-driver#837]
**What happened**:Using fsgroup in pod manifest doesn't changes ownership and permissions with Azure files.

**What you expected to happen**:Ownership and permissions changed with fsgroup id on the Azure file volume.

**How to reproduce it**:Here is pod, pvc and storageclass manifests:
apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
  namespace: application
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    fsGroupChangePolicy: "OnRootMismatch"
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: pvc-azurefile-2
  containers:
  - name: sec-ctx-demo
    image: busybox
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: persistent-storage
      mountPath: /mnt/azurefile
    securityContext:
      allowPrivilegeEscalation: false

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-2
provisioner: file.csi.azure.com
parameters:
  resourceGroup: xxxxxx
  storageAccount: xxxxxx
  shareName: xxxxxx
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azurefile-2
  namespace: application
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile-csi-2

**Results:**
kubectl exec -it security-context-demo -n application -- sh
/ $ id
uid=1000 gid=3000 groups=2000
/ $ cd /mnt/azurefile/
/mnt/azurefile $ ls -l
total 1
-rwxrwxrwx    1 root     root            10 Nov  4 07:54 fsgroup.txt
-rwxrwxrwx    1 root     root            10 Nov  3 17:57 nofsgroup.txt
-rwxrwxrwx    1 root     root             0 Nov  4 07:54 test

Here ownership and permission are set to root, I expected fsgroup id.

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:1.4
- Kubernetes version (use `kubectl version`):Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"c612f9dcf9cf5f6fda3ba3cd1c53b118c897f6c7", GitTreeState:"clean", BuildDate:"2021-10-21T03:30:46Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from /etc/os-release): Ubuntu 18.04.6 LTS
- Kernel (e.g. `uname -a`): 5.4.0-1061-azure
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
if you are using AKS, try upgrade to 1.21, it's fixed on 1.21 with Volume_mount_group capability; and if you don't want to upgrade, you could use gid, uid setting in storage class to workaround this issue:
https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/db9b0589cb59e43cca45eb686402e71ba31eb9a9/deploy/example/storageclass-azurefile-existing-share.yaml#L13-L17

**Comment by mmillard0** [comment]
@andyzhangx thanks for your quick response.
