### ISSUE TITLE
CSI driver fail to get cloud config secret but still runs without config

### ISSUE THREAD

**Issue by aurel333** [kubernetes-sigs/azurefile-csi-driver#838]
**What happened**:
After a cluster reboot, the `azurefile` container in the `csi-azurefile-node` pod tries to get the cloud config secret but fails due to a timeout after 30s. Then it tries to read the config in `/etc/kubernetes/azure.json` but fails because the config is in the secret and is not mounted in the container. Finally the container continue to run without a cloud config at all and never retries to get the config by refetching it or restarting.

Here are the logs:
```log
I1103 14:08:46.532666       1 azure.go:60] reading cloud config from secret
E1103 14:09:16.533973       1 azure_config.go:45] Failed to get cloud-config from secret: failed to get secret kube-system/azure-cloud-provider: Get "https://198.18.0.1:443/api/v1/namespaces/kube-system/secrets/azure-cloud-provider": dial tcp 198.18.0.1:443: i/o timeout
I1103 14:09:16.534006       1 azure.go:64] GetCloudProvider: failed to initialize cloud from secret kube-system/azure-cloud-provider: InitializeCloudFromSecret: failed to get cloud config from secret kube-system/azure-cloud-provider: failed to get secret kube-system/azure-cloud-provider: Get "https://198.18.0.1:443/api/v1/namespaces/kube-system/secrets/azure-cloud-provider": dial tcp 198.18.0.1:443: i/o timeout
I1103 14:09:16.534014       1 azure.go:69] could not read cloud config from secret
I1103 14:09:16.534023       1 azure.go:79] use default AZURE_CREDENTIAL_FILE env var: /etc/kubernetes/azure.json
I1103 14:09:16.534046       1 azure.go:98] no cloud config provided, error: load azure config from file(/etc/kubernetes/azure.json) failed with open /etc/kubernetes/azure.json: no such file or directory, driver will run without cloud config
```

**What you expected to happen**:
I expect that after the container fails to retrieve the config from the secret and from the file, it retries after a short delay or do something to restart the pod. I know doing this may disrupts some use cases so maybe adding a parameter for this would be better (with environment variables for example).

**How to reproduce it**:
This is the tricky part. For me it is due to the api server not responding but I think a similar situation can be reproduced by just not having a secret nor a file with the config

**Why it is an issue**:
Because the driver runs without a cloud config when it is supposed to, every attempt to mount an azurefile persistent volume in a pod on the same node fails, which can harm high availability services, block rollouts (especially when pod disruption budget are involved) and wastes time because the error is almost silent.

**Environment**:
- CSI Driver version: v1.4.0, commit 9a6614fda4242360a8d8edee3f794f2fe3e1a111
- Kubernetes version: v1.20.8, commit 092fbfbf53427de67cac1e9fa54aaa09a28371d7
- OS (e.g. from /etc/os-release): CentOS
- Kernel (e.g. `uname -a`): Linux 3.10.0-1127.19.1.el7.x86_64

**Comment by andyzhangx** [comment]
thanks, would adding a new feature flag `allow-no-cloud-config` (`true` by default) would solve this issue?

**Comment by aurel333** [comment]
I think that it would solve my issue because when I delete the faulty pods they are recreated and load the config correctly. Thank you for your quick answer.

**Comment by andyzhangx** [comment]
added `controller.allowEmptyCloudConfig` config in chart in master(v1.8.0), `--set controller.allowEmptyCloudConfig=false` would make controller crash without cloud config setting

**Comment by aurel333** [comment]
Thanks!
