### ISSUE TITLE
Is kube-system compulsory?

### ISSUE THREAD

**Issue by gmcbrien** [kubernetes-sigs/azurefile-csi-driver#850]
Hi,

I understand support requests should go to slack.k8s.io. Unfortunately, I don't find #sig-azure there. My question is simple, but I couldn't find anything in the documentation either:

Is it compulsory to install azurefile/azuredisk controller (and resulting 'csi-azurefile-node*' pods) in kube-system? The reason I ask is that pods in kube-system can prevent our Openshift Cluster Autoscaler from functioning correctly (athough I'm aware that workarounds exist). Source: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md

**Comment by andyzhangx** [comment]
you could install this driver on another namespace, `kube-system` is not required.

**Comment by gmcbrien** [comment]
Thanks for the fast reply.
