### ISSUE TITLE
Improve download of dependencies

### ISSUE THREAD

**Issue by msau42** [kubernetes-sigs/azurefile-csi-driver#873]
**Is your feature request related to a problem?/Why is this needed**

The script https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/hack/verify-helm-chart-files.sh#L52 is doing a "curl <script> | bash" [anti-pattern](https://sysdig.com/blog/friends-dont-let-friends-curl-bash/).

**Describe the solution you'd like in detail**

It would be better supply chain security if:
- The script being downloaded was checked into the repo directly so that we can validate it is safe.
- The tool needed is installed through a package manager and/or have the checksums validated.

**Describe alternatives you've considered**

**Additional context**

**Comment by andyzhangx** [comment]
We could use following command to install helm3 on Ubuntu, while that still requires curl, another option is `git clone` helm project and install helm, without curl, it would be harder.

https://helm.sh/docs/intro/install/

```console
curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
sudo apt-get install apt-transport-https --yes
echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
sudo apt-get update
sudo apt-get install helm
```

**Comment by msau42** [comment]
I think the sequence you suggested could work. One more suggestion I have is to checkin the signing key directly into the repo so it can be validated by a human.
