### ISSUE TITLE
use distroless image for driver image

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azurefile-csi-driver#894]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

original Dockerfile: https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/pkg/azurefileplugin/Dockerfile

**Describe alternatives you've considered**

**Additional context**

**Comment by olsenme** [comment]
@andyzhangx  could you please provide some more context here?

**Comment by andyzhangx** [comment]
that's a long term plan, we need to get standalone binary from these packaes: `cifs-utils util-linux e2fsprogs mount udev xfsprogs nfs-common netbase`, and use distroless base image, I have maked it as long term plan, it's not high priority now.
