### ISSUE TITLE
Cannot specify a specific OS revision when building azurefile/azuredisk csi driver Windows container

### ISSUE THREAD

**Issue by dzjiang91** [kubernetes-sigs/azurefile-csi-driver#898]
**What happened**:
The windows dockerfile for azurefile-csi-driver (https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/pkg/azurefileplugin/Windows.Dockerfile) does not support specifying a specific OS version (such as 10.0.17763.2458). The same issue also applies to azuredisk-csi-driver.

The servercore registry (gcr.io/k8s-staging-e2e-test-images/windows-servercore-cache) used Windows.Dockerfile contains only a limited subset of servercore images. As a result, we can only pull images against a major OS version like 1809 and ltsc2022 but not against a specific revision like 10.0.17763.2458.

**What you expected to happen**:
We are able to specify arbitrary OS versions when building azurefile/azuredisk CSI driver windows container as available in mcr.microsoft.com/windows/servercore or mcr.microsoft.com/windows/nanoserver.

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release): Windows
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
@mainred @AbelHu do you have any insights about how to support this?

**Comment by andyzhangx** [comment]
@dzjiang91 I could find `mcr.microsoft.com/windows/nanoserver:10.0.17763.2458` base image exists

I think you could add `10.0.17763.2458` in Makefile, and then build your own image, here is the diff:

```
# git diff
diff --git a/Makefile b/Makefile
index e61b1a059..e1366affb 100755
--- a/Makefile
+++ b/Makefile
@@ -42,7 +42,7 @@ ALL_OS = linux windows
 ALL_ARCH.linux = amd64 arm64
 ALL_OS_ARCH.linux = $(foreach arch, ${ALL_ARCH.linux}, linux-$(arch))
 ALL_ARCH.windows = amd64
-ALL_OSVERSIONS.windows := 1809 20H2 ltsc2022
+ALL_OSVERSIONS.windows := 1809 20H2 ltsc2022 10.0.17763.2458
 ALL_OS_ARCH.windows = $(foreach arch, $(ALL_ARCH.windows), $(foreach osversion, ${ALL_OSVERSIONS.windows}, windows-${osversion}-${arch}))
 ALL_OS_ARCH = $(foreach os, $(ALL_OS), ${ALL_OS_ARCH.${os}})
```

**Comment by dzjiang91** [comment]
@andyzhangx I am not sure if it would work because I cannot find image gcr.io/k8s-staging-e2e-test-images/windows-servercore-cache:1.0-linux-amd64-10.0.17763.2458.

As a workaround, I used a private docker file which reverts https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/476.

**Comment by mainred** [comment]
https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/476 speeded up the test but also brings less flexibility because gcr.io/k8s-staging-e2e-test-images/windows-servercore-cache that many archs and os support. I hit the issue when building arm64 Windows image.

**Comment by AbelHu** [comment]
I think that users should not specify a specific os version with the build number which will block getting the latest Windows image with the latest security patch.

**Comment by andyzhangx** [comment]
close this issue since we don't want to support it officially
