### ISSUE TITLE
LOCATION required in cloud.conf

### ISSUE THREAD

**Issue by haithamshahin333** [kubernetes-sigs/azurefile-csi-driver#906]
**What happened**:

When location is not specified in [cloud.conf](https://github.com/haithamshahin333/azure-redhatopenshift-concepts/blob/6cf803dbf03c22523e65164e153d6e440e92d10b/azure-files-csi-driver/script.sh#L37) there is an error in dynamically provisioning the storage account and nfs share.

**What you expected to happen**:

Did not expect the location field to be required.

**How to reproduce it**:

Run through the script here: [example-csi-azurefile-aro-setup](https://github.com/haithamshahin333/azure-redhatopenshift-concepts/blob/main/azure-files-csi-driver/script.sh). If `location` is left out of `cloud.conf`, it will not work. If you add it back, be sure to redeploy the controller before retrying on a new PVC so the conf is refreshed.

**Anything else we need to know?**:

**Environment**:

ARO
Server Version: 4.8.18
Kubernetes Version: v1.21.1+6438632

**Comment by andyzhangx** [comment]
@haithamshahin333 could you paste the detailed error? from the code, I could see location is hardcoded in `createPrivateEndpoint`, I will fix it.
