### ISSUE TITLE
Pods on one node "Unable to attach or mount volumes"

### ISSUE THREAD

**Issue by darose** [kubernetes-sigs/azurefile-csi-driver#911]
**What happened**:
On one node of our cluster(s), all new pods will suddenly start getting stuck in "Container Creating" state (and eventually time out and fail).  Performing a "describe pod" on one of them always shows the following:

```73s Warning FailedMount pod/<pod name> Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[<other volume> default-token-xxxxx data]: timed out waiting for the condition```

**What you expected to happen**:
New pods should mount the volume and start running.

**How to reproduce it**:
No way to reliably reproduce, but it has been recurring often on our clusters.  (I.e., every day or 2.)

**Anything else we need to know?**:
* This is on an AKS cluster.
* The "data" volume is a PVC.  The storage underlying the PVC is an Azure file share (set to ReadWriteMany).
* This only seems to happen on the large (96-core) nodes in our cluster.  The smaller nodes don't experience the issue.
* I see messages like the following in /var/log/messages on the offending node:
```Feb  9 23:32:37 aks-nodepoolX-XXXXX-vmssXXXXX kubelet[5727]: E0209 23:32:37.201125    5727 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/csi/file.csi.azure.com^<our resource group>#<our storage account>#<pv name># podName:10d23618-9f7c-49f0-a1b6-9dfea0f657fd nodeName:}" failed. No retries permitted until 2022-02-09 23:32:53.201089445 +0000 UTC m=+290077.968105329 (durationBeforeRetry 16s). Error: "UnmountVolume.TearDown failed for volume \"data\" (UniqueName: \"kubernetes.io/csi/file.csi.azure.com^<our resource group>#<our storage account>#<pv name>#\") pod \"10d23618-9f7c-49f0-a1b6-9dfea0f657fd\" (UID: \"10d23618-9f7c-49f0-a1b6-9dfea0f657fd\") : kubernetes.io/csi: mounter.TearDownAt failed: rpc error: code = Aborted desc = An operation with the given Volume ID <our resource group>#<our storage account>#<pv name># already exists"```
```...```
```Feb  9 23:32:37 aks-nodepoolX-XXXXX-vmssXXXXX kubelet[5727]: E0209 23:32:37.505727    5727 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/csi/file.csi.azure.com^<our resource group>#<our storage account>#<pv name># podName: nodeName:}" failed. No retries permitted until 2022-02-09 23:32:38.005702157 +0000 UTC m=+290062.772717941 (durationBeforeRetry 500ms). Error: "MountVolume.SetUp failed for volume \"pvc-4ac806d3-df65-4b19-94b6-d13d797becc9\" (UniqueName: \"kubernetes.io/csi/file.csi.azure.com^<our resource group>#<our storage account>#<pv name>#\") pod \"<pod name>\" (UID: \"19cfe3db-c724-4c8a-a0ee-4d6a5f02b8bf\") : rpc error: code = Aborted desc = An operation with the given Volume ID <our resource group>#<our storage account>#<pv name># already exists"```

* I also discovered that we have a way to clear the problem when it happens:  if we restart the kubelet on the offending node, the problem will clear, and the pods that are stuck in "Container creating" status will suddenly be able to successfully mount the PVC volume and then start running.

**Environment**:
- CSI Driver version: 1.2.0
- Kubernetes version (use `kubectl version`): 1.20.13
- OS (e.g. from /etc/os-release): Ubuntu 18.04.6 LTS
- Kernel (e.g. `uname -a`): 5.4.0-1064-azure
- Install tools: AKS
- Others:

**Comment by andyzhangx** [comment]
I think the azure file mount was broken at that time. if that issue happens, could you ssh to the node in problem and then run `mount | grep cifs`, and then try run `ls` on those cifs mount dirs, check the output.

**Comment by darose** [comment]
Thanks for the response @andyzhangx .

That's good news that this has been fixed in a later version of CSI driver.  Do you have a link to the github issue / PR number / release version that fixes it?  I looked through all the CSI driver release notes yesterday (https://github.com/kubernetes-sigs/azurefile-csi-driver/releases) but I didn't see anything related to this issue.  I'd like to upgrade our clusters to pick up the fix, but I'd need to know which version to upgrade to.

**Comment by andyzhangx** [comment]
> Thanks for the response @andyzhangx .
> 
> That's good news that this has been fixed in a later version of CSI driver. Do you have a link to the github issue / PR number / release version that fixes it? I looked through all the CSI driver release notes yesterday (https://github.com/kubernetes-sigs/azurefile-csi-driver/releases) but I didn't see anything related to this issue. I'd like to upgrade our clusters to pick up the fix, but I'd need to know which version to upgrade to.

@darose I did not say that this issue has been fixed since I am not sure about the original issue, need to find the root cause.

**Comment by darose** [comment]
> if that issue happens, could you ssh to the node in problem and then run `mount | grep cifs`, and then try run `ls` on those cifs mount dirs, check the output.

We just had this issue happen again, but I didn't get a chance to look at this output before someone on the team restarted the kubelet.  I'll check this next time this pops up.

**Comment by darose** [comment]
> @darose I did not say that this issue has been fixed since I am not sure about the original issue, need to find the root cause.

Ok sorry. I had assumed that when you said "the azure file mount was broken at that time" that there was a specific issue you were aware of that had been addressed.

Let me ask the question differently then:  if the file mount was "broken" back in v1.2.0, is there some minimum version that you would no longer consider broken?  I'd like us to upgrade, but I need to have some idea what to upgrade to.  (And I'm a little reluctant to upgrade to the latest (1.11.0) immediately as I'm concerned that that big a version jump could break something.)

**Comment by andyzhangx** [comment]
@darose I think this issue is mainly caused by azure file mount itself, related to remote azure file server issue.

**Comment by darose** [comment]
OK.  Any recommendations on how we might remedy it then?  It's becoming a big nuisance for our team.

**Comment by andyzhangx** [comment]
not sure about the original issue, if you hit that issue again, pls provide more details, and also share `/var/log/messages` on that  agent node, it's likely that azure file mount is broken.

**Comment by darose** [comment]
BTW, forgot to report back:  upgrading to a newer version of csi driver (v1.9.0) seems to have resolved this issue for us.
