### ISSUE TITLE
Error: rendered manifests contain a resource that already exists. Unable to continue with install: DaemonSet "csi-azurefile-node-win" in namespace "kube-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "azurefile-csi-driver"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kube-system"

### ISSUE THREAD

**Issue by mattduguid** [kubernetes-sigs/azurefile-csi-driver#919]
**What happened**: 
We have two existing AKS clusters that were built many months ago using terraform and "v1.4.0" of "azurefile_csi_driver" which are still running without issue. 

We have attempted standing up a brand new AKS cluster using terraform and the same "v1.4.0" and are receiving the following error, we have also tried the latest version "v1.11.0" and error is the same,

```hcl
Error: rendered manifests contain a resource that already exists. Unable to continue with install: DaemonSet "csi-azurefile-node-win" in namespace "kube-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "azurefile-csi-driver"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kube-system"
```
We also tried manual helm install and got the same error,

```bash
helm repo add azurefile-csi-driver https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts
helm install azurefile-csi-driver azurefile-csi-driver/azurefile-csi-driver --namespace kube-system --version v1.4.0
```

We then completely deleted and recreated everything (cluster/terraform state/etc) and exact same error came back.

**What you expected to happen**:
Expected it to just work like the other two as we haven't changed the resource since the first two were built.

**How to reproduce it**:
This is the terraform resource we use for the helm release,

```hcl
resource "helm_release" "azurefile_csi_driver" {
  atomic = true
  chart = "azurefile-csi-driver"
  name = "azurefile-csi-driver"
  namespace = "kube-system"
  repository = "https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/"
  version = var.helm_release_azurefile_csi_driver_version # we use -> v1.4.0
  timeout = 180 
  wait = true
  depends_on = [
    data.azurerm_kubernetes_cluster.azure,
  ]
}
```

**Anything else we need to know?**:
Given the error mentioned resources already existing we manually deleted each one that it mentioned and also removed all other related ones we could locate.

**Environment**:
- CSI Driver version:  v1.4.0 or v1.11.0
- Kubernetes version: 1.21.9 (all 3 clusters)
- OS: (AKS) Azure Kubernetes Service

**Comment by andyzhangx** [comment]
since you are already on AKS 1.21, Azure file CSI driver is already installed by default by AKS, you don't need to install CSI driver any more.

**Comment by mattduguid** [comment]
that would do it @andyzhangx we have commented out that part of the terraform install and things are now working as expected, thanks 😀
