### ISSUE TITLE
cannot install azure-csi-driver chart on AKS 1.22.6

### ISSUE THREAD

**Issue by dod38fr** [kubernetes-sigs/azurefile-csi-driver#925]
**What happened**:

I've tried to install azure-csi-driver chart on AKS 1.22.6. This cluster already contains some PVCs based on `file.csi.azure.com` and `kubernetes.io/azure-file` inherited from previous AKS versions

The installation fails with (output is slightly reformatted to be more readable):
```
$ helm install azurefile-csi-driver azurefile-csi-driver/azurefile-csi-driver --namespace kube-system --version v1.12.0 --set \
serviceAccount.node=csi-azurefile-node-sa-helm
Error: rendered manifests contain a resource that already exists. 
Unable to continue with install: ClusterRole "csi-azurefile-node-secret-role" in namespace "" exists  and cannot be imported into the current release: 
  invalid ownership metadata; label validation 
 error: missing key "app.kubernetes.io/managed-by": must be set to "Helm";
 annotation validation error: missing key "meta.helm.sh/release-name": must be set to "azurefile-csi-driver"; 
 annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "kube-system"
```

**What you expected to happen**:

Installation without conflicts with existing resources installed by AKS.

**Environment**:
- CSI Driver version:
`azurefile-csi-driver/azurefile-csi-driver       v1.12.0         latest          Azure File Container Storage Interface (CSI)`
- Kubernetes version (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6",`
- OS (e.g. from /etc/os-release): `Debian GNU/Linux bookworm/sid`
- Kernel (e.g. `uname -a`): `5.16.0-2-amd64 #1 SMP PREEMPT Debian 5.16.10-1 (2022-02-18)`
- Install tools: `helm`
- Others:

**Comment by andyzhangx** [comment]
azure file csi driver is already installed by default on aks 1.21+, it's managed by aks, so you can not install open source one now.

**Comment by dod38fr** [comment]
ok. Thanks for the reply.

All the  best
