### ISSUE TITLE
Mount options cannot overwrite in azurefile-csi-driver for NFS

### ISSUE THREAD

**Issue by Li-Shiang-Chi** [kubernetes-sigs/azurefile-csi-driver#956]
When I trying to using azurefile-csi-driver I create a storage class with nfs parameters configured.
<img width="942" alt="image" src="https://user-images.githubusercontent.com/6930223/160629856-c5fa7852-dcc8-48f0-8f44-d7a7dc10ccd5.png">

And my persistentVolumeClaim using this storage class to create PV, PVC
<img width="317" alt="image" src="https://user-images.githubusercontent.com/6930223/160630003-ff739842-c934-40b4-bac7-d5d3aa87cb06.png">

When I launch the pod using the persistent volume claim reference it shows the mount option is still using `mount -t nfs nconnect=8....` and this `nconnect=8` is only supported with linux kernel version >=5.3

Can I have a way to disable the default mount option to prevent this issue since my image & node kernel version is 4.X

![image](https://user-images.githubusercontent.com/6930223/160630640-f481a4c2-2fc2-481c-971e-8c341ee58857.png)

cc @andyzhangx

**Comment by Li-Shiang-Chi** [comment]
Hi andy thanks for the quick reply. My storage class is set with 
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/6930223/160633532-361e94d3-d41d-48e2-bd06-1deb05671add.png">

Or can i have a quick teams call with you?

**Comment by andyzhangx** [comment]
could you create a new pvc with the the storage class? I think your original pvc does not work since it uses the sc with `nconnect` setting.

**Comment by andyzhangx** [comment]
I am pretty sure that `nconnect` is not hard coded in this driver.

**Comment by Li-Shiang-Chi** [comment]
Hi @andyzhangx , your comment triggers me that I found my POD using the other PVC from another namespace and it was set with `nconnect=8`. After I create another PVC with the right storage class it mount successfully! Big careless for me orz... Finally, thanks for your quick response even it is late night for you. Big thanks to you!
