### ISSUE TITLE
Add the possibility to use managed identity for inline volume mount  instead of account name-account key secret

### ISSUE THREAD

**Issue by versoris** [kubernetes-sigs/azurefile-csi-driver#958]
I want to get rid of storage account secret (account name/account key) for security reason.  

I would like to use managed identity instead but it seems only possible to do it via storage class / PV / PVC.  For different reason it's not viable in  my context as I need to use inline volume mount.

Would be great to have the possibility to configure the storage  name in the inline volume mount parameter and let the kubelet managedId fetch the storage account key from the storage account :

kind: Pod
apiVersion: v1
metadata:
  name: busybox-azure-file
spec:
  containers:
    name: busybox
    image: myowncr/busybox:latest
    command:
        sh
        -c
        "exec tail -f /dev/null"
    volumeMounts:
      - mountPath: /mnt/azure/testinline
        name: azuretestinline
  volumes:
    csi:
      driver: file.csi.azure.com
      volumeAttributes:
        shareName: myfile/mydata
        **storageaccountname: myazurestorageaccount**
        **resourceGroup: notmyaksresourcegroup**
    name: azuretestinline

Right now I'm using csi-azure file version : v1.11.0 , k8s version : 1.21.7

**Comment by andyzhangx** [comment]
@versoris with a minor change, we could support this scenario, while we forbid this scenario because user could access any account just with pod configurations. Are you using AKS or open source CSI driver version?

**Comment by versoris** [comment]
@andyzhangx I use AKS CSI driver version
