### ISSUE TITLE
Error: flag provided but not defined: -allow-inline-volume-key-access-with-idenitity

### ISSUE THREAD

**Issue by pbtrudel** [kubernetes-sigs/azurefile-csi-driver#968]
**What happened**: Installing latest chart, the csi-azurefile-node pod crashloops with the following error:
flag provided but not defined: -allow-inline-volume-key-access-with-idenitity

**What you expected to happen**: Installation should be successful and pod should be running

**How to reproduce it**: Install latest chart v1.14.0

**Anything else we need to know?**: There seems to be a typo in commit e2be2c3fde34ec8423ef21030142dbcdbd96c599 for this flag

**Environment**:
- CSI Driver version: latest
- Kubernetes version (use `kubectl version`): v1.22.5
- OS (e.g. from /etc/os-release): Any
- Kernel (e.g. `uname -a`): 5.10.16.3-microsoft-standard-WSL2
- Install tools: helm
- Others:

**Comment by pbtrudel** [comment]
Hi @andyzhangx , this works now with the image. The typo on the word "idenitity" (there is an extra i character) is still there, but the pod runs fine now.

**Comment by ysma500** [comment]
@andyzhangx In this [PR](https://github.com/kubernetes-sigs/azurefile-csi-driver/commit/e2be2c3fde34ec8423ef21030142dbcdbd96c599) some typos were introduced. 

Line 115: [csi-azurefile-node-windows.yaml](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/charts/latest/azurefile-csi-driver/templates/csi-azurefile-node-windows.yaml)
Line 109: [csi-azurefile-node.yaml](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/charts/latest/azurefile-csi-driver/templates/csi-azurefile-node.yaml)
Line 52: [main.go](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/pkg/azurefileplugin/main.go)

"allow-inline-volume-key-access-with-idenitity" should probably be "allow-inline-volume-key-access-with-identity"
