### ISSUE TITLE
[feature request] support snapshot for NFSv4 file share

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azurefile-csi-driver#979]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

that's a long term plan since support snapshot for NFSv4 file share feature is not ready yet:
https://docs.microsoft.com/en-us/azure/storage/files/files-nfs-protocol#support-for-azure-storage-features

**Describe alternatives you've considered**

**Additional context**

**Comment by iusergii** [comment]
Wonder if there is any dependency ticket to follow for a support snapshot for NFSv4?

**Comment by jkroepke** [comment]
@andyzhangx seems like its now in preview

https://azure.microsoft.com/de-de/blog/whats-new-with-azure-files/

**Comment by andyzhangx** [comment]
close this issue since I have verified that as long as this backend snapshot feature is supported in specific azure region, this feature is already working on that region, from CSI driver side, there is no code change as long as backend snapshot feature is enabled on that region.
